### ISSUE TITLE
Returning List<LikedHashMap> for the type List<UserType> 

### ISSUE THREAD

**Issue by 4rpit** [vladmihalcea/hibernate-types#10]
Hi, 
I am using the library to cast JSON from DB to a List<UserType> object like this.
```

@Column(columnDefinition = "json", name = "USERTYPE")
    @Type(type = "json")
    private List<UserType> userType; 
```
```

public class UserType implements Serializable { 
    
private FunctionEnum key;
    private List<Users> users

    public UserType(){

    }
 public FunctionEnum getKey() {
        return coefficientKey;
    }

    public List<User> getUser() {
        return user;
    }
}
```

```
public class User {

    private String name

    private Integer value

    public String getName() {
        return name;
    }

    public Integer getValue() {
        return value;
    }

}
```

Any help why I am getting a return of List<LikedHashMap> not of List<UserType>

**Comment by vladmihalcea** [comment]
As noted in the provided examples, only Java Beans are supported, not Lists of Java Objects. At some point, I will investigate how to do that. I created [this issue](https://github.com/vladmihalcea/hibernate-types/issues/11) for this feature. 

Meanwhile, just wrap the `List<UserType>`  into a `UserTypeHolder` object which contains the `List<UserType>`, and it will work like a charm.

**Comment by 4rpit** [comment]
Thanks for your quick response, I will try it and let you know.
