### ISSUE TITLE
Postgres UUID array support

### ISSUE THREAD

**Issue by racevedoo** [vladmihalcea/hibernate-types#104]
Hi,

Are there any plans to support postgres uuid arrays?

Thanks!

**Comment by vladmihalcea** [comment]
If you want this feature, you need to implement it and send a Pull Request. I'll review it when it's ready.

**Comment by racevedoo** [comment]
I have a version that apparently works for `hibernate-types-52`, but I'd like some validations on your end before I implement for the other versions.

I'll open the PR now with `hibernate-types-52` only, and if the solution looks good, I can replicate for other hibernate versions. Sounds good?

**Comment by vladmihalcea** [comment]
Sounds great!

**Comment by racevedoo** [comment]
PR: https://github.com/vladmihalcea/hibernate-types/pull/105

**Comment by vladmihalcea** [comment]
Applied upstream, thanks
