### ISSUE TITLE
What about ipv6

### ISSUE THREAD

**Issue by aardbol** [vladmihalcea/hibernate-types#108]
I'm looking into using the Inet class; but it seems like only ipv4 is supported, looking at Inet4Address. What about ipv6? It's 2019 you know :-)

**Comment by vladmihalcea** [comment]
Have you tested it for Ipv6? It might work just fine.

**Comment by aardbol** [comment]
I haven't because I haven't gotten Inet to work so far unfortunately

**Comment by vladmihalcea** [comment]
I'll test it too when I have some time. It could work just fine.

**Comment by aardbol** [comment]
You're right. I tested the class separately and IPv6 is handled correctly.
