### ISSUE TITLE
Add support for List, Set, Map to be saved as JSON

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#11]
Investigate and add support for List, Set, and Map of Pojos to be saved as JSON.

**Comment by UltimaPhoenix** [comment]
Hello I really like your project, to do that in the past I created a `TypeReferenceFactory` like these
```
public interface TypeReferenceFactory {
    TypeReference<?> newTypeReference();
}
```

Each field that contains a generic definition is linked to an inner `TypeReferenceFactory` that is used to generate a `TypeReference`
```
public class EntityGeneric {

  @Type(type = "json", parameters = {
       @Parameter(name = TYPE_REFERENCE_FACTORY, value = "com.vladmihalcea.hibernate.type.model.EntityGeneric$InnerTypeRef")
  })
  @Column(columnDefinition = "json")
  Map<EntityType, String> field;


  enum EntityType {
    TYPE_0
    TYPE_1;
  }

  public static class InnerTypeRef implements TypeReferenceFactory {
    @Override
    public TypeReference<Map<KYCStatus, String>> newTypeReference() {
      return new TypeReference<Map<KYCStatus, String>>() {
    };
  }
}
```
then every time the field is deserialized through the `ObjectMapper` the method with `TypeReference` as arg can be used in place of the one with `Class`.

If you like my idea I can try to extend your code and submit a pull request.

**Comment by vladmihalcea** [comment]
Looks great. Send me a Pull Request. Thanks.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Comment by OrangeDog** [comment]
Was this (re)moved? I don't see `TypeReferenceFactory` in 2.13.0.
