### ISSUE TITLE
YearMonthTypeDescriptor failed to wrap null value from database in use case of YearMonthIntegerType 

### ISSUE THREAD

**Issue by sereysopheak-gl** [vladmihalcea/hibernate-types#113]
When using YearMonthIntegerType for YearMonth object. The YearMonthTypeDescriptor could not handle null value from database. YearMonth.of(0, 0) throw DateTimeException

**Comment by vladmihalcea** [comment]
Good catch. You should send a Pull Request with a fix for it.

**Comment by JWGmeligMeyling** [comment]
So the issue is with a `0` value rather than `NULL` right?

Because it seems `NULL` is properly handled here: https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/basic/internal/YearMonthTypeDescriptor.java#L61

`0` is indeed an invalid value for month in Java, but I would consider it a mapping error. You probably should change your database to use `null` instead.

**Comment by vladmihalcea** [comment]
This issue is probably invalid since `YearMonth.of(0, 0)` is not a valid `YearMonth` anyway.

**Comment by sereysopheak-gl** [comment]
You are right that ```YearMonth.of(0, 0)``` is not valid and I want to value to be null instead of ```YearMonth.of(0, 0)```. But even though the null was set in database, hibernate will map it to ```0``` hence the ```value = 0``` not ```null``` in the method ```public <X> YearMonth wrap(X value, WrapperOptions options)``` which cause ```DateTimeException``` to throw.

**Comment by vladmihalcea** [comment]
Thanks for the explanation. I reopened it and scheduled it for 2.9.0.

**Comment by sereysopheak-gl** [comment]
That's great. Thanks.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by finn0s** [comment]
I have a similar problem with the Month type. I save the value as a string (with the @Enumerated(EnumType.STRING) annotation)
This works fine in Hibernate 5 but after the upgrade to hibernate 6 i got the following error:

`java.time.DateTimeException: Invalid value for MonthOfYear: 0
	at java.base/java.time.Month.of(Month.java:187)
	at com.vladmihalcea.hibernate.type.basic.internal.Iso8601MonthMonthTypeDescriptor.wrap(Iso8601MonthMonthTypeDescriptor.java:50)
	at com.vladmihalcea.hibernate.type.basic.internal.Iso8601MonthMonthTypeDescriptor.wrap(Iso8601MonthMonthTypeDescriptor.java:12)
	at org.hibernate.type.descriptor.jdbc.IntegerJdbcType$2.doExtract(IntegerJdbcType.java:88)
	at org.hibernate.type.descriptor.jdbc.BasicExtractor.extract(BasicExtractor.java:44)
	at com.vladmihalcea.hibernate.type.MutableType.nullSafeGet(MutableType.java:100)`

**Comment by vladmihalcea** [comment]
@finn0s Try to create a replicating test case in this repository and send a Pull Request with it so we can see it in action.

**Comment by finn0s** [comment]
I've created a small example with the **hibernate-test-case-templates** repo. In this environment the  @Enumerated Annotation doest work at all (the table cannot be created by hibernate)

Here is the example: [example.zip](https://github.com/vladmihalcea/hypersistence-utils/files/11406414/example.zip)

**Comment by vladmihalcea** [comment]
Now, try to debug it and see what's causing the issue. If you find that it's a Hibernate issue, then you'll have to open a Hibernate issue.
