### ISSUE TITLE
Disable ad banner

### ISSUE THREAD

**Issue by joost-de-vries** [vladmihalcea/hibernate-types#114]
I don't enjoy having ads in my application log. 
For anybody who feels the same: setting the following logger to WARN hides it:
```
logging.level.logging.level.com.vladmihalcea.hibernate.type.util.Configuration: WARN
```

**Comment by vladmihalcea** [comment]
Setting the log level to WARN will prevent you from seeing other log entries as well. The framework comes with a setting allowing you to disable the banner:

`hibernate.types.print.banner=false`
