### ISSUE TITLE
Add support for the PostgreSQL TSVector column type

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#115]
PostgreSQL defines the `TSVector` column type that should be supported.

**Comment by chaoyangnz** [comment]
please merge, please

**Comment by vladmihalcea** [comment]
I will as soon as someone shows me an example of using it in a production system.

Check out the thread for the PR for more details.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by ajeyaraj03** [comment]
PostgreSQLTSVectorType.java is not available in hibernate-types-52, Isit not supported anymore?

**Comment by vladmihalcea** [comment]
@ajeyaraj03 Of course, it's there. You probably don't use the [2.8.0 version](https://search.maven.org/artifact/com.vladmihalcea/hibernate-types-52/2.8.0/jar).

**Comment by ajeyaraj03** [comment]
in 2.8.0 i dont see that its there in hibernate-types-5 but not in hibernate-types-52 @vladmihalcea can you help which latest version has this class?

**Comment by ajeyaraj03** [comment]
https://github.com/vladmihalcea/hibernate-types/tree/master/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/basic

master branch

**Comment by ajeyaraj03** [comment]
@vladmihalcea  I meant in master branch. But i am getting the error for the same in hibernate > 5.2 am using. 

  <hibernate.version>5.3.9.Final</hibernate.version>
        <hibernate-types.version>2.8.0</hibernate-types.version>


getting below error:

Caused by: java.lang.AbstractMethodError: Receiver class com.vladmihalcea.hibernate.type.basic.PostgreSQLTSVectorType does not define or inherit an implementation of the resolved method abstract isDirty(Ljava/lang/Object;Ljava/lang/Object;[ZLorg/hibernate/engine/spi/SharedSessionContractImplementor;)Z of interface org.hibernate.type.Type.
	at org.hibernate.type.TypeHelper.findDirty(TypeHelper.java:315)
	at org.hibernate.persister.entity.AbstractEntityPersister.findDirty(AbstractEntityPersister.java:4406)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.dirtyCheck(DefaultFlushEntityEventListener.java:569)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.isUpdateNecessary(DefaultFlushEntityEventListener.java:226)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:153)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:235)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:94)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:38)

**Comment by vladmihalcea** [comment]
It does implement that. The reason you get that error is that you have multiple versions of Hibernate in your classpath. Run `mvn dependency:tree` and you'll see where do you get multiple versions of Hibernate in your classpath.

**Comment by ajeyaraj03** [comment]
thats looks fine. @vladmihalcea  i was using hibernate-types-5

@vladmihalcea  are you sure PostgreSQLTSVectorType class is there?

  <dependency>
            <groupId>com.vladmihalcea</groupId>
            <artifactId>hibernate-types-52</artifactId>
            <version>2.8.0</version>
        </dependency>

**Comment by vladmihalcea** [comment]
> thats looks fine. @vladmihalcea i was using hibernate-types-5

You said you are using 5.2. Now, you say you are using 5 instead.

> @vladmihalcea are you sure PostgreSQLTSVectorType class is there?

Check it out on Maven Central, expand the dependency and see it for yourself. It should be there.

> com.vladmihalcea hibernate-types-52 2.8.0

And, now we're back to 5.2. Your message makes no sense. You are either using the 5 or the 5.2 dependencies.

> Where is the source code for > 5.2 is kept can you share the link.

The source code is on GitHub. And, there's the source code that you can also get from Maven Central.

**Comment by ajeyaraj03** [comment]
![source52](https://user-images.githubusercontent.com/3338673/71641049-5aacc500-2cbb-11ea-93fc-d83615b0c108.png)
[hibernate-types-52-2.8.0-sources.zip](https://github.com/vladmihalcea/hibernate-types/files/4014027/hibernate-types-52-2.8.0-sources.zip)

@vladmihalcea  check this

**Comment by vladmihalcea** [comment]
Of course it's there. You're just not searching it in the right folder.

![`PostgreSQLTSVectorType.java`](https://user-images.githubusercontent.com/5571399/71641233-ff6dd900-2ca0-11ea-9ad5-765941f7f919.png)

**Comment by md-farhan-memon** [comment]
@vladmihalcea can you please help me understand the usage for the same? I can't find anything related to this on the internet.
I am using Springboot, JPA with Hibernate 5.4. Java11.
How do I define an attribute in my entity model?

**Comment by vladmihalcea** [comment]
Support is offered via [consulting](https://vladmihalcea.com/consulting/). If your company is interested in my services, let me know.

**Comment by franciscoq3** [comment]
Hi @vladmihalcea 
Im having this issue with hibernate-types-52 2.21.1, can you please help me?
 
postgres  version 10.21-1
Hibernate version 5.6.9.Final
com.vladmihalcea  hibernate-types-52 2.21.1

Database Column definition 
 search_tokens    tsvector,
 
Spring boot hibernate mapping

 @Column(name = "search_tokens")
  private PostgreSQLTSVectorType searchTokens;
  
 public PostgreSQLTSVectorType getSearchTokens() {
        return searchTokens;
    }
 
 public void setSearchTokens(PostgreSQLTSVectorType searchTokens) {
        this.searchTokens = searchTokens;
    }
    
    
    Error : 
   
    org.springframework.orm.jpa.JpaSystemException  Could not set field value ['itslagomarcino45':2 'yes':1] value by reflection : [class com.XXX.domain.Questionnaire.searchTokens] setter of com.XXX.domain.Questionnaire.searchTokens; nested exception is org.hibernate.PropertyAccessException: Could not set field value ['itslagomarcino45':2 'yes':1] value by reflection : [class com.exammed.domain.Questionnaire.searchTokens] setter of com.exammed.domain.Questionnaire.searchTokens
    Caused by: java.lang.IllegalArgumentException: Can not set com.vladmihalcea.hibernate.type.search.PostgreSQLTSVectorType field com.XXX.domain.Questionnaire.searchTokens to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.hibernate.property.access.spi.SetterFieldImpl.set(SetterFieldImpl.java:52)
	... 182 more

**Comment by vladmihalcea** [comment]
@franciscoq3 I provide support via [consulting](https://vladmihalcea.com/consulting/) if you're interested.

**Comment by franciscoq3** [comment]
Hi @vladmihalcea I understand that you support via consulting, but  I will like please to have a  code example of the library then If need more help we can talk about it

**Comment by vladmihalcea** [comment]
In the test folder, you can find integration tests that offer examples of how you can use certain features.

**Comment by franciscoq3** [comment]
Hi @vladmihalcea  the integration tests helped me to fix the issues. Thanks !

**Comment by vladmihalcea** [comment]
I'm glad you found the problem
