### ISSUE TITLE
ImmutableType should also implement the Type interface

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#119]
Because `UserType` does not extend the Hibernate `Type` contract, we cannot provide a custom Type for a scalar result in a native SQL query as in the following example:

```
List<Tuple> tuples = entityManager
.createNativeQuery(
	"SELECT " +
	"  id, " +
	"  account_id, " +
	"  created_on - FIRST_VALUE(created_on) OVER ( " +
	"    PARTITION BY account_id " +
	"    ORDER BY created_on " +
	"    RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING " +
	"  ) AS since_first_transaction, " +
	"  LAST_VALUE(created_on) OVER ( " +
	"    PARTITION BY account_id " +
	"    ORDER BY created_on " +
	"    RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING " +
	"  ) - created_on AS until_last_transaction " +
	"FROM account_transaction " +
	"ORDER BY id", Tuple.class)
.unwrap(org.hibernate.query.NativeQuery.class)
.addScalar("since_first_transaction", PostgreSQLIntervalType.INSTANCE)
.getResultList(); 
```

The easiest way to fix this is to make the `ImmutableType` implement the `Type` contract as well.

This way, we can deal with the [`No Dialect mapping for JDBC type`](https://vladmihalcea.com/hibernate-no-dialect-mapping-for-jdbc-type/) at the SQL query level, no matter if the associated type implements the Hibernate `org.hibernate.type.Type` or `org.hibernate.usertype.UserType`.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by mfur** [comment]
Hi, probably not appropriate place for this but it is directly related.

I'm using hypersistence-utils-hibernate-62 with hibernate 6.2. When I try to add custom type as a scalar result:

```
Query query = em.createNativeQuery(query.unwrap(NativeQuery.class)
		.addScalar("operation_time", PostgreSQLPeriodType.INSTANCE);
```

Type is not accepted and can not be cast:

_The method addScalar(String, BasicTypeReference) in the type NativeQuery is not applicable for the arguments (String, PostgreSQLPeriodType)_

or

_java.lang.ClassCastException: class io.hypersistence.utils.hibernate.type.interval.PostgreSQLPeriodType cannot be cast to class org.hibernate.metamodel.model.domain.BasicDomainType (io.hypersistence.utils.hibernate.type.interval.PostgreSQLPeriodType and org.hibernate.metamodel.model.domain.BasicDomainType are in unnamed module of loader com.ibm.ws.classloading.internal.AppClassLoader @656f8f18)_

Am I doing something wrong?

**Comment by vladmihalcea** [comment]
@mfur I created #609 for this
