### ISSUE TITLE
Support PostgreSQL geometric types

### ISSUE THREAD

**Issue by mayb32** [vladmihalcea/hibernate-types#120]
Can this library introduce mapping for PostgreSQL geometric types like Point, Box, Circle etc? I can create pull request. On other side there is hibernate-spatial lib.

**Comment by vladmihalcea** [comment]
Hibernate Spatial might already cover these types, so you need to check out. Most likely, it's better to add support for those geospatial types in Hibernate Spatial which already adds the required dependencies.
