### ISSUE TITLE
Initialize PostgreSQLEnumType programmatically

### ISSUE THREAD

**Issue by JWGmeligMeyling** [vladmihalcea/hibernate-types#124]
I am trying to create a `TypedParameterValue` (from your blogpost https://vladmihalcea.com/bind-custom-hibernate-parameter-type-jpa-query/ ) for a `PostgreSQLEnumType`. In order to do so I use:

```java
PostgreSQLEnumType enumType = new PostgreSQLEnumType();
Properties properties = new Properties();
properties.put("enumClass", EnumClass.class.getName());
properties.put("useNamed", true);
enumType.setParameterValues(properties);
Enum enumValue = ...
query.setParameter("param", new TypedParameterValue(enumType, enumValue));
```

Obivously, the properties have to be set, because `EnumType`, the base type for `PostgreSQLEnumType` is a `DynamicParameterizedType`, and requires the enum classname to be set through properties for it not to fail with an NPE.

However, invoking `setParameterValues` requires `typeConfiguration`, which is set through `setTypeConfiguration`, as the type is `TypeConfigurationAware`. Because our type is instantiated programmatically, this `typeConfiguration` is `null`.

A couple of questions:

1. Can we add an additional constructor to `PostgreSQLEnumType` of the format `PostgreSQLEnumType(Class<Enum> clasz)`? However, the most tricky part of this:
2. How to get hold of a `TypeConfiguration` object?
3. Or: can the `PostgreSQLEnumType` be rewritten so that the `TypeConfiguration` is not required anymore? (We would have to replace the manner of construction of the `EnumJavaTypeDescriptor`, but in order to do so probably end up override all of the `EnumType` implementation - as its private).

I have also thought of registering the type globally and looking it up somewhere from Hibernate, but so far I haven't been able to get this to work.

I think we can also conclude that the fact that `PostgreSQLEnumType` is a `TypeConfigurationAware DynamicParameterizedType` renders the presence of the singleton `PostgreSQLEnumType.INSTANCE` useless, as it cannot be used in that fashion.

**Comment by vladmihalcea** [comment]
What if we add the following constructor:

```
public PostgreSQLEnumType(Class enumClass) {
	this();
	setTypeConfiguration(new TypeConfiguration() {
		@Override
		public JavaTypeDescriptorRegistry getJavaTypeDescriptorRegistry() {
			return new JavaTypeDescriptorRegistry(this) {
				@Override
				public JavaTypeDescriptor getDescriptor(Class javaType) {
					return new EnumJavaTypeDescriptor(enumClass);
				}
			};
		}
	});
}
```

Would that work in your case? Basically, we just have to use a custom `TypeConfiguration` that returns the right `EnumJavaTypeDescriptor` we need to avoid the NPE.

**Comment by JWGmeligMeyling** [comment]
Let me test, thanks for the tip! I'll get back to you soon. I'll provide my test / changes as PR if they work.

**Comment by JWGmeligMeyling** [comment]
The combination of our fixes worked, also applied the same to the enum array type in my PR.

**Comment by vladmihalcea** [comment]
Thanks. I'll review it when I have some time.

**Comment by vladmihalcea** [comment]
Fixed.
