### ISSUE TITLE
Feature request: Abstract class (ie: generic storage)

### ISSUE THREAD

**Issue by Emmenemoi** [vladmihalcea/hibernate-types#13]
The json mapper can't work if the defined class is Abstract or Object.
The purpose of jsonb column being to be able to store variable properties objects, it makes sense that the provided code allows storing at least a hierarchy of objects in the same column - or even any object if the Hibernate type is "Object".

To allow this, we could split the storage in 2 derived columns: "<original_name>_object" and "<original_name>_class".

I tried to implement it (doesn't seams so difficult), but couldn't find easily a 5.2 example...

**Comment by vladmihalcea** [comment]
You can store anything you want via a `JsonNode` object which does not require any specific structure. You can then do the transforming from `JsonNode` which can contain a `_class` property so you can further transform the JSON into a type-safe `Object` in the application if you want.

**Comment by UltimaPhoenix** [comment]
@Emmenemoi Generally the feature request #3 will allow you to manage this by configuring the ObjectMapper properly. However if you have an Abstract class, you can annotate it with `@JsonTypeInfo` in order to manage polymorphism (jackson will do the job for you).

**Comment by Emmenemoi** [comment]
Not se easy to configure, but @UltimaPhoenix's solution was the way to go. Works perfectly.
