### ISSUE TITLE
Mapping Enum to a String column uses toString() instead of name()

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vladmihalcea/hibernate-types#135]
I have a field in an entity like
```
...
@Type( type = "pgsql_enum" )
@Enumerated(EnumType.STRING)
private MyEnum myEnum;
...
```
where `MyEnum` is defined as 
```
public enum MyEnum{
    PROP_A {
        @Override
        public String toString() {
            return "Prop A";
        }
    }
}
```
I expected that in my db the field would be `PROP_A` but I find that it is `Prop A` which indicates that the conversion is using the `toString()` representation of enum whereas I believe `name()` would be more appropriate since `toString()` is overridable and `name()` is not.
Is there a workaround or a configuration property I have overlooked?

**Comment by vladmihalcea** [comment]
You need to use `@Enumarated` to map Java Enum:

    @Enumerated(EnumType.STRING)
    @Column(length = 8)
    private MuEnum myEnum;

Why would you use a Jsonb column to store an Enum when you are better off using a String or an Integer. Check out [this article for more details](https://vladmihalcea.com/the-best-way-to-map-an-enum-type-with-jpa-and-hibernate/).

**Comment by SayakMukhopadhyay** [comment]
Sorry, it has been a long day and I copy pasted the wrong part of the code.
My actual code entity field is as such
```
@Type( type = "pgsql_enum" )
@Enumerated(EnumType.STRING)
private MyEnum myEnum;
```
I will update the OP

**Comment by vladmihalcea** [comment]
You need to send a replicating test case to prove the problem. This is a mandatory step in order to fix any issue.

**Comment by SayakMukhopadhyay** [comment]
The issue can be easily replicated by overriding the `toString()` method of an enum member. This causes whatever is returned in the `toString()` to be saved in the db. This has an additional effect of not being able to query the record anymore since the string returned via `toString()` cannot be resolved by `Enum.valueOf()`. If you still need a reproduction, a template project would help.

**Comment by vladmihalcea** [comment]
Send me a Pull Request with a replicating test case and a fix as well. I'll review it when it's ready.

**Comment by vladmihalcea** [comment]
Fixed.
