### ISSUE TITLE
Add support for mapping java.util.Date ARRAY or List to PostgreSQL DATE[] and TIMESTAMP[]

### ISSUE THREAD

**Issue by Ethoytaryn** [vladmihalcea/hibernate-types#150]
I had to implement this on my actual project. Maybe this can be interested to share my work with community.
I can create a pull request and my implementation and had unit tests.

**Comment by vladmihalcea** [comment]
Do you want to add support for mapping a PostgreSQL `DATE[]` to a `java.util.Date` array or Collection?

**Comment by Ethoytaryn** [comment]
Sorry i didnt specify. Yes, Postgres `DATE[]` to a `java.util.Date` array

**Comment by vladmihalcea** [comment]
Sounds great. Please send the PR.

**Comment by vladmihalcea** [comment]
Fixed.
