### ISSUE TITLE
PGSQL Enum Type not working with native queries

### ISSUE THREAD

**Issue by cec** [vladmihalcea/hibernate-types#152]
Hi,

in PostgreSQL I have a table `registrations` with a `status` enum column of type `enum_status_completed_cancelled_pending`.

I mapped the table to a `Registration` entity that uses `PostgreSQLEnumType` to map `RegistrationStatus` Java string enum to the pgsql enum.

A `TypedQuery` selecting all records with a given status (set via `setParameter("status", RegistrationStatus.PENDING)`) works perfectly.

Now, I need to join with tables of non-associated entities.
Since I can't upgrade this project to Hibernate >= 5.1 I'm trying to use native queries as you suggest on your venerable blog.

**Problem**
Using native queries, even something as simple as this
````java
Query q = em.createNativeQuery("select * from {h-schema}registrations where status = :status", Registration.class);
q.setParameter("status", RegistrationStatus.PENDING);
q.getResultList();
````

Results in 
````
org.postgresql.util.PSQLException: ERROR: operator does not exist: edu_booking.enum_status_completed_cancelled_pending = bytea
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
````

It seems that when using native queries, `PostgreSQLEnumType` is not able to cast the Java enum to `enum_status_completed_cancelled_pending`.

I'm new to Hibernate so I do not know if this is not expected to work, or if an actual fix to this amazing library is required.

Thanks :)

**Comment by vladmihalcea** [comment]
You can do provide the custom Type to Hibernate.

### Hibernate 5.2 and newer

```
List<Registration> registrations =  em.createNativeQuery("select * from {h-schema}registrations where status = :status", Registration.class)
.unwrap(NativeQuery.class)
.setParameter("status", RegistrationStatus.PENDING, PostgreSQLEnumType.INSTANCE);
.getResultList();
```

### Hibernate 5.1 or older

```
List<Registration> registrations =  em.createNativeQuery("select * from {h-schema}registrations where status = :status", Registration.class)
.unwrap(SQLQuery.class)
.setParameter("status", RegistrationStatus.PENDING, PostgreSQLEnumType.INSTANCE);
.getResultList();
```

For more details, check out [this article](https://vladmihalcea.com/sql-server-json-hibernate/).

**Comment by cec** [comment]
Hi @vladmihalcea ,

I tried the **Hibernate5.1 or older** solution, but compiler complained that it cannot resolve a method `setParameter` with those 3 arguments, as the third argument is meant to be a `org.hibernate.Type`.

I tried casting as follows

````
SQLQuery unwrappedQuery = query.unwrap(SQLQuery.class);
unwrappedQuery.setParameter("status", RegistrationStatus.PENDING, (Type) PostgreSQLEnumType.INSTANCE)
````

but it results in the following exception

````
java.lang.ClassCastException: com.vladmihalcea.hibernate.type.basic.PostgreSQLEnumType cannot be cast to org.hibernate.type.Type
````

I'm not sure how to proceed forward

I'm using `hibernate-types:2.7.1`

**Comment by vladmihalcea** [comment]
@cec That's because the Hibernate `EnumType` extends `EnhancedUserType`. I created [a new issue](https://github.com/vladmihalcea/hibernate-types/issues/153) that should address this problem for both `PostgreSQLEnumType` and the Hibernate `EnumType`. 

However, I don't have the time to work on this project at the moment. Maybe I'll find more time in 2020.

**Comment by cec** [comment]
Hi @vladmihalcea , sorry for the late reply.

Thanks for the explanation. I will resort to explicit casting for the moment.

I'd be happy to contribute to the library, but I believe the necessary change is not small and I'm still to green on Hibernate

**Comment by vladmihalcea** [comment]
Replaced by #153

**Comment by fredclose** [comment]
@cec can you show what's your workaround for this issue ?  
what do you mean with ' I will resort to explicit casting for the moment.'

**Comment by imaxkhan** [comment]
hi every body
i have hibernate-types-55
when trying to map HStore Data type on my entity i face error like this
 class org.postgresql.util.PGobject cannot be cast to class java.util.Map (org.postgresql.util.PGobject is in unnamed module of loader 'app'; java.util.Map is in module java.base of loader 'bootstrap')

@Entity
@Table(name = "COUNTRY_NAME")
@Getter
@Setter
@NoArgsConstructor
@TypeDef(name = "hstore", typeClass = PostgreSQLHStoreType.class)
public class CountryNameEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "Country_Name_Sequence")
    @SequenceGenerator(name = "Country_Name_Sequence", sequenceName = "COUNTRY_NAME_SEQ", allocationSize = 50)
    @Column(name = "ID_PK")
    private int id;
    @Column(name = "COUNTRY_CODE", length = 2, unique = true)
    private String countryCode;
    @Column(name = "NAME", columnDefinition = "public.hstore")
    @Type(type = "hstore")
    private Map<String, String> name;
    @Column(name = "COUNTRY_DEFAULT_LANGUAGE_CODE", length = 2)
    private String countryDefaultLanguageCode;
    @Column(name = "PARTITION")
    private Integer partition;
}
