### ISSUE TITLE
Doesn't work with spring.jpa.hibernate.ddl-auto

### ISSUE THREAD

**Issue by javaisgood** [vladmihalcea/hibernate-types#156]
When I use spring.jpa.hibernate.ddl-auto with this project. 
This exception will be thrown:
org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111

**Comment by vladmihalcea** [comment]
All tests in this project use hbm2ddl, and everything works just fine.

That exception can be fixed as I explained [in this article](https://vladmihalcea.com/hibernate-no-dialect-mapping-for-jdbc-type/).
