### ISSUE TITLE
Add a type mapping for Oracle BINARY_DOUBLE and BINARY_FLOAT

### ISSUE THREAD

**Issue by lukaseder** [vladmihalcea/hibernate-types#160]
For performance reasons, a customer would like to use `BINARY_DOUBLE` as a type mapping. This can be drastically faster than using `NUMBER` or `DOUBLE PRECISION`, see
https://blog.jooq.org/2019/09/11/oracles-binary_double-can-be-much-faster-than-number/

Is that something worth adding to hibernate-types?

**Comment by vladmihalcea** [comment]
Sounds like a good idea. It should not be difficult to add.

**Comment by vladmihalcea** [comment]
[This commit](https://github.com/vladmihalcea/hibernate-types/commit/0c9ac781e3ec1079237ddbf5be67eb791df22b3c) adds several test cases demonstrating that `BINARY_DOUBLE` and `BINARY_FLOAT` are already supported by Hibernate, so no custom Type needs to be added.

**Comment by p3consulting** [comment]
The query generated doesn't have the 'd' at the end of the value when handling BINARY_DOUBLE which limits the range of usable values to the ones of ... BINARY_FLOAT, outside you get an ORA-01426.
Example: 1.79769313486231E125 will work but 1.79769313486231E126 fails.

**Comment by vladmihalcea** [comment]
If you  can provide a test case and a fix for that, I'll review it.

**Comment by p3consulting** [comment]
Just add one in your existing tests with values like 1.79769313486231E126…

**Comment by vladmihalcea** [comment]
Looking forward to your Pull Request with the fix.
