### ISSUE TITLE
Add support for VARCHAR when mapping ARRAY to String[]

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#17]
As explained in [this article](https://vladmihalcea.com/hibernate-hsqldb-array-type/).

**Comment by OrangeDog** [comment]
It `StringArrayType` appears to work already for reading an entity, but not e.g. for query parameters.

**Comment by vladmihalcea** [comment]
Is your comment really related to this issue? It looks more like it's related to the existing StringArrayType  in which case, you need to provide a replicating test case and open a new issue.

**Comment by OrangeDog** [comment]
I mean it works for `varchar[]` fields.

**Comment by OrangeDog** [comment]
However, the constructor `StringArrayType(TypeDescriptor)` doesn't exist, so you cannot extend it directly as in the article you linked.

**Comment by vladmihalcea** [comment]
I now there is support for `String[]`, but I don't recall exactly why I created this issue.

Anyway, if there's something to be implemented, then you need to send me a Pull Request with a fix. I'll review it when it's ready.

**Comment by OrangeDog** [comment]
I'm not familiar with all the nuances, but this does the job for me. Using the `StringArrayType` results in various `function X(character varying[], text[]) does not exist`-like errors.

```java
public class VarcharArrayType extends AbstractHibernateType<String[]> {
    public static VarcharArrayType INSTANCE = new VarcharArrayType();

    public VarcharArrayType() {
        super(ArraySqlTypeDescriptor.INSTANCE, new TypeDescriptor());
    }

    public String getName() {
        return "varchar-array";
    }

    public static class TypeDescriptor extends StringArrayTypeDescriptor {
        @Override
        protected String getSqlArrayType() {
            return "varchar";
        }
    }
}
```

**Comment by ShuzzDE** [comment]
@OrangeDog 's solution works perfectly for me! Thank you so much for this! :-)
Any chance to include that in the official sources? There's some other "solutions" on the web, but those are years old by now and no longer work.

**Comment by vladmihalcea** [comment]
@ShuzzDE You can provide a Pull Request for it, and I'll review it when I have some time

**Comment by vladmihalcea** [comment]
Already supported and proved by the [`HSQLDBArrayTypeTest`](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-55/src/test/java/com/vladmihalcea/hibernate/type/array/HSQLDBArrayTypeTest.java).
