### ISSUE TITLE
ListArrayType should match the initial type when populating the List with the array from the DB

### ISSUE THREAD

**Issue by marceloverdijk** [vladmihalcea/hibernate-types#170]
When having a entity like:

```
@Entity
@TypeDefs({
        @TypeDef(name = "list-array", typeClass = ListArrayType.class)
})
public class Circuit {

    @Column(name = "previous_names")
    @Type(type = "list-array")
    private List<String> previousNames = new ArrayList<>();

    ..
```

Could the `ListArrayType` add the names to the initiated list instead of replacing the list?

I'm wondering as when the array is null in the database the `previousNames` list will be null in the fetched entity. I'm having 2 feelings here as it makes sense if it's null in the database.

But I expected differently.

Similar as 

```
    @OneToMany(mappedBy = "project")
    private List<Task> tasks = new ArrayList<>();
```
 
will also give an empty list, even if no tasks would be found in the databse.

Maybe 

```
    @Type(type = "list-array")
    private List<String> previousNames = new ArrayList<>();
```

could return an empty list.

and

```
    @Type(type = "list-array")
    private List<String> previousNames;
```

could return null.

What do you think?

**Comment by vladmihalcea** [comment]
Yes, that can also be an option. It can also be made configurable and passed via a Type parameter.

**Comment by vladmihalcea** [comment]
This [test case](https://github.com/vladmihalcea/hibernate-types/commit/1aea30af27d1699b6e525936bd163aedf7d78398) demonstrates that this behavior is already in place.

**Comment by marceloverdijk** [comment]
In my project it is not working, but there is a difference..

In my database the actual values are `null`.

Looking at the test:

```
    @Test
    public void testEmptyArrays() {

        doInJPA(entityManager -> {
            Event nullEvent = new Event();
            nullEvent.setId(0L);
            entityManager.persist(nullEvent);

            Event event = new Event();
            event.setId(1L);
            entityManager.persist(event);
        });

        doInJPA(entityManager -> {
            Event event = entityManager.find(Event.class, 1L);

            assertArrayEquals(new UUID[]{}, event.getSensorIds().toArray());
            assertArrayEquals(new String[]{}, event.getSensorNames().toArray());
            assertArrayEquals(new Integer[]{}, event.getSensorValues().toArray());
            assertArrayEquals(new Long[]{}, event.getSensorLongValues().toArray());
            assertArrayEquals(new SensorState[]{}, event.getSensorStates().toArray());
            assertArrayEquals(new Date[]{}, event.getDateValues().toArray());
            assertArrayEquals(new Date[]{}, event.getTimestampValues().toArray());
        });
    }
```

It creates an `Event` with all the list types initialised with `new ArrayList()`. 
I think when persisting this, it is actually persisted as `[]`, and not `null`.
Then when querying the `[]` is converted to an empty `ArrayList`.

I tweaked the test a bit to:

```
            Event event = new Event();
            event.setId(1L);
            event.setSensorNames(null); // SET IT EXPLICITLY TO NULL
            entityManager.persist(event);
```

then the test fails as we get a NPE on `event.getSensorNames().toArray()`.

It could be argued that this is expected behaviour.
But the problem is not only Hibernate is writing to the database..

And it is different from something like `@OneToMany(mappedBy = "project") List<Task> tasks = new ArrayList<>();` which will also never be `null`. I would expect the same for the `ListArrayType`.

**Comment by vladmihalcea** [comment]
Send me a Pull Request with the replicating test case, and I'll investigate it when I have some time.

**Comment by marceloverdijk** [comment]
Created https://github.com/vladmihalcea/hibernate-types/pull/171 with the failing test.

**Comment by vladmihalcea** [comment]
Unlike `@OneToMany` associations, the `ListArrayType` manages a `@Basic` property. So, if you set it to `null`, it must set the column value to `NULL`.

However, you can easily prevent the NPE by changing the getter and setter to:

```
public List<String> getSensorNames() {
    if(sensorNames == null) {
        sensorNames = new ArrayList<>();
    }
    return sensorNames;
}

public void setSensorNames(List<String> sensorNames) {
    if(sensorNames == null) {
        sensorNames.clear();
    }
    this.sensorNames = sensorNames;
}
```

**Comment by marceloverdijk** [comment]
OK, I wasn't aware of the `@Basic` property rules, but it makes sense.
I indeed added a getter like that already. Thx again.

**Comment by vladmihalcea** [comment]
You're welcome. I think the current behavior follows the "principle_of_least_astonishment", so it's better to leave it as-is.
