### ISSUE TITLE
GraalVM / Quarkus native build support

### ISSUE THREAD

**Issue by andreas-eberle** [vladmihalcea/hibernate-types#173]
It would be great if this library could add support for GraalVM / Quarkus native builds. Currently, adding this library to a quarkus project breaks the native build.

As far as I know, the main problem probably are the reflection calls. These will need a configuration for GraalVM so it knows how to handle them in native code. See [https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md).

This feature would be very nice to be able to continue using this library with Quarkus projects. Unfortunately, I'm not deep enough in this to provide a PR.

**Comment by vladmihalcea** [comment]
Indeed, this will be a nice feature. However, I have never used Quarkus or GraalVM, so I have no idea what's needed to be done for this issue.

Maybe the Quarkus development team should provide this change as they better know what's needed in order to support a given framework.

For the moment, this is the first time someone demanded this feature, so, at the moment, I think there is little demand for this.

**Comment by marceloverdijk** [comment]
Actually I'm also experimenting with Quarkus, not yet using the native build but will one day.
And I'm also using `hibernate-types`, so somewhere down the road this will bite me as well :-)

@gsmet @emmanuelbernard @FroMage could you maybe provide pointers to make `hibernate-types`  native compatible?

**Comment by vladmihalcea** [comment]
The #177 PR needs to be reviewed for this issue.

**Comment by marceloverdijk** [comment]
Note #177 is even needed to make Quarkus work in JVM mode. 
`Class.forName(className)` does not work in Quarkus JVM mode as it uses a 2 layer class loading structure, to allow the application classes to be dropped on hot reload. See [this](https://github.com/quarkusio/quarkus/issues/6625) issue for more info.

What is needed to run GraalVM/native I honestly don't know.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks
