### ISSUE TITLE
Unexpected Hibernate dirty checking when using Sets

### ISSUE THREAD

**Issue by Himly1** [vladmihalcea/hibernate-types#175]
Here is my entity
```
@Data
@EntityListeners(AuditingEntityListener.class)
public class ExpertApplicationRecord extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

   
    @Type(type = "json")
    @Column(columnDefinition = "json", nullable = false)
    private Map<String, Object> applicationInfo;

   
    @Type(type = "json")
    @Column(columnDefinition = "json", nullable = false)
    private Form metaDataOfTheApplicationInfo;
}
```

Here is the struct of the `Form` class
```
@Data
public class Form implements Serializable {
    private static final Long UID = 1L;

    private Set<FormField> formFields;

    public static Form getInstance(Set<FormField> formFields) {
        Form form = new Form();
        form.setFormFields(formFields);
        return form;
    }
}
```

Here is the the class name of the descriptor
`com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor`

Here is the `areEqual` method
```
@Override
    public boolean areEqual(Object one, Object another) {
        if (one == another) {
            return true;
        }
        if (one == null || another == null) {
            return false;
        }
        if (one instanceof String && another instanceof String) {
            return one.equals(another);
        }
        return objectMapperWrapper.toJsonNode(objectMapperWrapper.toString(one)).equals(
                objectMapperWrapper.toJsonNode(objectMapperWrapper.toString(another)));
    }
```
The `one` does equal to the `another`
The elements of the `formFields` of the `one` are : 3 2 1
The elements of the  `formFields` of the `another` are: 1 2 3 

When convert the `one` and the `another` to  the  JsonNode and compare the two the result  will not be equal.

**Comment by Himly1** [comment]
And then Hibernate will mark the object as dirty and run a update sql .

**Comment by vladmihalcea** [comment]
You need to provide a replicating test case. I'll check it out afterwards.

**Comment by Himly1** [comment]
@vladmihalcea  I was add the test case to my forked repository  
Can you please take a look ? Thanks you.

You can clone the below repository
`git@github.com:Himly1/hibernate-types.git
`
And you can find the test case at the below path
`com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptorTest`

**Comment by vladmihalcea** [comment]
If you already have a fork, you can easily send a Pull Request.

**Comment by vladmihalcea** [comment]
Fixed.
