### ISSUE TITLE
How to use the PostgreSQLEnumType with both PostgreSQL and H2?

### ISSUE THREAD

**Issue by rorytorneymf** [vladmihalcea/hibernate-types#179]
Is there any way to allow `PostgreSQLEnumType `to work with a h2 database as well?

I use h2 in testing, where the regular `@Enumerated(EnumType.STRING)` works fine, however, it doesn't work for the postgres database I use in production.

Your `PostgreSQLEnumType `works great for postgres, but doesn't work for h2.

Is there anything you suggest for this use case?

Many thanks!

**Comment by vladmihalcea** [comment]
You will need to investigate what H2 needs in order to bind the Enum to the `PreparedStatement` and how to fetch it from the `ResultSet`. For that, you will need to:

- add a H2 test case that uses a DB-specific Enum 
- create a new `H2EnumType` according to how H2 needs to get/set the Enum

**Comment by rorytorneymf** [comment]
For anyone else, the 3 steps described [in this stackoverflow answer](https://stackoverflow.com/a/43125099/12177456) works with both h2 and postgres:

1. Create enum in sql
2. Add @Enumerated(EnumType.STRING) on entity
3. Appending ?stringtype=unspecified to postgres connection string

**Comment by vladmihalcea** [comment]
I'm sure there's a way to make it work even without those parameters.

**Comment by Cytriox** [comment]
Hi,

You could extend PostgreSQLEnumType to use your own class (for example MyPostgreSQLEnumType.class) and override the nullSafeSet method with Types.VARCHAR for your unit tests : 

```java
    @Override
    public void nullSafeSet(final PreparedStatement st, final Object value, final int index,
            final SharedSessionContractImplementor session)
            throws HibernateException, SQLException {
        st.setObject(index, value != null ? ((Enum<?>) value).name() : null, Types.VARCHAR);
    }
```

For your production code, this class is empty : 
```java
public class MyPostgreSQLEnumType extends PostgreSQLEnumType {
}
```

**Comment by Cytriox** [comment]
Better with : 
```java
public class MyPostgreSQLEnumType extends PostgreSQLEnumType {

    private static final String H2_DIALECT = "org.hibernate.dialect.H2Dialect";

    @Override
    public void nullSafeSet(final PreparedStatement st, final Object value, final int index,
            final SharedSessionContractImplementor session) throws SQLException {

        // H2 database compatibility
        if (H2_DIALECT.equals(session.getFactory().getJdbcServices().getDialect().toString())) {
            st.setObject(index, value != null ? ((Enum<?>) value).name() : null, Types.VARCHAR);
        } else {
            super.nullSafeSet(st, value, index, session);
        }
    }

}
```
Have fun

**Comment by vladmihalcea** [comment]
Thanks for the workaround

**Comment by rafis** [comment]
That doesn't solve Hibernate schema validation issues.

PostgreSQL required columnDefinition to be default.
```
    @Enumerated(EnumType.STRING)
    @Column(name = "direction", nullable = false)
    @Type(type = "pgsql_enum")
    private Direction direction;
```

H2 requires columnDefinition to be "enum".
```
    @Enumerated(EnumType.STRING)
    @Column(name = "direction", columnDefinition = "enum", nullable = false)
    @Type(type = "pgsql_enum")
    private Direction direction;
```

**Comment by vladmihalcea** [comment]
Schema validation happens in Hibernate ORM. More, if you use it, you are doing it all wrong as you should have used something like [Flyway](https://vladmihalcea.com/flyway-database-schema-migrations/) instead.
