### ISSUE TITLE
Setting JsonInclude behavior via spring boot properties

### ISSUE THREAD

**Issue by Tajveer** [vladmihalcea/hibernate-types#181]
Hi,

Trying to persist a JSON in MySQL 8.0 using `JsonStringType.class`. Simplified example:

```
public class MyEntity {
    @Type(type = "json")
    @Column(name = "custom_obj", columnDefinition = "JSON")
    private CustomObj customObj;
}

class CustomObj {
     private String str1;
     private String str2;
}
```

I've set `spring.jackson.default-property-inclusion=non_null` in `application.properties`, and `hibernate.types.jackson.object.mapper=com.fasterxml.jackson.databind.ObjectMapper` in `hibernate-types.properties`. The `ObjectMapper` instance in my project is being injected by `JacksonAutoConfiguration`. 

With the above configuration, null values are still being serialized in the JSON. Eg. `{"str1": "value1", "str2": null}`. However, on using the annotation `@JsonInclude(JsonInclude.Include.NON_NULL)` on `CustomObj`, null values are excluded and result is `{"str1": "value1"}`.

Am I missing something or is there a need to use the annotation explicitly on every class to avoid serializing nulls?

Thanks in advance.

**Comment by vladmihalcea** [comment]
[This article](https://vladmihalcea.com/hibernate-types-customize-jackson-objectmapper/) explains how to customize the Jackson ObjectMapper.

Integrating that with Spring requires consulting, so, if your company is interested in employing [my consulting services](https://vladmihalcea.com/consulting/) to help you with this issue, just let me know.
