### ISSUE TITLE
HHH015011: Unable to locate static metamodel field

### ISSUE THREAD

**Issue by srnm** [vladmihalcea/hibernate-types#184]
I am seeing warnings during startup:
`WARN o.h.metamodel.internal.MetadataContext   : HHH015011: Unable to locate static metamodel field : xyz.UserView_#data; this may or may not indicate a problem with the static metamodel`

using **JsonBinaryType** as per https://vladmihalcea.com/how-to-store-schema-less-eav-entity-attribute-value-data-using-json-and-hibernate/

A static metamodel is being created during maven build via hibernate-jpamodelgen.

I am unsure of the difference between JsonBinaryType and JsonNodeBinaryType.
Previously I was using JsonNodeBinaryType and I don't recall seeing this warning.

Should I revert to JsonNodeBinaryType or is there a way to resolve the warning and continue using JsonBinaryType?

thank you

**Comment by vladmihalcea** [comment]
The Metamodel is generated by Hibernate ORM, and the Hibernate Types have no way to control that.

So, you need to open an issue in the Hibernate ORM project about that warning.

The `JsonBinaryType` can be used instead of the `JsonNodeBinaryType`.
