### ISSUE TITLE
Specify String encoding in JsonBlobType

### ISSUE THREAD

**Issue by linarkou** [vladmihalcea/hibernate-types#185]
Hi! Thank you for hibernate-types!
I want to save some object in blob column as json, and I use JsonBlobType. Can I set a specific charset for converting String to byte array?
Now I see that `JsonTypeDescriptor::wrap`  just uses `String::getBytes` with default charset. 

https://github.com/vladmihalcea/hibernate-types/blob/b3189cc10d13f7761121db867152b840e1203433/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/json/internal/JsonTypeDescriptor.java#L120

**Comment by vladmihalcea** [comment]
Thanks, indeed, a useful requirement. One option is to set the `file.encoding` JVM property.

What I need is a test case showing how this issue is replicating so that I could analyze whether a global property is needed or a Type-specific setting.

**Comment by vladmihalcea** [comment]
Closed as no test case was provided.
