### ISSUE TITLE
Need help to store arbitary json( any child depth) to postgres jsonb column with spring boot

### ISSUE THREAD

**Issue by sumanadak** [vladmihalcea/hibernate-types#186]
Hi,
I need to store an arbitary json( any child depth) to a postgres column. I dont need any search on stored json.  So I tried to declare a column as String but there is a error. Could someone please help me to store json vale and retrive same?

Thanks
Suman

**Comment by vladmihalcea** [comment]
Check out the `PostgreSQLJsonStringPropertyTest` in the GitHub repository. It will show you how to map a JSONB column as a `String` entity attribute.
