### ISSUE TITLE
Add support for checking if the bounds are open or closed for a given Range

### ISSUE THREAD

**Issue by frode-carlsen** [vladmihalcea/hibernate-types#204]
the Range#hasMask method is private, which makes it not possible for clients of class to test whether a range includes/excludes its bounds.

Suggest making hasMask public and /or add convenience methods
* isLowerClosed/isLowerOpen
* isUpperClosed/isUpperOpen
* isClosed
* isOpen

**Comment by vladmihalcea** [comment]
Send me a Pull Request with your fix proposal. Thanks.

**Comment by vladmihalcea** [comment]
Fixed.
