### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by ArkadyKarev** [vladmihalcea/hibernate-types#207]
I've tried to clone the project to play around with tsranges. Looks like tsrange in PostgreSQL sometimes can contain milliseconds, so in that case pattern `LOCAL_DATE_TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss[.SSSSSS]")` wouldn't work with the following exception
> java.time.format.DateTimeParseException: Text '2020-03-23 10:00:43.925' could not be parsed at index 10

I'm not sure yet how to handle this correctly, but after I had cloned the project and run docker environment, I'm getting following error on `mvn test`:

> [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.085 s - in com.vladmihalcea.hibernate.type.range.PostgreSQLRangeTypeTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   MySQLYearMonthDateTest.test:52->AbstractTest.doInJPA:451->lambda$test$1:58 expected:<2016-10> but was:<2016-09>
[ERROR]   PostgreSQLJsonBinaryTypeNestedCollectionNoEqualsTest>AbstractTest.init:78->afterInit:53 expected:<1> but was:<2>
[ERROR] Errors:
[ERROR]   ArrayTypeTest.test:81->AbstractTest.doInJPA:453 » Rollback Error while committ...
[ERROR]   EhcacheListArrayTypeTest.test:81->AbstractTest.doInJPA:453 » Rollback Error wh...
[ERROR]   EhcacheListArrayTypeTest.testMixingNullValues:133->AbstractTest.doInJPA:453 » Rollback
[ERROR]   ListArrayTypeTest.test:70->AbstractTest.doInJPA:453 » Rollback Error while com...
[ERROR]   ListArrayTypeTest.testMixingNullValues:202->AbstractTest.doInJPA:453 » Rollback
[ERROR]   MultiDimensionalIntegerArrayTypeTest.test:80->AbstractTest.doInJPA:451->lambda$test$2:89 NoSuchMethod
[ERROR]   MultiDimensionalStringArrayTypeTest.test:87->AbstractTest.doInJPA:451->lambda$test$2:96 NoSuchMethod
[ERROR] com.vladmihalcea.hibernate.type.interval.OracleIntervalDayToSecondTypeTest.test(com.vladmihalcea.hibernate.type.interval.OracleIntervalDayToSecondTypeTest)
[ERROR]   Run 1: OracleIntervalDayToSecondTypeTest>AbstractTest.init:76->AbstractTest.newEntityManagerFactory:273 » Persistence
[ERROR]   Run 2: OracleIntervalDayToSecondTypeTest>AbstractTest.destroy:90 » NullPointer
[INFO]
[ERROR] com.vladmihalcea.hibernate.type.json.OracleJsonBinaryTypeTest.test(com.vladmihalcea.hibernate.type.json.OracleJsonBinaryTypeTest)
[ERROR]   Run 1: OracleJsonBinaryTypeTest>AbstractTest.init:76->AbstractTest.newEntityManagerFactory:273 » Persistence
[ERROR]   Run 2: OracleJsonBinaryTypeTest>AbstractTest.destroy:90 » NullPointer
[INFO]
[ERROR] com.vladmihalcea.hibernate.type.json.OracleJsonBinaryTypeTest.testLoad(com.vladmihalcea.hibernate.type.json.OracleJsonBinaryTypeTest)
[ERROR]   Run 1: OracleJsonBinaryTypeTest>AbstractTest.init:76->AbstractTest.newEntityManagerFactory:273 » Persistence
[ERROR]   Run 2: OracleJsonBinaryTypeTest>AbstractTest.destroy:90 » NullPointer
[INFO]
[ERROR] com.vladmihalcea.hibernate.type.json.OracleJsonStringPropertyTest.test(com.vladmihalcea.hibernate.type.json.OracleJsonStringPropertyTest)
[ERROR]   Run 1: OracleJsonStringPropertyTest>AbstractTest.init:76->AbstractTest.newEntityManagerFactory:273 » Persistence
[ERROR]   Run 2: OracleJsonStringPropertyTest>AbstractTest.destroy:90 » NullPointer
[INFO]
[ERROR] com.vladmihalcea.hibernate.type.json.OracleJsonStringPropertyTest.testLoad(com.vladmihalcea.hibernate.type.json.OracleJsonStringPropertyTest)
[ERROR]   Run 1: OracleJsonStringPropertyTest>AbstractTest.init:76->AbstractTest.newEntityManagerFactory:273 » Persistence
[ERROR]   Run 2: OracleJsonStringPropertyTest>AbstractTest.destroy:90 » NullPointer
[INFO]
[ERROR] com.vladmihalcea.hibernate.type.json.SQLServerJsonStringPropertyTest.test(com.vladmihalcea.hibernate.type.json.SQLServerJsonStringPropertyTest)
[ERROR]   Run 1: SQLServerJsonStringPropertyTest>AbstractTest.init:76->AbstractTest.newEntityManagerFactory:273 » Persistence
[ERROR]   Run 2: SQLServerJsonStringPropertyTest>AbstractTest.destroy:90 » NullPointer
[INFO]
[ERROR] com.vladmihalcea.hibernate.type.json.SQLServerJsonStringPropertyTest.testLoad(com.vladmihalcea.hibernate.type.json.SQLServerJsonStringPropertyTest)
[ERROR]   Run 1: SQLServerJsonStringPropertyTest>AbstractTest.init:76->AbstractTest.newEntityManagerFactory:273 » Persistence
[ERROR]   Run 2: SQLServerJsonStringPropertyTest>AbstractTest.destroy:90 » NullPointer
[INFO]
[INFO]
[ERROR] Tests run: 110, Failures: 2, Errors: 14, Skipped: 2

My environment is 
OS X 10.15.3
java version "1.8.0_202"

**Comment by vladmihalcea** [comment]
I never use that Docker image to run tests, and it would not work for you either, as that's only for PostgreSQL, while the tests that are failing are supposed to run on Oracle, SQL Server or MySQL.

I have all those already installed in my machine since I'm using them on a daily basis, so I don't need a Docker image for that anyway.

If you want to add a feature, you can add a new test case for it and run that only to see if it works. I'll run the suite anyway when I integrate a new feature.

In your case, try to add a replicating test case for that issue. You can also customize the DB credentials in the `DataSourceProvider` classes if you have the DBs already installed on your machine.
