### ISSUE TITLE
ignore property

### ISSUE THREAD

**Issue by fabioebner** [vladmihalcea/hibernate-types#208]
It's possible to ignore one property?

tks

**Comment by vladmihalcea** [comment]
I have no idea what you are talking about.

**Comment by fabioebner** [comment]
just like u have the @transient in a Entity File,  there is some annotations to when I don't wanna serialize one property when save ?

tks

**Comment by vladmihalcea** [comment]
This library uses Jackson, so maybe Jackson [`FilterProvider`](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html#setFilterProvider(com.fasterxml.jackson.databind.ser.FilterProvider)) can help you. 

You can provide a custom `ObjectMapper` as explained in [this article](https://vladmihalcea.com/hibernate-types-customize-jackson-objectmapper/), so you will have to create a custom `ObjectMapper` instance that takes a given `FilterProvider` which ignores that field.

Another option is to use a `String` entity attribute and make sure you remove that property prior to getting the `String` value of the JSON object you want to save.
