### ISSUE TITLE
Provide a way to customize the deep copy mechanism

### ISSUE THREAD

**Issue by iLavryk** [vladmihalcea/hibernate-types#21]
There is a method
static T clone(T value)
in class JacksonUtil
which try to determine what type of deep copy use and in case if input Object implements Serializable interface it try to use java Serialization mechanism to copy object. But what if i use ArrayList to store it to DB and MyObject is not implements it. Why just for all cases not use json serialization?
Can you do it preferable may be. Because it always fails with exception and force me to mark my Object as Serializable. But it is not what i want

**Comment by vladmihalcea** [comment]
That feature was added to support [this issue](https://github.com/vladmihalcea/hibernate-types/issues/8).  

I'm thinking of adding some Configuration object so that we can customize various aspects, like this one here.

**Comment by rhanton** [comment]
I'm having this issue too. It seems like a nuisance to figure out a way to do it, but it would be nice if the use of the SerializationHelper was configureable or if there was an easy way to override just the JacksonUtil without cloning the entire library.

**Comment by vladmihalcea** [comment]
This is fixed in version 2.2.0 as explained in [this article](https://vladmihalcea.com/how-to-customize-the-json-serializer-used-by-hibernate-types/).

You can now customize the `JsonSerializer` and provide your own logic for deep cloning.
