### ISSUE TITLE
Allow ArrayType to work on HSQLDB

### ISSUE THREAD

**Issue by mybyte** [vladmihalcea/hibernate-types#219]
Following the short tutorial on https://vladmihalcea.com/hibernate-hsqldb-array-type/, deserialization of String[] arrays fails.

ArrayUtil#unwrapArray can't work for array of Strings:

`if(arrayClass.isInstance(originalArray)) {
                return (T) originalArray;
            } else {
                throw new UnsupportedOperationException("Cannot transform array :" + Arrays.toString(originalArray) + " to type: " + arrayClass);
            }`

Check is failing because originalArray is object[], the arrayClass is string[].

Working with Hibernate-Types-52-2.9.8.

**Comment by vladmihalcea** [comment]
You need to create a replicating test case that proves the issue. Use one of the existing test cases and modify it to use HSQLDB instead of PostgreSQL.

**Comment by vladmihalcea** [comment]
Fixed.
