### ISSUE TITLE
SqlResultMapping with ConstructorResult mapping of jsonb column into Constructor is not working

### ISSUE THREAD

**Issue by mosesonline** [vladmihalcea/hibernate-types#226]
SqlResultMapping with ConstructorResult mapping of jsonb column into Constructor is not working.

Table:
```
SELECT * FROM data;
                  id                  |       sub_data
--------------------------------------+-----------------------
 366bee25-2f08-4fe7-a94e-84acfa550dd4 | {"name": "sfsdfsdfd"}
```

Annotation over an Entity:
```
@SqlResultSetMapping(
        name = "DataMapping",
        classes = {
                @ConstructorResult(
                        targetClass = Data.class,
                        columns = {
                                @ColumnResult(name = "sub_data", type = SubData.class),
                        }
                )
        }
)
```
Classes:
```
//Data.java
public class Data {
    private SubData data;

    public Data(SubData data) {
        this.data = data;
    }

    public SubData getData() {
        return data;
    }

    public void setData(SubData data) {
        this.data = data;
    }
}
//SubData.java
public class SubData {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```
not working:
```
entityManager
                .createNativeQuery(
                        "SELECT sub_data FROM data", "DataMapping")
                .getResultList();
```
working solution without SqlResultMapping but deprecated setResultTransformer:
```
entityManager
                .createNativeQuery(
                        "SELECT sub_data FROM data")
                .unwrap(org.hibernate.query.NativeQuery.class)
                .setResultTransformer(
                        (ListResultTransformer)
                                (tuple, aliases) -> objectMapper.convertValue(tuple[0], SubData.class)
                )
                .getResultList();
```
org.springframework.boot:spring-boot-starter-data-jpa:2.3.0.M4
com.vladmihalcea:hibernate-types-52:2.9.9

**Comment by vladmihalcea** [comment]
You didn't use the `type` attribute to pass the `JsonStringType` or `JsonBinaryType`. CHeck out [this article](https://vladmihalcea.com/jpa-sqlresultsetmapping/) for more info, and [this one](https://vladmihalcea.com/hibernate-no-dialect-mapping-for-jdbc-type/} as well.

**Comment by mosesonline** [comment]
I've set the following class as dialect:

```
public class PostgreSQL95JsonDialect extends PostgreSQL95Dialect {

    public PostgreSQL95JsonDialect() {
        super();
        this.registerHibernateType(
                Types.OTHER, JsonNodeBinaryType.class.getName()
        );
    }
}
```
And the entity is read correctly with JpaRepository implementation.
```
@Entity
@Table(name = "data")
@TypeDefs({
        @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class),
        @TypeDef(name = "json", typeClass = JsonStringType.class)
})
public class DataEntity {
    @Id
    private String id;

    @Type(type = "jsonb")
    @Column(name = "sub_data", columnDefinition = "jsonb")
    private SubDataEntity data;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SubDataEntity getData() {
        return data;
    }

    public void setData(SubDataEntity data) {
        this.data = data;
    }
}
```

**Comment by vladmihalcea** [comment]
That's not the best way to fix this issue. Any other DB-specific column will fail, like UUID.

Better handle the mapping at query level, not global level.

**Comment by mosesonline** [comment]
And it doesn't fix the issue :)

**Comment by vladmihalcea** [comment]
Of course, it does ;)

**Comment by mosesonline** [comment]
Thanks for the example. 

This is my example: [demo.zip](https://github.com/vladmihalcea/hibernate-types/files/4574831/demo.zip) . If you start the container like in the README.md you can run `./mvnw test` you can see two tests failing due to the missing mapping. You can also run the service and use the postman collection.

If you don't find my mistake I ask the hibernate community.

**Comment by vladmihalcea** [comment]
You're welcome.

**Comment by mosesonline** [comment]
I'm blind or something. I've tried to find the differences between your example and mine, so I added the metadata builder contributor. Now my request with ListResultTransformer delivers data but the result is not mapped when I use AliasToBeanResultTransformer (added endpoint & test for it).

The SqlResultSetMapping still doesn't work.

I don't know what to configure so that hibernate will map the json-data to objects.
[demo.zip](https://github.com/vladmihalcea/hibernate-types/files/4576178/demo.zip)

**Comment by vladmihalcea** [comment]
Just fork this repository and run the [`PostgreSQLJsonNodeTypeTest`](https://github.com/vladmihalcea/hibernate-types/blob/55973bb9f9f8910b93b1d390bc8240f8209e1e75/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/json/PostgreSQLJsonNodeTypeTest.java) to see a working example.
