### ISSUE TITLE
ObjectMapperJsonSerializer#clone throws NullPointerException if the Map key or value are null

### ISSUE THREAD

**Issue by iandrianto** [vladmihalcea/hibernate-types#227]
Hi, I got the following error
```
java.lang.NullPointerException: null
	at com.vladmihalcea.hibernate.type.util.ObjectMapperJsonSerializer.clone(ObjectMapperJsonSerializer.java:42)
```
When I checked it, most likely that was because the `value` is `null` but the code tries to get the class of `value` (`value.getClass()`)

**Comment by vladmihalcea** [comment]
You need to provide a replicating test case. Use any of the existing tests as a template for your test case.

**Comment by joshiste** [comment]
Is fixed by https://github.com/vladmihalcea/hibernate-types/pull/230 (also having testcases for this)

**Comment by vladmihalcea** [comment]
Fixed.
