### ISSUE TITLE
Add MySQL BinaryType

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#23]
https://discourse.hibernate.org/t/how-to-map-byte-to-jdbc-binary-type/222/2

**Comment by pavelgordon** [comment]
Hey @vladmihalcea, is this still up for grabs? If so, I would like to implement it. 
From what I understand, it's as simple as bringing 
```
public class MySQLBinaryType extends BinaryType {

    public MySQLBinaryType() {
        setSqlTypeDescriptor(BinaryTypeDescriptor.INSTANCE);
    }
}
```

to the codebase, and writing a test for it. Am I missing something?

**Comment by vladmihalcea** [comment]
If you have time to do it, I'll surely appreciate it. Looking forward to getting your PR.

**Comment by vladmihalcea** [comment]
PR integrated. Thanks for your contribution.
