### ISSUE TITLE
Custom deserializer for collection

### ISSUE THREAD

**Issue by Marek00Malik** [vladmihalcea/hibernate-types#24]
Hi, 
First, great job on this lib, congrats !

I have a quick question regarding deserialization. 
I have an Set of objects which contain more objects inside them (in a structure like this:
Set<A>, where A is an abstract class with 3 different implementations (A1, A2, A3). So in the end I have a set of A1's, that contain a set of A2's which in the end contain a set of A3's).
To correctly create a collection of those objects I would need to write a custom converter, with some business logic inside. 
Is it possible to override you default behaviour JsonTypeDescriptor ?

**Comment by vladmihalcea** [comment]
Thanks.

Related to your question, the current implementation can only create objects of a given type. Only some custom handle your use case.

**Comment by Marek00Malik** [comment]
By custom handler you mean the one "JsonStringType" ? 
If I would be able to run my one Json deserializer rather then trying to may on TypeReference I'm ok :) 
But I don't know how to force this custom handler.  Can you point me to any examples ?

**Comment by vladmihalcea** [comment]
Just fork the repository and try to implement your own logic. The code base is very simple and with one debug session, you are going to know how it works. There are lots of examples in unit tests which you can run as well, or try to add a new one for your use case.

**Comment by vladmihalcea** [comment]
Closing this issue for now since there was no example being given as a Pull Request.
