### ISSUE TITLE
Guava range mapping does not support infinite bounds

### ISSUE THREAD

**Issue by azell** [vladmihalcea/hibernate-types#244]
If I create a Guava Range instance like the following:

```
Range.atLeast(LocalDate.of(1934, Month.JUNE, 9))
```

then saving it will generate an exception.  The offending code is in
https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/range/guava/PostgreSQLGuavaRangeType.java#L364

According to https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/Range.html

the `lowerBoundType` and `upperBoundType` methods will throw an **IllegalStateException** if the corresponding `hasLowerBound` and `hasUpperBound` methods return **false**.

So if the intent is to support lower or higher infinite bounds, then the calls to `lowerBoundType` and `upperBoundType` should have guards.

**Comment by azell** [comment]
And I think there is a copy and paste error at https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/range/guava/PostgreSQLGuavaRangeType.java#L173

Should replace `upper` on lines 173 and 174 with `lower`.

**Comment by vladmihalcea** [comment]
Thanks for the analysis. Send me a Pull Request with a replicating test case and a fix to these issues, and I'll review it.

**Comment by azell** [comment]
@vladmihalcea https://github.com/vladmihalcea/hibernate-types/pull/245

**Comment by vladmihalcea** [comment]
Fixed.
