### ISSUE TITLE
Add jackson-module-jaxb-annotations dependency

### ISSUE THREAD

**Issue by gitterhh** [vladmihalcea/hibernate-types#247]
On mapping
```
@Type(type = "jsonb")
@Column(columnDefinition = "jsonb")
private Map<String, Object> properties;
```
I receive the error
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule not found
```
It is need to add the dependency
```
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.11.0</version>
</dependency>
```

**Comment by vladmihalcea** [comment]
This issue is probably related to [this StackOverflow question](https://stackoverflow.com/questions/59933277/provider-com-fasterxml-jackson-module-jaxb-jaxbannotationmodule-not-found-afte) and seems to affect Spring Boot 2.2 or newer versions.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by jmchuster** [comment]
We just upgraded our services from Spring boot 2.1.4 => 2.3.3, and it looks like the `jackson-datatype-joda` dependency is also required.

**Comment by vladmihalcea** [comment]
@jmchuster I don't think Hibernate Types needs that dependency. Run a dependency tree and see where it's needed.

**Comment by jmchuster** [comment]
Sorry, i think i got confused somewhere along the way.  It was only the `jackson-module-jaxb-annotations` that was missing, resolved by upgrading hibernate-types.  We were scrambling to fix a forced upgrade, and I must've missed a refresh somewhere trying to get it to a working state, and formed the wrong the dependency chain in my mind.

**Comment by vladmihalcea** [comment]
No problem. I'm glad you sorted it out.
