### ISSUE TITLE
Add a new Type to handle that JsonNode is not Serializable

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#25]
Mapping the JSON type to a String in Java and then just use a `@Transient` toJsonNode method would be a solution.

**Comment by guptavivek792** [comment]
Mapping the JSON type to a String in Java and then just use a @Transient toJsonNode method would be a solution.

**Comment by vladmihalcea** [comment]
This is already supported via the `JsonBinaryType` mapped to a `String` as explained in [this article](https://vladmihalcea.com/map-string-jpa-property-json-column-hibernate/).
