### ISSUE TITLE
Illegal reflective access by ReflectionUtils

### ISSUE THREAD

**Issue by plucdrol** [vladmihalcea/hibernate-types#259]
I have added hibernate-types-5 2.9.9 as a dependency in a SpringBoot application (using spring-data 3.2.5.RELEASE) in order to use Postgresql custom types.
When I start the application, I get these warnings:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.vladmihalcea.hibernate.type.util.ReflectionUtils (file:/home/pldrolet/.m2/repository/com/vladmihalcea/hibernate-types-5/2.9.9/hibernate-types-5-2.9.9.jar) to field java.lang.Class.name
WARNING: Please consider reporting this to the maintainers of com.vladmihalcea.hibernate.type.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Is there a way to remove these warnings only for ReflectionUtils? These logs cannot be controlled by log4j apparently.

**Comment by vladmihalcea** [comment]
There isn't much that can be done about it. You get this WARNING on Java 9 or higher JVM version because of the new Module system.

> These logs cannot be controlled by log4j apparently.

Yes, they cannot be controlled via Log4J since these are not application logs, but JVM warnings.

> Is there a way to remove these warnings only for ReflectionUtils?

Sure thing. You have to add the following argument when starting the JVM:

    --illegal-access=allow
