### ISSUE TITLE
Are PostgreSQL composites type supported?

### ISSUE THREAD

**Issue by baerwang** [vladmihalcea/hibernate-types#261]

**Comment by vladmihalcea** [comment]
There is no support for PostgreSQL composite types. I have never used this feature, so I don't know how it will work in JDBC. If you can build an example showing show this works in JDBC, I will have more info about what might be needed to add a custom type. However, even so, it might be that this is not easy to implement as a Hibernate Type.

**Comment by baerwang** [comment]
> 不支持PostgreSQL复合类型。我从未使用过此功能，所以我不知道它如何在JDBC中工作。如果您可以构建一个示例来说明在JDBC中可以正常工作，那么我将获得有关添加自定义类型所需内容的更多信息。但是，即使这样，也可能很难将其实现为Hibernate Type。

Thank you for your reply
