### ISSUE TITLE
Why update sql occurred when I used JsonBinaryType to query some results?

### ISSUE THREAD

**Issue by BlackRen09** [vladmihalcea/hibernate-types#264]
![image](https://user-images.githubusercontent.com/19494659/89883161-5d30af00-dbfa-11ea-9d4f-fdd845a918f4.png)
I used Spring Data JPA as ORM, a table contains a column which is defined as jsonb, when I execute a simple query sql, hibernate log show some update sql executing in the meantime

**Comment by vladmihalcea** [comment]
Most likely it's because you didn't add equals and hashCode on your POJOs that are saved as JSON. Check out [this issue](https://github.com/vladmihalcea/hibernate-types/issues/263) for more details.

**Comment by BlackRen09** [comment]
> Most likely it's because you didn't add equals and hashCode on your POJOs that are saved as JSON. Check out [this issue](https://github.com/vladmihalcea/hibernate-types/issues/263) for more details.

It works and thanks very much!

**Comment by vladmihalcea** [comment]
I'm glad I could help.

**Comment by jmchuster** [comment]
Is this something that changed in the last year, how the dirty checking works?  We did not see these types of updates when querying, until we recently upgraded:
spring boot `2.1.4` => `2.3.3`
hibernate-types-52 `2.3.0` => `2.9.13`

**Comment by vladmihalcea** [comment]
Check out the project release notes for more details. If you see redundant Updates, it's most likely because of the lack of equals/hashCode on the Pojos you map to Json.
