### ISSUE TITLE
Bad value for type long when using PostgreSQL database

### ISSUE THREAD

**Issue by clzola** [vladmihalcea/hibernate-types#265]
Hi, I am using your library but I have problems with extracting JSONBs from database. The error I am getting is 
```
Bad value for type long: (some json string)
```

I am using PostgreSQL 12.3 version.

I have been debuging my app and discovered that it is calling `org.hibernate.type.descriptor.sql.BlobTypeDescriptor::getExtractor()` method in which it returns implementation of `BasicExtractor` class.  Then it calls doExtract() method from BasicExtractor class in order to wrap blob from database:
```
return javaTypeDescriptor.wrap( rs.getBlob( name ), options );
```

however `rs.getBlob()` is trying to call `toLong(fixedString())` method. But I have no idea why would it call toLong when it is string.

Here are the classes:

```
@Data
@Entity
@Table(name = "merchant_stores")
@DiscriminatorValue("MERCHANT_STORE")
@EntityListeners(AuditingEntityListener.class)
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
@NamedEntityGraphs({
    //
})
public class MerchantStore {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ...

    @Type(type = "jsonb")
    @Column(name = "business_hours")
    private List<BusinessHours> businessHours;

    // ...
}

@Data
public class BusinessHours implements Serializable {
    @JsonInclude
    private String openTime;

    @JsonInclude
    private String closeTime;
}
```

**Comment by vladmihalcea** [comment]
In order to investigate it, you will need to provide a replicating test case. Use any of the existing test cases as the base for your test. I'll take a look at it once it's done.

**Comment by clzola** [comment]
I have created fresh new project, put your library in there, created table with jsonb in PostgreSQL database, and it works, but for some reason in my current project it does not. Further debuggings show that it thinkgs that it is JsonBlobType instead of JsonBinaryType... Somehow my spring boot project ignores @TypeDefs....

I don't know how would I create test case, when it just does not work for my project, while it works in fresh new....

**Comment by vladmihalcea** [comment]
Then, it's definitely not a problem with this library. It's either a Spring Boot or a Hibernate issue, so you need to open the issue for those projects.

**Comment by clzola** [comment]
I figured it out, for some reason I had this dependency in my `pom.xml` faile:

```
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
</dependency>
```

I can't remember why I put it there, but once I removed it (I also see that your library is also using this dependency) it started working...

**Comment by vladmihalcea** [comment]
I don't see why that dependency would cause that issue. Again, maybe it's a Hibernate issue.
