### ISSUE TITLE
Regarding issue #39 (String fields on entity as JSONB don't work correctly)

### ISSUE THREAD

**Issue by HittiGubbi** [vladmihalcea/hibernate-types#276]
I suspect the problem we are experiencing is closely related to issue #39.

Our Spring application uses jsonb columns in postgresql without problems under hibernate-types-52 version 2.2.2, but any version >= 2.2.3 goes berserk. When looking at the data with psql, the data stored with version 2.2.2 shows as:

` "[{\"item\":\"eedaa6\",\"type\":\"Valid\"},{\"item\":\"70254c\",\"type\":\"Valid\"},{\"item\":\"717ce9\",\"type\":\"Valid\"}]"`

If I try to store the very same data with e.g. 2.10.0, the result under psql shows as:

`"\"[{\\\"item\\\":\\\"eedaa6\\\",\\\"type\\\":\\\"Valid\\\"},{\\\"item\\\":\\\"70254c\\\",\\\"type\\\":\\\"Valid\\\"}][object Object]\""`

So something clearly goes very much wrong here... But I am not sure what, as the client code inserting the data seems standard. The postgresql jsonb column is defined in similar manner as suggested at https://vladmihalcea.com/map-string-jpa-property-json-column-hibernate/.

```
@TypeDefs(
{
  @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
})
...
@Type(type = "jsonb")
  @Column(columnDefinition = "jsonb")
  private String data;
```

The stored JSON-data is created by the frontend JavaScript by doing:
```
var postData = new FormData();
postData.set('data', JSON.stringify(data));
return AXIOS.post('/store-data', postData);
```
Here the variable "data" is a plain JavaScript-array containing plain JavaScript objects.

**Comment by vladmihalcea** [comment]
Try to debug both versions and see where they differ. 

I've never seen this issue. You could try to replicate it with one of the existing test cases. If you can, then send a Pull Request with the replicating test case.

**Comment by HittiGubbi** [comment]
Ok, it seems the issue was found from our own code, which accidentally sometimes did extra JSON.stringify-operation to some parts of the JSON data. It was just a coincidence that the extra stringifications caused no problems under 2.2.2.

**Comment by vladmihalcea** [comment]
I'm glad you found the issue.
