### ISSUE TITLE
Why update sql occurred when I used JsonBinaryType

### ISSUE THREAD

**Issue by dfreudenberger** [vladmihalcea/hibernate-types#277]
Hey. First of all thanks for your quick reply on twitter. It helped me finding the issues #264 and #263 on github. Unfortunately I'm still in a situation where I see updates happening. It's a mix of kotlin / java but I had exactly the same result in pure java.

```kotlin
@Embeddable
data class FeedItemId(
    val feedId: String,
    val messageId: Long
) : Serializable

@Entity
@Table(name = "...", schema = "...")
@TypeDef(name = "jsonb", typeClass = JsonBinaryType::class)
open class FeedItem(
    feedId: String,
    messageId: Long,
    @Type(type = "jsonb")
    open val content: Content
) {
    @EmbeddedId
    open val id = FeedItemId(feedId, messageId)
}
```

```java
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor
public class Content
{
    public String sku;
    public OffsetDateTime timestamp;
}
```

As soon as persisting a new entity I see the insert statement followed by an update statement. I already figured out that the update is gone when I change Content::timestamp from OffsetDateTime to Long but I simply don't understand why.

Any help is highly appreciated.

**Comment by vladmihalcea** [comment]
I've never used Kotlin and avoid Lombok because it doesn't play well with Hibernate, so, at a first glance, I can't see any obvious problem. 

In order to replicate it, this problem would have to be demonstrated using a test case in this repository, as if it's a bug, then the replicating test case serves as a regression prevention mechanism.

Having a very busy schedule until February, I won't have the time to work on this project unless development is done via consulting.

**Comment by dfreudenberger** [comment]
Hey @vladmihalcea. The issue is not related to Kotlin or Lombok. After stepping through the JsonTpeDescriptor::areEqual method I realised the default objectmapper does not support the date classes introduced in java 8. This results in foo != serialize(deserialize(foo)). 

We could

1. do nothing because it can be fixed by providing a customized objectmapper with JavaTimeModule enabled
2. document it
3. enable the module in the default objectmapper

Your call ;)

**Comment by dfreudenberger** [comment]
Okay it is related to the object mapper's behaviour of how offsetdatetime objects are serialized and deserialized.
Following configuration does the job
```java
new ObjectMapper()
    .registerModule(new JavaTimeModule())
    .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
    .disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE)
    .enable(SerializationFeature.WRITE_DATES_WITH_ZONE_ID):
```

More details can be found here https://github.com/FasterXML/jackson-modules-java8/issues/53

**Comment by vladmihalcea** [comment]
Thanks for providing thd workaround. It will surely help others having the same issue. This might bd included in the default mapper, but it requires analyzing whether it does not break other existing systems.
