### ISSUE TITLE
Postgresql: Generalized Inverted Index

### ISSUE THREAD

**Issue by JensPiegsa** [vladmihalcea/hibernate-types#278]
Hi, I'd like to ask whether this library provides a declarative way to define generalized inverted indices (GIN) for JSONB columns in Postgresql. So schema generation would result in a line like:

```sql
CREATE INDEX product_attributes_idx ON product USING GIN (attributes jsonb_ops);
```

**Comment by vladmihalcea** [comment]
Not only that this cannot provide this, but not even the JPA or Hibernate `@Index` annotation can do that. But, even if it did, it would still be the wrong way to manage your DB schema because, a schema migration tool, like [Flyway](https://vladmihalcea.com/flyway-database-schema-migrations/) is a much better approach.

**Comment by JensPiegsa** [comment]
Thank's for your super-fast reply. I already use Flyway for schema migration. But it's also very helpful being able to automate generation of DDL snippets most of the time (Also not all my integration tests via testcontainers are required to execute the whole schema migration history).

The annotations `@Index`, `@UniqueConstraint`, `@ForeignKey` and also properties like `hibernate.hbm2ddl.delimiter` and `hibernate.physical_naming_strategy` help alot.

I understand that JPAs `@Index` annotation cannot be extended for this purpose. Do you have a tip or a starting point to hook into hibernates schema generation to run an own implementation based on a custom annotation?

**Comment by vladmihalcea** [comment]
I think the only way you could do it is via [auxiliary database objects](https://docs.jboss.org/hibernate/core/3.6/reference/en-US/html/mapping.html#mapping-database-object), but there's no annotation equivalent, so you'd have to add a `hibernate.cfg.xml` file for that.

**Comment by JensPiegsa** [comment]
That worked! For some unknown reason I had to name the file following the pattern `*.hbm.xml` to be picked up and implement `org.hibernate.boot.model.relational.AuxiliaryDatabaseObject`.

```xml
<hibernate-mapping>
	<database-object>
		<definition class="com.example.MyAuxiliaryDatabaseObject"/>
	</database-object>
</hibernate-mapping>
```

**Comment by vladmihalcea** [comment]
Thanks. I'm glad I could help.
