### ISSUE TITLE
Convert parsing or processing errors to HibernateException

### ISSUE THREAD

**Issue by andrei-ivanov** [vladmihalcea/hibernate-types#280]
After doing some manual processing on some JSON values it resulted in some errors being thrown by the Jackson object mapper (`MismatchedInputException` in this case), which gets converted to `IllegalArgumentException` by the [ObjectMapperWrapper](https://github.com/vladmihalcea/hibernate-types/blob/f1eefa5049c020ea3965bcece1b7466a438ad5cf/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/util/ObjectMapperWrapper.java#L52), when I think it should be converted to some `HibernateException` instead, so that the proper error handling would get invoked.

**Comment by vladmihalcea** [comment]
I wonder if the change is going to be backward compatible.

**Comment by andrei-ivanov** [comment]
I don't think anybody expects Hibenate to throw generic `IllegalArgumentException` but specific `HibernateException`s.

**Comment by vladmihalcea** [comment]
That's true. I think this could be implemented in 2.11.

**Comment by vladmihalcea** [comment]
Fixed.
