### ISSUE TITLE
Add support for JavaMoney/Moneta/JSR 354  and/or Joda Money

### ISSUE THREAD

**Issue by benstpierre** [vladmihalcea/hibernate-types#286]
Maybe it would be super useful to implement support for Joda Money?

https://www.joda.org/joda-money/index.html

It seems a lot of people store money incorrectly in databases.

**Comment by benstpierre** [comment]
I noticed postgresql has a money type as well...

https://www.postgresql.org/docs/12/datatype-money.html

**Comment by vladmihalcea** [comment]
@benstpierre That's a good idea. If you submit a Pull Request, I'll review it when I have some time.

**Comment by benstpierre** [comment]
It seems that there is a newer better currency api here http://javamoney.github.io/ which has a jsr.

**Comment by benstpierre** [comment]
Looking around github it appears Jadira project already supports both JSR354 (javamoney) as well as Joda in their usertype library. 

https://github.com/JadiraOrg/jadira/tree/master/usertype.core/src/main/java/org/jadira/usertype/moneyandcurrency

**Comment by vladmihalcea** [comment]
Jadira supports encryption types too. If this is covered by Jadira, then this issue can be closed as there's no reason in reinventing the wheel.

**Comment by benstpierre** [comment]
What do you mean by encryption types?

**Comment by vladmihalcea** [comment]
That was [Jasypt](http://www.jasypt.org/encrypting-passwords.html), not Jadira.
