### ISSUE TITLE
CamelCaseToSnakeCaseNamingStrategy does not seem to work

### ISSUE THREAD

**Issue by LifeIsStrange** [vladmihalcea/hibernate-types#293]
I added hibernate-types and the property:
spring.jpa.hibernate.naming.physical-strategy=com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
But doesn't work. For example it throws an exception showing  hasverifiedmail, meaning hasVerifiedMail became hasverifiedmail instead has_verified_mail

(I'm using spring boot)
@vladmihalcea

**Comment by vladmihalcea** [comment]
Instead of:

    spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true

Use this:

    spring.jpa.properties.hibernate.naming.physical-strategy=com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy

You forgot the `properties` keyword.
