### ISSUE TITLE
False positive "class should override both the equals and hashCode methods" for Enum values

### ISSUE THREAD

**Issue by ewirch** [vladmihalcea/hibernate-types#295]
https://github.com/vladmihalcea/hibernate-types/issues/138 introduced a warning which looks like

> The class MyEnum class should override both the equals and hashCode methods based on the JSON object value it represents!

I cannot override `hashCode()` and `equals()` for enums, they are final.

**Comment by vladmihalcea** [comment]
@ewirch At [this line](https://github.com/vladmihalcea/hibernate-types/blob/a1df2f408a932f9f232d7e42bda95b752b1ffc34/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/json/internal/JsonTypeDescriptor.java#L89), try replacing the `getDeclaredMethodOrNull` check with a `hasMethod` call and see if it works.

Looking forward to getting your feedback.

**Comment by vladmihalcea** [comment]
Fixed.
