### ISSUE TITLE
Occur Exception when I used JsonBinaryType in Multi module project.

### ISSUE THREAD

**Issue by bbuljj** [vladmihalcea/hibernate-types#298]
Hi,
I had used `hibernate-52` in multi-module Project.
project's structure consist of `root, core and api`.

`JPA entity, repository` is defined in `core`.
```
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
public class TestEntity {
    @Id private Long id;

    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    private List<TestType> data;
}
```
when i append `implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.11.3'` to `root dependency`, occured exception below Message
```Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: com.fasterxml.jackson.datatype.jsr310.JavaTimeModule Unable to get public no-arg constructor```

and when i tear off  `dependency 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.11.3`, up and running

why occurred exception, when i append `dependency 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.11.3`

### root dependency
implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.1'

### core dependency
implementation 'com.vladmihalcea:hibernate-types-52:2.4.3'

**Comment by vladmihalcea** [comment]
It looks like a Jackson issue. Not something this can be fixed in this library.
