### ISSUE TITLE
Interval may not be properly mapped to duration

### ISSUE THREAD

**Issue by Bonebreaker9** [vladmihalcea/hibernate-types#299]
While converting months and years are not read nor written from/to the duration.
This may not be problem when writing since duration returns all days in the duration, but PGInterval, if i see correctly, returns at max days up to a month, so Interval -> Duration may result in shortening the duration.

**Comment by Bonebreaker9** [comment]
In #110 you can see the conversion

**Comment by vladmihalcea** [comment]
It's unlikely that I will have the time to investigate any issue in the following months, so if you can think of a good fix, send me a Pull Request and I'll check it out when I have some time.

**Comment by vladmihalcea** [comment]
I tried to understand the issue, but I have no idea what the problem is, and since it references an issue that was fixed, that's even more puzzling. Hence, I'closing it.
