### ISSUE TITLE
ERROR: column "location" is of type json but expression is of type character varying

### ISSUE THREAD

**Issue by akefirad** [vladmihalcea/hibernate-types#30]
I'm trying to use `JsonStringType`, here's how I use it:

```Java
@Entity
@Table(name = "participants")
@TypeDefs({
        @TypeDef(name = "json", typeClass = JsonStringType.class),
        @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class),
})
public class Participant extends BaseEntity {

    private String name;

    @Type(type = "json")
    @Column(columnDefinition = "json")
    @Basic(fetch = FetchType.LAZY)
    private List<Ticket> tickets;

}
```
But I get the following error:
> Caused by: org.postgresql.util.PSQLException: ERROR: column "tickets" is of type json but expression is of type character varying
>  Hint: You will need to rewrite or cast the expression.
>  Position: 55

So to make sure if there's something missing in my code, I tried to run the test `PostgreSQLJsonStringTypeTest`. However to make it similar to my code I had to change the following:
```Java
    @Entity(name = "Event")
    @Table(name = "event")
    public static class Event extends BaseEntity {

        @Type(type = "json") // It was jsonb. But why?
        @Column(columnDefinition = "json")
        private Location location;

    }
    // Same for `Participant` entity!
```
And the test failed with the same error:
> ERROR: column "location" is of type json but expression is of type character varying

It seems that for some reason `JsonStringType` does not work properly. (Or what am I missing?). Thanks.

**Comment by vladmihalcea** [comment]
The short names `jsonb` and `json` I used in my tests are not equivalent to `jsonb` and `json` column types in PostgreSQL.

`jsonb` means that the JDBC Driver expects to provide the object in binary format which is what PostgreSQL expects.

`json` is for passing the JSON object as a String which is how the MySQL Driver works with this object type.

So, for PostgreSQL, use the `JsonBinaryType` and not the `JsonStringType`.

**Comment by vladmihalcea** [comment]
I updated the README file to make it obvious for every database which Hibernate Types are needed depending on the underlying column type.
