### ISSUE TITLE
Is it possible to register Hibernate types in the Hibernate Dialect?

### ISSUE THREAD

**Issue by dzou** [vladmihalcea/hibernate-types#305]
Thanks for your work on the project; it is really great.

I saw there was a [`Dialect.contributeTypes(..)`](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java#L371) method one might override. Is it possible to register the types there for the respective databases so users get the feature transparently? I was just curious if it was possible to override the Postgres dialect and then register the types in there, so they can be transparently used without the `@TypeDefs{..}`.

I gave it a brief try, but it seems like I was only able to register "basic types" in this method, and parameterized types did not seem to work. Was wondering if you ran into the same issues.

**Comment by vladmihalcea** [comment]
You can register Types like [this](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/util/AbstractTest.java#L171) depending on the associated Type you want to register.

**Comment by dzou** [comment]
I see, that is helpful for users. However, I'm wondering from the perspective of a Library Maintainer who maintains a Hibernate Dialect of a database -- if you wanted to write a Hibernate dialect where anyone who used the dialect would automatically get the complex types registered for your database. Is this possible? Suppose you wanted to simplify it so users do not need to manually configure `@TypeDefs` or their entity manager.

I was wondering if this is possible through overriding `Dialect.contributeTypes(..)` somehow. From my analysis though, it only lets you register basic types, and the [SimpleValueBinder does not appear to inject reflection data into basic types](https://github.com/ekirkilevics/Hibernate/blob/master/hibernate-core/src/main/java/org/hibernate/cfg/annotations/SimpleValueBinder.java#L638) (see the if-condition). Which leads me to believe registering a dynamically parameterized type is not possible through the dialect. But I was curious if you agreed with this.

**Comment by vladmihalcea** [comment]
I don't think I've ever used that Dialect method, but you could try it out, and if it doesn't work, you should open a Hibernate issue.

You should also ask this question on the Hibernate Discourse and see what the Hibernate devs advise you to do.
