### ISSUE TITLE
Two different offsets in Range<ZonedDateTime> is not always different timezones

### ISSUE THREAD

**Issue by alexandersavin93** [vladmihalcea/hibernate-types#312]
I have a Range<ZonedDateTime> in postgresql table. When I save range like 
`["2000-01-01 00:00:00Z", "2020-01-01 00:00:00Z"]`
But in table it represents according to DB timezone (In my case Europe/Minsk) as 
`["2000-01-01 02:00:00+02:00", "2020-01-01 03:00:00+03:00"]`
because in winter of 2000 Minsk had offset 02:00 and now has offset +03:00.
So when I try to request data to Range<ZoneDateTime> field in my object, I've got an exception.
`"The upper and lower bounds must be in same time zone!"`

**Comment by vladmihalcea** [comment]
Try to create a replicating test case and see if you can think of a fix for this issue.

Looking forward to reviewing your Pull Request.

**Comment by alexandersavin93** [comment]
@vladmihalcea thanks for your answer. I just want to add this case accrues when JVM and DB placed in different time zones.
