### ISSUE TITLE
PostgreSQL hstore: class org.postgresql.util.PGobject cannot be cast to class java.util.Map

### ISSUE THREAD

**Issue by aint** [vladmihalcea/hibernate-types#313]
Hi there,

I'm trying to configure PostgreSQL types. `array` and `json` work like a charm, but there is an issue with `hstore`. I can save a data but getting an exception while reading from a db:
`java.lang.ClassCastException: class org.postgresql.util.PGobject cannot be cast to class java.util.Map` at the [following line](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/basic/PostgreSQLHStoreType.java#L40)  `return (Map) rs.getObject(names[0]);`

Could you please help with that?

```java
@TypeDefs({
        @TypeDef(name = "json", typeClass = JsonBinaryType.class),
        @TypeDef(name = "array", typeClass = ListArrayType.class),
        @TypeDef(name = "hstore", typeClass = PostgreSQLHStoreType.class)
})
...
@Type(type = "hstore")
@Column(columnDefinition = "hstore")
private Map<String, String> attributes = new HashMap<>();
```

**Comment by vladmihalcea** [comment]
Check out the [`PostgreSQLHStoreTypeTest`](https://github.com/vladmihalcea/hibernate-types/blob/10b82db716695c5a17447ab83fd0bd891011a9fc/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/basic/PostgreSQLHStoreTypeTest.java) which works fine and see why my test works and yours fails.

**Comment by aint** [comment]
Everything works when I run my app with an empty db. I'm able to save and read data. However I get `java.lang.ClassCastException: class org.postgresql.util.PGobject cannot be cast to class java.util.Map` after app restart with no changes.

It looks like the issue is with a PG schema. I use a non default schema and Hibernate reads `hstore` extension from a public schema after app restart. A workaround is to create `hstore` extension for all schemas like this:
```
CREATE EXTENSION IF NOT EXISTS hstore schema pg_catalog;
```

**Comment by aint** [comment]
I'm closing the ticket. Thanks for the help and thanks for your great library.

**Comment by vladmihalcea** [comment]
You're very welcome. I'm glad you found this framework useful.

**Comment by JoaoGSRocha** [comment]
@aint could you explain what did you do in the end? I have the exact same issue (can create / get data but only when starting the program with empty tables)

**Comment by aint** [comment]
@JoaoGSRocha as far as I remember, the root cause was because I declared `@TypeDefs` in an abstract class. I moved `@TypeDefs` to certain classes and that fixed the issue.

**Comment by marcoamato1** [comment]
Hi all,

do you have any clue how to resolve this issue?
Application is working fine as soon as I start it and tables are empty.
Unfortunately after restart I'm having this issue when reading and writing.

I have even tried to apply `CREATE EXTENSION IF NOT EXISTS hstore schema pg_catalog;` but it has not worked.
In addition I do not have any abstract class where I have applied @TypeDefs annotation.

@aint do you have more information to share about this issue for helping me solving it?
@vladmihalcea did you got the change to investigate in much more detail?

Cheers

**Comment by vladmihalcea** [comment]
@marcoamato1 I didn't investigate this issue, but I could do that via consulting if your company is interested in my expertise. If they are not, then you could investigate it and provide a replicating test case that proves the issue and the solution for it.
