### ISSUE TITLE
[Feature Request] QueryDSL support (querydsl issue #615)

### ISSUE THREAD

**Issue by genslein** [vladmihalcea/hibernate-types#314]
Greetings,

Folks for a while seem to be requesting help with getting a fully-integrated JSONB type support for JPA and QueryDSL https://github.com/querydsl/querydsl/issues/615.

Since most folks use this extension to work with JPA already, there are a couple of folks who've created POCs but they haven't been formally integrated into major version support:

https://github.com/wenerme/postjava
https://github.com/alexliesenfeld/querydsl-jpa-postgres-json

Would it be possible to bring these into the fold for this extension?

**Comment by vladmihalcea** [comment]
@genslein Frankly, I have no idea what this feature request is all about.

The POCs you linked are QueryDSL-specific, so they should be integrated into QueryDSL. 

It's QueryDSL who builds on top of JPA, Hibernate and Hibernate Types, not the other way around.

**Comment by jwgmeligmeyling** [comment]
Theres https://github.com/jwgmeligmeyling/hibernate-types-querydsl-apt for QueryDSL codegen on Hibernate-Types specific types. There is already support for ranges and arrays.

JSONB specifically will be implemented as part of https://github.com/jwgmeligmeyling/hibernate-types-querydsl-apt/issues/12
