### ISSUE TITLE
Loading JSON enum list via Envers revision returns String data

### ISSUE THREAD

**Issue by ircecho** [vladmihalcea/hibernate-types#318]
We are having the following problem using hibernate-types-52:2.11.1, hibernate-core and envers 5.4.27.

We have a Column definition which looks like this:

```
@Type(type = "json")
@Column(columnDefinition = "json")
List<UserPermission> permissions = new ArrayList<>();
```
where UserPermission is an enum.

When loading the entity normally, list works fine, but when loading revisions, we get a list that contains (contrary to the declared type) String instead.

So you can understand it better I include the following failing test case.

```java
EntityT entity = repository.findAll().get(0);

// Loading normally works fine.
UserPermission userPermission = entity.getPermissions().get(0);
Assert.assertEquals(UserPermission.class, userPermission.getClass());

entity.setName(entity.getName() + "_suffix");
repository.save(entity);

Revisions<Integer, EntityT> revisions = repository.findRevisions(entity.getId());

Revision<Integer, EntityT> revision = revisions.getContent().get(0);
// The crazy things we test for hibernate. Here revision.getEntity().getPermissions().get(0).getClass() would be String.
Assert.assertEquals(UserPermission.class, revision.getEntity().getPermissions().get(0).getClass());
```
We are stumped by this behaviour. Do you have any ideas how to resolve this? I will be happy to provide additional informaion.

**Comment by vladmihalcea** [comment]
Your use case requires one or two days of consulting in order to provide you with the best solution to your problem. If your company is interested in my [consulting services](https://vladmihalcea.com/consulting/), let me know, as I have several collaboration options.

**Comment by ircecho** [comment]
Two days seems a little modest for saving a whole Enum, don't you think? Maybe you could add even more bugs to your library and charge even more!
