### ISSUE TITLE
How to search for particular value in string-array in postgres-db using hibernate-types?

### ISSUE THREAD

**Issue by Sriram1404** [vladmihalcea/hibernate-types#321]
For example my db contains record 
Table: Student
Id,name,skills
1,'aaa',['java','c','cpp']
2,'bbb',['c#',java']

Above table contains id, name and skills( string array). how to get the records based on person having skills java using hibernate-type lib. please provide the sample example for better understanding.

**Comment by vladmihalcea** [comment]
This library only provides the Hibernate Types that allows you to persist the Java array to a PostgreSQL column type.

If you want to query the column, you need to use the proper PostgreSQL query, according to the manual. So, read the DB manual to find out how you can do that.
