### ISSUE TITLE
How to disable the Hypersistence banner? #196

### ISSUE THREAD

**Issue by Sriram1404** [vladmihalcea/hibernate-types#322]
I have tried to disable the startup banner using hibernate properties( "hibernate.types.print.banner: false" ) but still i could see that banner has popped up while building the project even though added in  yml file of dropwizard framework.  Please have a look at it.

**Comment by vladmihalcea** [comment]
It's all explained in this [GitHub issue](https://github.com/vladmihalcea/hibernate-types/issues/196) why it didn't work.

Just adding that property to the Spring Boot application.properties is not going to work. But, you can find out why and what to do in that issue.
