### ISSUE TITLE
Query: Postgres + Domain + ColumnDefinition.

### ISSUE THREAD

**Issue by guptapavan31** [vladmihalcea/hibernate-types#326]
This is more of a query or I will say it was hard to find any example out there. 

I am using Postgres + Spring boot + JPA + Flyway. 
Now I have a schema 
```
CREATE SEQUENCE my_sequence START WITH 1 INCREMENT BY 50;
CREATE DOMAIN ABC AS VARCHAR(8);
CREATE DOMAIN XYC AS SMALLINT CHECK (VALUE >= 20 AND VALUE <= 50);
```
And then I am using it in the table
```
CREATE TABLE MY_TABLE {
    id                 BIGINT       NOT NULL,
    name           ABC,
    age              XYZ,
    owner_ship  JSONB,
};
```

And I have a entity as 
```
.....
@Entity
@TypeDef(name = "JSONB", typeClass = JsonBinaryType.class)
@Table(name = "my_table") 
private class MyTable {
  

  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "table_key_generator")
  // This sequence is defined once and reused for all entity ids
  @SequenceGenerator(name = "table_key_generator", sequenceName = "default_sequence")
  private Long id;
  
  @Column(columnDefinition = "abc")
  private String name;

  @Column(columnDefinition = "xyz")
  private Integer age;
  
  @NotNull
  @Column(columnDefinition = "JSONB", nullable = false)
  @Type(type ="JSONB")
  private Map<@NotNull String, String> owner_ship;
}

```
My queries are 

1) By just adding columnDefinition in column and pointing it to a existing domain will take care of validation? or I still need to add some constraint like `@Column(length = 8, columnDefinition = "abc")` 

2) Do we have a custom type for such cases in `hibernate-type-55` and I can just add a @Type and it will take care of it.

**Comment by vladmihalcea** [comment]
> 1. By just adding columnDefinition in column and pointing it to a existing domain will take care of validation? or I still need to add some constraint like @Column(length = 8, columnDefinition = "abc")

Better use [Flywa](https://vladmihalcea.com/flyway-database-schema-migrations/) to manage DB schema migrations. Use incremental migrations scripts instead of the HIbernate hbm2ddl.

The Hibernate Types framework doesn't support PostgreSQL domains. If you want that feature, then you could try to investigate how to add support for it.

> 2. Do we have a custom type for such cases in hibernate-type-55 and I can just add a `@Type` and it will take care of it.

If you're talking about mapping JSON, then no. Just use the `JsonType` instead of the `JsonBinaryType` as it's more generic.

If you're talking about those Domain types, then there's no such `Type` currently. But, you could add support for them.

**Comment by guptapavan31** [comment]
I forget to mention that we do use Flyway to manage DB schema Migration. Actually the SQL I mentioned in the question is my SQL script and we upgrade Database with Flyway DB. 

I am specifically talking about the Domain Types. Thanks for your Answer. I will try to investigate to find way for Domain type.

**Comment by vladmihalcea** [comment]
> I forget to mention that we do use Flyway to manage DB schema Migration. Actually the SQL I mentioned in the question is my SQL script and we upgrade Database with Flyway DB.

That's a great choice. A tool like Flyway is the proper way of dealing with database schema migrations.

> I am specifically talking about the Domain Types. Thanks for your Answer. I will try to investigate to find way for Domain type.

If you cannot find a solution and your company needs this feature, then I could add support for it via [consulting](https://vladmihalcea.com/consulting/), so keep that in mind.
