### ISSUE TITLE
How to build criteria for string array where certain element of array is equal to X?

### ISSUE THREAD

**Issue by PashaTurok** [vladmihalcea/hibernate-types#327]
This is my table:

```
CREATE TABLE IF NOT EXISTS NODE (
           UUID VARCHAR NOT NULL,
           PARENT_UUID VARCHAR NULL,
           PATH ARRAY NULL,
          PRIMARY KEY (UUID));
```

This is my entity:

```
@TypeDefs({
    @TypeDef(
        name = "string-array",
        typeClass = StringArrayType.class
    )
})
@Entity
@Table(name = "NODE")
public class Node {

    @Id
    @Column(name = "UUID")
    private String uuid;

    @Column(name = "PARENT_UUID")
    private String parentUuid;

    @Type(type = "string-array")
    @Column(
        name = "PATH",
        columnDefinition = "text[]"
    )
    private String[] path;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getParentUuid() {
        return parentUuid;
    }

    public void setParentUuid(String parentUuid) {
        this.parentUuid = parentUuid;
    }

    public String[] getPath() {
        return path;
    }

    public void setPath(String[] path) {
        this.path = path;
    }
}
```

Now I want to build the following SQL query with JPA criteria:

`SELECT * FROM NODE where path[2] = '4a46a59a-6ff5-4ae2-9b84-eb2a357e57ee';`

This is what I have:

```
CriteriaBuilder criteriaBuilder = manager.getCriteriaBuilder();
CriteriaQuery<Node> criteriaQuery = criteriaBuilder.createQuery(Node.class);
Root<Node> root = criteriaQuery.from(Node.class);
var path = root.get("path");
criteriaQuery.select(root).where(criteriaBuilder.equal(path, "4a46a59a-6ff5-4ae2-9b84-eb2a357e57ee"));
TypedQuery<Node> typedQuery = manager.createQuery(criteriaQuery);
List<Node> nodes = typedQuery.getResultList();
```

Could anyone say how I can set path index to `1` in my criteria query? I would be very thankful.

**Comment by vladmihalcea** [comment]
You need to create a `path_element` PostgreSQL function that returns the `path` array element value for the element position you send as the function argument.

Afterward, your query becomes:

SELECT * FROM NODE where path_element(2) = '4a46a59a-6ff5-4ae2-9b84-eb2a357e57ee';

And, that query can be easily transformed to Criteria API via an SQL function call.

**Comment by PashaTurok** [comment]
I did it with h2 and custom functions. Thank you very much for your help. Only one thing, final solution was:

```
criteriaQuery.select(root).where(
                builder.equal(builder.function("path_element", String.class, root.get("path"), builder.literal(2)),
                        "4a46a59a-6ff5-4ae2-9b84-eb2a357e57ee"));
```

I mean, that there are two arguments in function as the first argument is selected column. Is it possible to have only one integer argument as you wrote above?

**Comment by vladmihalcea** [comment]
The array column can be hard-coded in the function since this function is called `path_element`, not `array_element`. There's no problem in making it generic. It's up to you.
