### ISSUE TITLE
Convert JSON from MySQL to UTF-8

### ISSUE THREAD

**Issue by alexandrmiee** [vladmihalcea/hibernate-types#33]
Could not deserialize values from mysql json column with utf-8 encoding.
Example
`
@ TypeDef(
    name = "jsonb-node", 
    typeClass = JsonStringType.class
)`
`
public class Catalog {`
`...`
`
@ Type( type = "jsonb-node" )`
`
@ Column(columnDefinition = "json")`
`
public ArrayNode tags;`
`...`
`
List<Catalog> catalog = em.createNativeQuery("select * from Catalog c ",Catalog.class).getResultList();
`
The result is 
`"tags":[{"key":"??????????","value":"????????????"},{"key":"new","value":"template"}]`

**Comment by vladmihalcea** [comment]
Most likely there's an incompatibility between the encoding you used in your DB with the one used by your application.

If you can replicate it and send me a Pull Request that proves the issue, I'm going to reopen the issue. Otherwise, it's because of the encoding mismatch.
