### ISSUE TITLE
JsonType init not using Configuration.INSTANCE

### ISSUE THREAD

**Issue by mgohin** [vladmihalcea/hibernate-types#332]
Hi there,

we are using an custom `ObjectMapperSupplier` and we see that the `public JsonType(Configuration configuration) {` is not using Configuration singleton:

https://github.com/vladmihalcea/hibernate-types/blob/a96859704c0295f811e871070b99f8c4580f7aff/hibernate-types-55/src/main/java/com/vladmihalcea/hibernate/type/json/JsonType.java#L57

unlike others
https://github.com/vladmihalcea/hibernate-types/blob/a96859704c0295f811e871070b99f8c4580f7aff/hibernate-types-55/src/main/java/com/vladmihalcea/hibernate/type/json/JsonType.java#L43
https://github.com/vladmihalcea/hibernate-types/blob/a96859704c0295f811e871070b99f8c4580f7aff/hibernate-types-55/src/main/java/com/vladmihalcea/hibernate/type/json/JsonType.java#L50

So we have multiple instances of our custom `ObjectMapperSupplier`, and we think it's not intended.

**Comment by vladmihalcea** [comment]
The goal of the `public JsonType(Configuration configuration)` method is to supply a custom `Configuration`, not us the default one.

So, what exactly is your problem?

**Comment by mgohin** [comment]
Alright, that makes sense.

When starting the app, the default constructor of `JsonType` is called, but also the one with the custom `Configuration`, so our `ObjectMapperSupplier` is instanciated twice. 

We are wondering why it happens, is it normal, is a problem on our side or is it a problem in the lib ?

**Comment by vladmihalcea** [comment]
In the same application, you might use different flavors of JSON objects. Having different `JsonType` doesn't sound like a problem to me.
