### ISSUE TITLE
Behaviour in case of deserialization error of JSON columns

### ISSUE THREAD

**Issue by victornoel** [vladmihalcea/hibernate-types#333]
Hi,

Maybe it's already documented but couldn't find it: I'm worried about what happens if there is a de-serialization error when JSON columns are loaded by Hibernate into the corresponding Entity DTO. Does the load completely fail? Can I  

Another related question is: how to write custom code to handle such situation from inside the entity class?

Maybe it's more related to hibernate than hibernate-types, but since this kind of problem are more susceptible to happen when deserializing complex datatypes such a json, at least a small doc redirecting to Hibernate's would be really helpful :)

Thanks!

**Comment by vladmihalcea** [comment]
If there's a deserialization error, most likely that an exception will be triggered.

Now, related to customizing the deserialization process, I could offer your company a training/consulting session where, after you explain your business requirements, I could provide you the best solution that can address your needs.

**Comment by victornoel** [comment]
@vladmihalcea thanks, that's what I was suspecting.

Basically the use case is that sometimes, you store json as a column in db, then this json schema evolves, so you have to handle the situation where you want to allow loading the previous json without error and then convert it to the new schema.

I suppose that that's what migrations are for, and I shouldn't try to use the entity mapping to achieve that objective?

**Comment by vladmihalcea** [comment]
You can use the `JsonType` provided by this framework while also evolving your JSON column schema. As you will discover when analyzing the source code, of both Hibernate ORM and Hibernate Types, you can customize almost anything you want. So, yes, the task is doable.

**Comment by victornoel** [comment]
@vladmihalcea ok, thank you for your explanation :)

I will close this then, cheers!

**Comment by vladmihalcea** [comment]
I'm glad I could help.
