### ISSUE TITLE
JSON parse error: Cannot construct instance of com.vladmihalcea.hibernate.type.basic.Inet

### ISSUE THREAD

**Issue by Okiring** [vladmihalcea/hibernate-types#339]
**1. Error on saving Inet type to postgres. There was no problem reading inet type from the database. The problem was mainly upon saving new entities**

Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `com.vladmihalcea.hibernate.type.basic.Inet` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.vladmihalcea.hibernate.type.basic.Inet` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)

**2. Below are the steps i performed to fix the above the issue.** 

Upon checking the inet class, i realized it has no default empty constructor so i created a custom inet class with an empty constructor and everything started working fine again.

**Comment by vladmihalcea** [comment]
The `Inet` class is immutable, hence you need to register a `@JsonComponent` in Spring Boot to handle it. Check out [this article](https://javadeveloperzone.com/spring-boot/spring-boot-custom-json-serialize-deserialize-example/) for more details.
