### ISSUE TITLE
Convert UTF8 String error

### ISSUE THREAD

**Issue by alexandrmiee** [vladmihalcea/hibernate-types#34]
When read UTF8 string from mysql json column, result string converting with error:
Original string
```
[
	{
		"key" : "новый"
	}
]

Bytes
5b0a097b0a0909226b657922203a2022d0bdd0bed0b2d18bd0b9220a097d0a5d
```
Result string after hibernate request
```
{"key":"??????????"}
Bytes
7B226B6579223A223F3F3F3F3F3F3F3F3F3F227D
```

If read varchar column no error occure.

**Comment by vladmihalcea** [comment]
Send a Pull Request which proves the use case with a test case.

**Comment by vladmihalcea** [comment]
Closed as no test case was provided.
