### ISSUE TITLE
MySQL Data Truncation: Data too long for JSON column

### ISSUE THREAD

**Issue by chenningg** [vladmihalcea/hibernate-types#340]
Hi, I have this entity like such, where I define the JSON type to be JsonStringType as specified by the docs. I'm trying to save a small JSON data into a mySQL database, and this generally works well - but if my JSON becomes just a little longer (>50 bytes, not even MB!), there's an error that says data is too long for the json column.

However, if I save the JSON manually into mySQL, it works, so the issue is probably somewhere in Hibernate/JPA/Hibernate Types.

Here is my entity. I'm trying to save the mapping as a JSON column in mySQL:

```
@Table(name = "xxx")
@TypeDefs({
        @TypeDef(name = "json", typeClass = JsonStringType.class),
})
public class XXX extends BaseEntity {
  @Type(type = "json")
  @Column(columnDefinition = "json")
  private Map<String, String> mapping = new HashMap<String, String>();
}
```

My repository:

```
public interface Repo extends JpaRepository<XXX, Long> {

}
```

And then I call this to save:

`repo.save(XXX);`

This data works and the JSON is properly saved to the database under the mapping column:

```
{
  "Bloomberg Code":"Direct Bill",
  "Region":"Region",
  "Exchange":"Exchange Code",
  "Fee Group":"Product Group Name",
  "Product":"Product Name",
  "Quoting CCY":"Currency",
  "Execution Venue":"Trade Type",
  "Voice Execution Markup":"Brokerage Amount"
}
```

However this doesn't and throws the MySQL Data Truncation: Data too long for mapping column error:

```
{
  "Bloomberg Code":"Direct Bill",
  "Region":"Region",
  "Exchange":"Exchange Code",
  "Fee Group":"Product Group Name",
  "Product":"Product Name",
  "Quoting CCY":"Currency",
  "Execution Venue":"Trade Type",
  "Total Clearing Rate (Full Service) incl NFA":"Brokerage Amount"
}
```

Note the last line in the JSON, where the string becomes considerably longer. Are there any tips on how to fix this? (:
Thank you!

**Comment by vladmihalcea** [comment]
I could investigate it via consulting if you're interested.

**Comment by chenningg** [comment]
Not sure where the issue is, either way, fixed it by just storing the JSON as a string and mapping it without the library.
