### ISSUE TITLE
Postgresql Trying to check if a certain value exist in a text array type in JPA Criteria Query returns IllegalArgumentException

### ISSUE THREAD

**Issue by Mohammed97abdulhai** [vladmihalcea/hibernate-types#341]
@Override
	public Predicate toPredicate(Root<People> root, CriteriaQuery<?> criteriaQuery, CriteriaBuilder criteriaBuilder) {
		final List<Predicate> predicates = new ArrayList<>();
		if(criteria.getName() != null)
			predicates.add(criteriaBuilder.like(root.get("name"), "%" + criteria.getName() + "%"));
		if(criteria.getCategory() != null)
			predicates.add(criteriaBuilder.isMember(criteria.getCategory(), root.get("categories")));
		return criteriaBuilder.and(predicates.toArray(new Predicate[predicates.size()]));
	}

the isMember function is treating the categories field as a singular field and not a text array
is there anyway to avoid this?

**Comment by vladmihalcea** [comment]
I've never tried it, but I could find you a solution via [consulting](https://vladmihalcea.com/consulting/) if you're interested.

**Comment by tejareddy457** [comment]
Did we have any answer for the question above

**Comment by vladmihalcea** [comment]
@tejareddy457 No answer, so far. But, I could investigate it via consulting if you're company is interested in getting this problem solved sooner than later.
