### ISSUE TITLE
Anonymous inner class with an instance initializer serialization problems

### ISSUE THREAD

**Issue by andres99x** [vladmihalcea/hibernate-types#342]
I've run into this issue where when initializing an ArrayList using an anonymous inner class it fails to serialize/deserialize because it's picking up the wrong Class.

[Find here the failing Test example.](https://github.com/andres99x/hibernate-types/blob/master/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/json/PostgreSQLJsonListPojoTest2.java)

`$ mvn clean -Dtest=PostgreSQLJsonListPojoTest2 test -pl hibernate-types-52 -am`

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.592 s <<< FAILURE! - in com.vladmihalcea.hibernate.type.json.PostgreSQLJsonListPojoTest2
[ERROR] test(com.vladmihalcea.hibernate.type.json.PostgreSQLJsonListPojoTest2)  Time elapsed: 1.565 s  <<< ERROR!
java.lang.IllegalArgumentException: Cannot create TypeBindings for class com.vladmihalcea.hibernate.type.json.PostgreSQLJsonListPojoTest2$1 with 1 type parameter: class expects 0
	at com.vladmihalcea.hibernate.type.json.PostgreSQLJsonListPojoTest2.lambda$test$0(PostgreSQLJsonListPojoTest2.java:34)
	at com.vladmihalcea.hibernate.type.json.PostgreSQLJsonListPojoTest2.test(PostgreSQLJsonListPojoTest2.java:33)
```

 I'm not sure where the issue stems from, i haven't had time to look into it, but wanted to report this with a reproducible test case.

Thanks for the great work!

**Comment by vladmihalcea** [comment]
This is an [anti-pattern](https://blog.jooq.org/2014/12/08/dont-be-clever-the-double-curly-braces-anti-pattern/):

```
new ArrayList<Property>() {{
	add(new Property("title", "High-Performance Java Persistence"));
	add(new Property("author", "Vlad Mihalcea"));
	add(new Property("publisher", "Amazon"));
	add(new Property("price", "$44.95"));
}}
```

The double bracket means you are creating an anonymous class just for initializing the `List`. But, the class will have a reference to the outer Object reference, hence the anti-pattern. Therefore, this is just a usability issue.
