### ISSUE TITLE
JsonB support in postgres and h2

### ISSUE THREAD

**Issue by bobbyphilip** [vladmihalcea/hibernate-types#345]
This is kind of related to https://github.com/vladmihalcea/hibernate-types/issues/316

```
@Type(type = "json")
@Column(columnDefinition = "jsonb")
private MyDataObject data;
```

Mapping works like a charm in postgres
When using h2 while running tests, I get the following error
_Caused by: org.h2.jdbc.JdbcSQLException: Unknown data type: "JSONB"; SQL statement_

I see the test cases for [H2](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-55/src/test/java/com/vladmihalcea/hibernate/type/json/generic/GenericH2JsonMapTest.java) use **json**,  while the ones for  [postgres](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-55/src/test/java/com/vladmihalcea/hibernate/type/json/generic/GenericPostgreSQLJsonMapTest.java) use **jsonb**

Is the combination of h2 & jsonb  not possible at the moment(maybe because of h2) or is this an oversight?

**Comment by vladmihalcea** [comment]
If you use `JsonType`, it should work as this Type picks the proper descriptor for each supported DB. Check out the JavaDoc and the project examples for more details.
