### ISSUE TITLE
NPE when initializing JsonSqlTypeDescriptor on "merge" action

### ISSUE THREAD

**Issue by hoomb** [vladmihalcea/hibernate-types#346]
Hello,
I'm using your fabulous component in a Spring Boot application.
This is how I defined my Entity:
```
@Entity
@Table(name = "car")
@IdClass(CarId.class)
@TypeDef(name = "json", typeClass = JsonType.class)
public class Car implements Serializable {
    @Id
    @Column(name = "brand")
    private String brand;

    @Id
    @Column(name = "color")
    private String color;

    @Column(name = "doors")
    private Integer doors;

    @Type(type = "json")
    @Column(name = "properties", columnDefinition = "jsonb")
    private List<CarProperty> properties = new ArrayList<>();
}
```
CarId.java
```
public class CarId implements Serializable {
    private String brand;
    private String color;
}
```

CarProperty.java
```
public class CarProperty implements Serializable {
    @JsonProperty("prop-number")
    private String propNumber;
    @JsonProperty("values")
    @Valid
    private List<String> values = null;
```

everything works properly once the Entity doesn't exist in database and must be saved.

But if I
- Restart the application, so the cached `sqlTypeDescriptor` Object in `JsonSqlTypeDescriptor` will be cleared up.
- Call `repository.saveAll(cars)` to update (`merge`) existing entities, I will get a NullPointerException a on `extractJson` function because of nulled and not initialized `sqlTypeDescriptor` and `dialect`objects in `JsonSqlTypeDescriptor.java` class

I will really appreciate if you could help me to resolve this issue.

**Comment by vladmihalcea** [comment]
Any issue requires a replicating test case that proves the problem. Therefore, this is what you need to do:

1. Fork the project
2. Use any of the existing test cases to create your own that replicates the problem using the same flow you do in Spring
3. If you cannot replicate it, try to create a Spring Boot app that proves the issue
4. Debug the app to see why it happens
5. Find the problem and create a fix
6. Build the project locally to see the fix works
7. Send a Pull Request with the fix and I'll review it

Looking forward to seeing your contribution.

**Comment by hoomb** [comment]
updating to the recent Version 2.12.1 has solved the Problem. Thank you.

**Comment by vladmihalcea** [comment]
@hoomb Thanks for confirming it.
