### ISSUE TITLE
ListArrayType : The provided Temperature is not a Object[] or List!

### ISSUE THREAD

**Issue by indvamshi** [vladmihalcea/hibernate-types#347]
Hi
I am using ListArrayType as String when I query using JPA specification/CriteriaBuilder, hibernate-types unable to convert ListArrayType unable to convert to desired Java List type .  

So, I downloaded hibernate-types and modified the test ListArrayTypeTest to query using CriteriaBuilder surprisingly I got the same issue on hibernate-types repository.

The code snippet I used to replicate the issue,
final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();
            CriteriaQuery<Event> criteriaQuery = criteriaBuilder.createQuery(Event.class);
            Root<Event> itemRoot = criteriaQuery.from(Event.class);
            final CriteriaQuery<Event> sensonNames = criteriaQuery.select(itemRoot).
                where(itemRoot.get("sensorNames").in(Arrays.asList("Temperature", "Pressure")));

            final TypedQuery<Event> query = entityManager.createQuery(sensonNames);
            final List<Event> resultList = query.getResultList();
            System.out.println(resultList);

Here is the stacktrace:
java.lang.UnsupportedOperationException: The provided Temperature is not a Object[] or List!

	at com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor.unwrap(ListArrayTypeDescriptor.java:60)
	at com.vladmihalcea.hibernate.type.array.internal.ArraySqlTypeDescriptor$1.doBind(ArraySqlTypeDescriptor.java:38)
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:73)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:276)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:271)
	at org.hibernate.param.NamedParameterSpecification.bind(NamedParameterSpecification.java:53)
	at org.hibernate.loader.hql.QueryLoader.bindParameterValues(QueryLoader.java:648)

Looks like its does not work with CriteriaBuilder. But, if I use StringArrayType then it work as expected.

Can you please take a look.

Attached the screenshot for your reference.

![Screenshot 2021-09-24 at 20 44 05](https://user-images.githubusercontent.com/3646825/134731566-878864a0-7c45-41ef-ab5b-d200b8514172.jpg)

**Comment by vladmihalcea** [comment]
Having a replicating test case is the first step towards finding a fix.

Now, since you know that StringArrayType works, you'll have to debug it and see why that one works and ListArrayType does not.

Once you find the problem, you could provide the fix.

Looking forward to getting your Pull Request with the replicating test case and the fix.

**Comment by vladmihalcea** [comment]
Closed as no test case was provided.
