### ISSUE TITLE
class org.postgresql.util.PGobject cannot be cast to class java.util.Map

### ISSUE THREAD

**Issue by imaxkhan** [vladmihalcea/hibernate-types#362]
hi every body
i have hibernate-types-55
when trying to map HStore Data type on my entity i face error like this
class org.postgresql.util.PGobject cannot be cast to class java.util.Map (org.postgresql.util.PGobject is in unnamed module of loader 'app'; java.util.Map is in module java.base of loader 'bootstrap')

```
@entity
@table(name = "COUNTRY_NAME")
@getter
@Setter
@NoArgsConstructor
@typedef(name = "hstore", typeClass = PostgreSQLHStoreType.class)
public class CountryNameEntity {
@id
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "Country_Name_Sequence")
@SequenceGenerator(name = "Country_Name_Sequence", sequenceName = "COUNTRY_NAME_SEQ", allocationSize = 50)
@column(name = "ID_PK")
private int id;
@column(name = "COUNTRY_CODE", length = 2, unique = true)
private String countryCode;
@column(name = "NAME", columnDefinition = "public.hstore")
@type(type = "hstore")
private Map<String, String> name;
@column(name = "COUNTRY_DEFAULT_LANGUAGE_CODE", length = 2)
private String countryDefaultLanguageCode;
@column(name = "PARTITION")
private Integer partition;
}
```

**Comment by vladmihalcea** [comment]
It looks like a Java module issue. Try to upgrade the PostgreSQL driver version.

In the meantime, check out [this test case](https://github.com/vladmihalcea/hibernate-types/blob/e419ad5089ff7b8f4746694dd6b0b19dc31866d4/hibernate-types-55/src/test/java/com/vladmihalcea/hibernate/type/basic/PostgreSQLHStoreTypeTest.java) that works like a charm on Java 8.

**Comment by imaxkhan** [comment]
i think i have same issue , hstore is in public schema of postgres, and every thing is ok for first insrted data by me in the same session but if session changes the problem occurs
https://githubmemory.com/repo/vladmihalcea/hibernate-types/issues/313
i think the issue above is same as mine but i didnt understand the solution

**Comment by vladmihalcea** [comment]
Try this suggestion provided by the issue:

> A workaround is to create `hstore` extension for all schemas like this:

    CREATE EXTENSION IF NOT EXISTS hstore schema pg_catalog;

**Comment by imaxkhan** [comment]
yes that's the solution but i found another way

**Comment by vladmihalcea** [comment]
You're welcome. I'm glad you figured it out.

**Comment by marcoamato1** [comment]
Hi all,

posting also here same questione as per https://github.com/vladmihalcea/hibernate-types/issues/313

Cheers,
Marco
