### ISSUE TITLE
spring boot 2.6.0 hibernate 5.6.1 not support @TypeDef @Type

### ISSUE THREAD

**Issue by kaoding** [vladmihalcea/hibernate-types#367]
```
<dependency>
    <groupId>com.vladmihalcea</groupId>
    <artifactId>hibernate-types-56</artifactId>
    <version>x.x.x</version>
</dependency>
```

**Comment by vladmihalcea** [comment]
There's no such hibernate-types-56 Maven dependency. Use hibernate-types-55 instead.

**Comment by kaoding** [comment]
@TypeDef @Type, deprecated
hibernate 5.6.1
![image](https://user-images.githubusercontent.com/18542211/142960708-9a252c64-fc1d-4f30-8ea0-8283f7d5f4c6.png)

**Comment by vladmihalcea** [comment]
Deprecated doesn't mean it does not work. It means they will change in Hibernate 6.

**Comment by kaoding** [comment]
thanks

**Comment by vladmihalcea** [comment]
You're welcome. It's sad they deprecated it before offering an alternative.

**Comment by kth13** [comment]
@vladmihalcea your library has been pretty useful. Thanks for that. I tried upgrading my application to hibernate-core:6:1:1.Final where they have totally removed the @TypeDef annotation. 
I having an annotation like this ```@TypeDef(name = "list-array", typeClass = ListArrayType::class)``` and a reference like this ```@Type(type = "list-array") @Column(name = "disabilities", columnDefinition = "text[]")```. what should be the alternative if this is not supported anymore

**Comment by asdirc** [comment]
Same question here. I don't find the replacement for TypeDef
@vladmihalcea  do you have any idea ?

**Comment by vladmihalcea** [comment]
There's no replacement. You have to use the `@Type` annotation on every JSON entity property:

    @Type(ListArrayType.class)
    private List<Date> dateValues;

**Comment by ekeeya** [comment]
How do I go about postrgesql hstore

**Comment by vladmihalcea** [comment]
@ekeeya For Hibernate 6, [like this](https://github.com/vladmihalcea/hibernate-types/blob/a5130b438c1e41466968a4de87c2bb5bf3e09b60/hibernate-types-60/src/test/java/com/vladmihalcea/hibernate/type/basic/PostgreSQLHStoreTypeTest.java#L81). For older Hibernate version, check out the associated Hibernate Types module for the `PostgreSQLHStoreTypeTest`.

**Comment by ekeeya** [comment]
Thank you @vladmihalcea, I realised I had an older version of `hibernate-type` (52) in my `pom.xml` switching to (60) with your suggestion helped.

Thank you very much.

**Comment by vladmihalcea** [comment]
You're welcome

**Comment by kmcsekar** [comment]
@vladmihalcea I upgraded my Hibernate library from 5.4.32 to hibernate-core:6.1.4.  @typedef annotation is no longer supported on this Hibernate version 6.1.4.
I having an annotation defined like this 
@TypeDef(name = "json", typeClass = JsonStringType.class)
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
 and a referenced like this 
 @Type(type = "json") @Column(name="Tag1")
 @Type(type = "jsonb") @Column(name="Tag2")

I have upgraded my com.vladmihalcea:hibernate-types-52 to com.vladmihalcea:hibernate-types-60.
Since typedef is no longer supported, what should be the equivalent approach to support this type in Hibernate 6.1.x

Appreciate your help on this.   Thanks!

**Comment by vladmihalcea** [comment]
@kmcsekar Check out [this README section](https://github.com/vladmihalcea/hypersistence-utils#hibernate-6) for a solution.

**Comment by kmcsekar** [comment]
Thanks @vladmihalcea 
I made the recommended change as follows
Hibernate 6:
public class xyz{
    @Column(name = TAGS)
    @Type(JsonType.class)
    @Lob
    private Map<String, Map<String, Object>> Tags;
}

Following is the code in Hibernate 5 (that use to work):
@TypeDefs({
        @TypeDef(name = "json", typeClass = JsonStringType.class),
        @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
})
public class xyz{
    @Column(name = TAGS)
    @Type("json")
    @Lob
    private Map<String, Map<String, Object>> Tags;
}

In Hibernate 6, I started seeing bunch of incompatible type error
incompatible types: java.lang.Class<com.vladmihalcea.hibernate.type.json.JsonType> cannot be converted to java.lang.Class<? extends org.hibernate.usertype.UserType<?>>

Any suggestion on what could be causing this errors?   Thanks a lot for your assistance on this.

**Comment by vladmihalcea** [comment]
First, there's no `com.vladmihalcea.hibernate.type.json.JsonType` in Hypersistence Utils.

Second, just run [this test case](https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-60/src/test/java/io/hypersistence/utils/hibernate/type/json/generic/GenericPostgreSQLJsonTypeTest.java#L136) and then compare with your to see why mine is working and yours is not.

**Comment by akhil-finvasia** [comment]
Hi @vladmihalcea 
We are using JSON column type.

```
import java.util.List;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import com.vladmihalcea.hibernate.type.json.JsonBinaryType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Entity
@Table
@Data
@TypeDefs({ @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class) })
public class Books {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private int id;
	@Column
	private String bookname;
	@Column
	private String author;
	@Column
	private int price;

	@Type(type = "jsonb")
	@Column(columnDefinition = "jsonb")
	private List<String> watchlist;

}
```

with Java-8 and Spring-boot-2.x it was working but it is not working with Java-17 and Spring-boot-3.x.

Is there any other way to create JSON column type and query on the same ?

Please help.

**Comment by vladmihalcea** [comment]
@akhil-finvasia This project only provides the source code and the binaries for free. Support is not available for free. You will need to purchase my [Coaching program](https://vladmihalcea.teachable.com/p/high-performance-java-persistence-coaching-basic) to get support.

**Comment by a-tarasiuk** [comment]
@vladmihalcea, Tell me, please, what is the analogue of using the `uuid-char` type for `MariaDB`:

```java
@Type(type="uuid-char")
    private UUID id;
```

**Comment by vladmihalcea** [comment]
@a-tarasiuk Join my [Coaching program](https://vladmihalcea.teachable.com/p/high-performance-java-persistence-coaching-basic), and I will investigate it for you.

**Comment by a-tarasiuk** [comment]
[Answer](https://discourse.hibernate.org/t/what-is-equivalent-for-type-annotation-in-hibernate/6152/5)
