### ISSUE TITLE
Support for Hibernate v5.3

### ISSUE THREAD

**Issue by x0a1b** [vladmihalcea/hibernate-types#37]
Does `hibernate-types` support Hibernate 5.3 at all?

**Comment by vladmihalcea** [comment]
Yes, it should work just fine.

**Comment by x0a1b** [comment]
If I may ask which version `artifactId` should I use?

**Comment by vladmihalcea** [comment]
I updated the [README](https://github.com/vladmihalcea/hibernate-types) so it's more clear now.

You should use the `hibernate-types-52` artifact.
