### ISSUE TITLE
saving Bidirectional @OneToMany produce extra update statement

### ISSUE THREAD

**Issue by ferinoc** [vladmihalcea/hibernate-types#375]
Hello,
I have Bidirectional @OneToMany relation similar like in this article:
https://vladmihalcea.com/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/

Child entity has jsonb column.

if set values to jsonb column, hibernate produce extra update statement during saving parent entity  like:
Hibernate: update SITEMAPURL set created=?, lastmodified=?, alternateLinks=?, changeFreq=?, lastMod=?, loc=?, priority=?, reference=?, SITEMAPURLSET=? where id=?

if jsonb column is empty, then hibernate doesn't execute update statement.

I'm using spring boot 2.6.1 and Hibernate Types 55 version 2.14.0

Do you have any idea what could be the problem?
Thank you.

**Comment by vladmihalcea** [comment]
Check out if you implemented [equals and hashCode properly for the elements contained in the collection](https://github.com/vladmihalcea/hibernate-types#best-practices).

**Comment by ferinoc** [comment]
Thank you. Seems that was the problem :) After adding Lombok annotation @EqualsAndHashCode no extra update is present. Thank you :)

**Comment by vladmihalcea** [comment]
I'm glad I could help.
