### ISSUE TITLE
ERROR: column "duration" is of type daterange but expression is of type bytea

### ISSUE THREAD

**Issue by mujehoxe** [vladmihalcea/hibernate-types#379]
```
	@Column(
		columnDefinition = "daterange"
	)
	private Range<LocalDate> duration =
		Range.closedOpen(
			LocalDate.now(),
			LocalDate.of(2025, 12, 3));
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "duration" is of type daterange but expression is of type bytea
  Hint: You will need to rewrite or cast the expression.
  Position: 103

Note. when i don't specify column definition i get this mess
![image](https://user-images.githubusercontent.com/52047683/147411196-399b128a-4c8d-4530-8b8f-968ba18fb392.png)

**Comment by vladmihalcea** [comment]
First, a replicating test case is required.

Second, a fix is needed to makes the test pass. Send me a Pull Request when it's done, and I'll check it out.

**Comment by mujehoxe** [comment]
Totaly my bad i didn't see this
```
@TypeDef(
    typeClass = PostgreSQLRangeType.class,
    defaultForType = Range.class
)
```
thanks for the truble.
