### ISSUE TITLE
JsonStringSqlTypeDescriptor.getSqlType() mismatch MySQL57Dialect

### ISSUE THREAD

**Issue by kentkwan** [vladmihalcea/hibernate-types#38]
must use types.java_object to match MySQL57Dialect in hibernate version 5.2.
can represent when use "spring.jpa.hibernate.ddl-auto=create", "no dialect mapping for jdbc type: 1111" exception will be thrown.

**Comment by vladmihalcea** [comment]
Send me a Pull Request that proves the issue. Use existing test cases as s reference.

**Comment by vladmihalcea** [comment]
Closed as no test case was provided.
