### ISSUE TITLE
Support for Jakarta EE 9?

### ISSUE THREAD

**Issue by frode-carlsen** [vladmihalcea/hibernate-types#380]
Hibernate now publishes alternative artefacts for jakarta (hibernate-core-jakarta for example), but hibernate-types still refers to Java EE specs (javax.persistence).  Any chance of publishing dual artefacts?  This can be done by post-processing jars with Eclipse Transformer for  example

**Comment by vladmihalcea** [comment]
Anything can be done. Send me a Pull Request with a fix proposal.
