### ISSUE TITLE
select inside jsonb list by date

### ISSUE THREAD

**Issue by ferinoc** [vladmihalcea/hibernate-types#381]
Hello,
In parent dbo "market" I have list of deliveries:

```
@Type(type = "json")
    @Column(columnDefinition = "jsonb")
    private List<OrderDeliveryDbo> orderDeliveries = new ArrayList<>();
```

and OrderDeliveryDbo looks like this:

```
@NoArgsConstructor
@Data
@EqualsAndHashCode
public class OrderDeliveryDbo implements Serializable {
    @Nonnull
    private String deliveryCode;
    private LocalDate deliveryFrom;
    private LocalDate deliveryTo;
}
```

in db it is stored like this:

`[{"deliveryTo": [2021, 10, 1], "deliveryCode": "LT2", "deliveryFrom": [2021, 8, 30]}, {"deliveryTo": [2021, 10, 29], "deliveryCode": "LT3", "deliveryFrom": [2021, 10, 4]}]`

I'm able to fetch all markets which have deliveryCode LT2 with following sql query:
```
select m.*
from market m
where exists(select *
             from jsonb_array_elements(m.order_deliveries) obj(val)
             where obj.val ->> 'deliveryCode' = 'LT2'
          );
```

But how I can compare dates? Like select all markets where  deliveryFrom is after 1.1.2020 ?

Thank you very much.

**Comment by vladmihalcea** [comment]
I could investigate a solution via [consulting](https://vladmihalcea.com/consulting/) if you're interested in my expertise.
