### ISSUE TITLE
Schema generates uuid sql type instead of json or jsonb

### ISSUE THREAD

**Issue by tfactor2** [vladmihalcea/hibernate-types#383]
Summary
=======

We have a Pdo with a custom `json` type:
```java
public class CustomPdo {
    ....
    @Type(type = "json")
    private Map<String, Object> instanceVariables;
```

typedefs are defined on a package level:
```java
@TypeDefs({
        @TypeDef(name = "json", typeClass = JsonType.class)
})
package custompackage;
...
```

Actual Results
===========

While generating the schema from the pdo we get:
```sql
-- Tables
CREATE TABLE custom_pdo (
    -- should be json
    instance_variables uuid
);
```

Expected Results
==========
```sql
CREATE TABLE custom_pdo (
    instance_variables json
);
```

Any ideas?

**Comment by vladmihalcea** [comment]
Try with a custom Dialect like this one:

````
public class PostgreSQL10JsonDialect
        extends PostgreSQL10Dialect {
  
    public PostgreSQL10JsonDialect() {
        super();
        this.registerHibernateType(
            Types.OTHER, JsonNodeBinaryType.class.getName()
        );
    }
}
````

**Comment by tfactor2** [comment]
Am I right that then any non-standard java sql type (`java.sql.Types.Other`) will be mapped to `jsonb`?
So it would be impossible to have some tables with columns mapped to `json` and others to `jsonb`.

**Comment by vladmihalcea** [comment]
Actually, there's a much easier way. Use `columnDefinition` and it  should be fine:

    @Type(type = "json")
    @Column(columnDefinition = "jsonb")
    private Map<String, Object> instanceVariables;

There's no need to use the `Dialect` for that.

**Comment by tfactor2** [comment]
Indeed, thanks!
