### ISSUE TITLE
Issue with two arrays of different type

### ISSUE THREAD

**Issue by mattpal** [vladmihalcea/hibernate-types#384]
Hi, I'm using hybernate-types-43 and running into an issue with having an array of type UUID **and** and array of type varchar.

If I just have the varchar array it works fine, but if I add the uuid array I get an error about trying to convert the varchar array in PG to uuid array.   

```
@TypeDef(name = "list-array", typeClass = ListArrayType.class)
public class CustomerList extends GeneratedIDResource {
    ...
    @Type(type = "list-array")
    @Column(name = "tags", columnDefinition = "uuid[]")
    private List<UUID> tags;

    @Type(type = "list-array")
    @Column(name = "statuses", columnDefinition = "varchar[]")
    private List<String> statuses;
```

With just the ```statuses``` array it works fine, but adding the ```tags``` array breaks statuses.

Is this supported?

**Comment by vladmihalcea** [comment]
It can surely be supported. There are two ways to do it:

1. You can do it yourself and provide a Pull Request with the fix, and I will review it when I have some time.
2. I could do it via [consulting](https://vladmihalcea.com/consulting/) and integrate it as soon as I fix it.

**Comment by mattpal** [comment]
Okay, so just to confirm, it is not currently supported right?  Also if I were to do that myself, any tips on what class to look at?

Thanks

**Comment by vladmihalcea** [comment]
Try debugging the `ListArrayType` and see why it's working for `String` and not for the `UUID`.

**Comment by vladmihalcea** [comment]
Closed as no analysis was provided.
