### ISSUE TITLE
While reading from DB, skip the extra fields in JSON(TolerantReader)

### ISSUE THREAD

**Issue by sann3** [vladmihalcea/hibernate-types#395]
Hi,
How to skip the extra fields(TolerantReader) in JSON while converting to Java object ?

In ObjectMapper, we pass FAIL_ON_UNKNOWN_PROPERTIES as false. is there a way to do this in this lib ?

https://martinfowler.com/bliki/TolerantReader.html

**Comment by vladmihalcea** [comment]
You can customize the `ObjectMapper` as explained in [this article](https://vladmihalcea.com/hibernate-types-customize-jackson-objectmapper/). That way, you can surely achieve your goal.
