### ISSUE TITLE
Search by json field in MySQL

### ISSUE THREAD

**Issue by mas15** [vladmihalcea/hibernate-types#396]
If you used MySQL, is it possible to search for the entity using JSON field? For example, in your example with a Location as a JSON field:
```
INSERT INTO event (location, id)
VALUES ('{"country":"Romania","city":"Cluj-Napoca"}', 1)
```
can you search just by a city?

**Comment by vladmihalcea** [comment]
You can use a native SQL query for that. Check out the [JSON module of my High-Performance SQL video course](https://vladmihalcea.teachable.com/p/high-performance-sql-online?coupon_code=HPSQLV150OFF) for more details.
