### ISSUE TITLE
PostgreSQLEnumType#sqlTypes() should always return Types.VARCHAR

### ISSUE THREAD

**Issue by pglizniewicz** [vladmihalcea/hibernate-types#399]
`PostgreSQLEnumType` does not override `EnumType#sqlTypes()`, what means, it will return a value based on`EnumType#enumValueConverter`, which is never used by `PostgreSQLEnumType`. `enumValueConverter` is chosen based on what is set in the `@Enumerated`, so to make it work one have to annotate a property with both ` @Type( type = "pgsql_enum" )` and `@Enumerated(EnumType.STRING)` or it will default to @Enumerated(EnumType.ORDINAL). This feels redundant, since the both annotations define a type mapping and having to specify `@Enumerated(EnumType.STRING)` is just a workaround for the wrong default.

**Comment by vladmihalcea** [comment]
Makes sense. Ill check it out when I have some time.

**Comment by vladmihalcea** [comment]
Fixed.
