### ISSUE TITLE
Json Fields don't allow distinct keyword in hql queries

### ISSUE THREAD

**Issue by SupaMario123** [vladmihalcea/hibernate-types#400]
Hello Vlad, 

first i want to thank you for providing this awesome package!

But i am facing a problem with it, and i am not pretty sure how to fix it. When i have multiple Joins in my JPA Repository, i have duplicates inside my resultset. When i use the distinct option in the select part i get the following error:

<img width="992" alt="Bildschirmfoto 2022-03-03 um 13 44 08" src="https://user-images.githubusercontent.com/33687577/156567148-d5f754f8-6581-4dd9-9211-8d4a7c2d425e.png">

The query i execute:
`
    @Query("SELECT distinct training " +
            "FROM Training training LEFT JOIN training.exercises exercises " +
            "WHERE training.complete = true " +
            "AND training.language = :lang AND " +
            " AND " +
            "lower(training.name) like lower(concat('%', :input,'%')) OR lower(exercises.name) like lower(concat('%', :input,'%'))" +
            "OR lower(training.description) like lower(concat('%', :input,'%')) OR lower(exercises.description) like lower(concat('%', :input,'%')) " +
            " ")
    List<Training> searchTrainings(@Param("input")String input, Pageable pageable,@Param("lang")Language lang);`

Because of the json fields in database, the distinct keyword doesnt work in queries. :-/

It would be really awesome, if you can give me any idea of how to fix this problem. Because i am really stuck. 
If you have any advice i could try to fix it myself, but i really have no idea how to approach this problem.

**Comment by vladmihalcea** [comment]
I've never seen this issue, so I don't know what the problem is. Try to extra the query that gets executed and ask the question on the PostgreSQL forum using the SQL query, the tables, and the data you have. They surely know how to help you with this issue.
