### ISSUE TITLE
SQLExtractor returning query with distinct when QueryHints.PASS_DISTINCT_THROUGH is false

### ISSUE THREAD

**Issue by lucasoares** [vladmihalcea/hibernate-types#404]
Hello.

I'm using the hibernate types to get the SQL query generated by this code:
```
    TypedQuery<Interaction> query =
        this.entityManager
            .createQuery(
                "select distinct i from Interaction i left join fetch i.tags where i.interactionId = :interactionId",
                Interaction.class)
            .setParameter("interactionId", interactionId)
            .setHint(QueryHints.PASS_DISTINCT_THROUGH, false);

    String queryString = SQLExtractor.from(query);
    System.out.println(queryString);
```

For some reason the queryString contains the `distinct` keyword but it should not since the PASS_DISTINCT_THROUGH with `false` is a directive to Hibernate itself and not to the query generation:
```
select distinct interactio0_.interaction_id as interact1_10_0_, tags1_.interaction_id as interact1_1_1_, (... rest of the query)
```

Dependencies:

```
hibernate-core - 5.6.5.Final
google-cloud-spanner-hibernate-dialect - 1.5.3
hibernate-types-55 - 2.14.0
```
I also tried with hibernate 5.5.9.Final and dialect 1.5.2 but the result is the same.
This also happens with hibernate-types-52.

I'm missing something? I'm interpreting the QueryHints.PASS_DISTINCT_THROUGH parameter correctly? Only few weeks working with Hibernate but this seems to be an issue.

Thanks.

**Comment by vladmihalcea** [comment]
This is a Hibernate ORM limitation. The `SQLExtractor` fetches the SQL query as provided by the JPQL query plan. However, during execution, there's an additional `pre-processing` phase which removes the `DISTINCT` keyword.

Hence, the SQL query changes. Therefore, I don't see how this could be solved without issuing an additional query execution.
