### ISSUE TITLE
Parse Json from database to JsonNode encoding

### ISSUE THREAD

**Issue by mfvoid** [vladmihalcea/hibernate-types#41]
<dependency>
    <groupId>com.vladmihalcea</groupId>
    <artifactId>hibernate-types-52</artifactId>
    <version>2.2.2</version>
</dependency>

@Entity
@TypeDef(
        name = "jsonb-node",
        typeClass = JsonNodeStringType.class
)
public class Test implements Serializable {
	@Type(type = "jsonb-node")
	@Column(columnDefinition = "json")
	private JsonNode data;
	…
}

Hello, 
First of all congratulations for your work.
I have a problem with the charset when I get the data from the database, the data is stored with utf-8 but when it is read and then passed to JsonNode the encoding is not utf-8.
Is there any way to say that in reading the encoding is utf-8?

thanks

**Comment by vladmihalcea** [comment]
As long as the JDBC Driver uses UTF-8, just like the DB, you should be tine. You can also customize the Jackson ObjectMapper as explained in the articles provided in the README file.
