### ISSUE TITLE
Add support for MariaDB

### ISSUE THREAD

**Issue by marccollin** [vladmihalcea/hibernate-types#410]
I see support for mysql, I know json seem different betwen mariadb and mysql but is there any support for mariadb

**Comment by vladmihalcea** [comment]
Currently, the framework is not tested with MariaDB, so it might or might not work with it.

However, if you need support for MariaDB, there are two ways to achieve your goal:

- having the source code, you can add the support yourself and send a Pull Request that I could review when I have some time 
- I could add support for it via consulting in case your company wants to get this done sooner than later

**Comment by Dokkabei97** [comment]
I'm using mariadb and it works well.

environment
 - spring boot 2.7.0
 - hibernate 5.6.9
 - maraiadb 10.6.7

```java
@Entity
@TypeDef(name = "json", typeClass = JsonStringType.class) // JsonType.class or JsonStringType.class Both work well
public class Calendar extends AbstractEntity {

    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    @Type(type = "json")
    @Column(name = "data", columnDefinition = "longtext")
    private Map<String, Object> data = new HashMap<>();
}

```
```yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
```

**Comment by vladmihalcea** [comment]
@Dokkabei97 Thanks for your confirmation. 

I'm glad it works!
