### ISSUE TITLE
Issue with 2.15.0 upgrade

### ISSUE THREAD

**Issue by benstpierre** [vladmihalcea/hibernate-types#418]
I switched to hibernate 2.15.0 after seeing your post on LinkedIn but noticed the following error then trying to build.

```
Blocked mirror for repositories: [releases.java.net (http://maven.java.net/content/repositories/releases/, default, releases+snapshots), shapshots.java.net (http://maven.java.net/content/repositories/snapshots/, default, releases+snapshots), jvnet-nexus-staging (http://maven.java.net/content/repositories/staging/, default, releases+snapshots), netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans, default, releases)]

Since Maven 3.8.1 http repositories are blocked.

Possible solutions:
- Check that Maven settings.xml does not contain http repositories
- Check that Maven pom files not contain http repository http://maven.java.net/content/repositories/releases/
- Check that Maven pom files not contain http repository http://maven.java.net/content/repositories/snapshots/
- Check that Maven pom files not contain http repository http://maven.java.net/content/repositories/staging/
- Check that Maven pom files not contain http repository http://bits.netbeans.org/nexus/content/groups/netbeans
- Add a mirror(s) for http://maven.java.net/content/repositories/releases/, http://maven.java.net/content/repositories/snapshots/, http://maven.java.net/content/repositories/staging/, http://bits.netbeans.org/nexus/content/groups/netbeans that allows http url in the Maven settings.xml
- Downgrade Maven to version before 3.8.1 in settings

```
Simply be upgrading to the new release this error pops up...

**Comment by benstpierre** [comment]
I downgraded to Maven 3.6.3 and confirmed it works around this issue.  I also made a blank maven project and added only your library and was able to reproduce.

**Comment by vladmihalcea** [comment]
The library is available via Maven Central, and it supports HTTPs:

https://repo1.maven.org/maven2/

Why do you use Maven.java.net for? That's not Maven Central.

**Comment by benstpierre** [comment]
Hi Vlad I am pretty sure your hibernate-types pom.xml is referencing some http repositories.  Our dev team has been trying to work around this all morning.  The only way we could get it working was to add a dummy  mirror in settings.xml.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/1399854/162234443-79738578-2e54-45b2-9e8b-42cb9e72def2.png">
