### ISSUE TITLE
Remove warning generated on startup "Type [org.hibernate.type.CustomType@6142b9dd] defined no registration keys; ignoring"

### ISSUE THREAD

**Issue by Bas83** [vladmihalcea/hibernate-types#427]
In our Spring Boot application (2.6.6), after updating Hibernate-Types-55 from 2.14.1 to 2.15.1 we are getting the following warning on startup:

`Type [org.hibernate.type.CustomType@6142b9dd] defined no registration keys; ignoring`

On the logger `org.hibernate.type.BasicTypeRegistry`

However, we're not creating any custom types, we're only using `DecimalArrayType` which indeed doesn't seem to have these registration keys.

We have this definition on 2 Entity classes:

```
@TypeDefs({
    @TypeDef(
        name = "big-decimal-array",
        typeClass = DecimalArrayType.class
    )
})
```

And then also a custom postgres dialect:

```
import com.vladmihalcea.hibernate.type.array.DecimalArrayType;
import java.sql.Types;
import org.hibernate.dialect.PostgreSQL95Dialect;

public class PostgreSQL95CustomDialect extends PostgreSQL95Dialect {

    public PostgreSQL95CustomDialect() {
        super();
        // this is not super extendible because now ALL arrays in custom queries are treated as BigDecimal arrays.
        this.registerHibernateType(Types.ARRAY, DecimalArrayType.class.getName());
    }
}
```

Are we doing anything wrong or is this an issue in the library?

**Comment by Bas83** [comment]
I just put a breakpoint on the line that actually throws the exception and it seems to be about the type `com.vladmihalcea.hibernate.type.basic.NullableCharacterType`

**Comment by Bas83** [comment]
I just debugged, in the previous version this type `com.vladmihalcea.hibernate.type.basic.NullableCharacterType` was never registered in the BasicTypeRegistry, but now it is. Thus causing the warning there.

It is indeed being registered in the `HibernateTypesContributors` at the line `        typeContributions.contributeType(NullableCharacterType.INSTANCE, new String[0]);`

**Comment by vladmihalcea** [comment]
Indeed, the issue can be replicated with the existing test cases, so I'll investigate it when I have some time. In the meanwhile, you can simply ignore it as it won't affect the functionality of your application.

**Comment by vladmihalcea** [comment]
Fixed.
