### ISSUE TITLE
Batch sequence generation broken on H2 2.x

### ISSUE THREAD

**Issue by marschall** [vladmihalcea/hibernate-types#428]
Due to https://github.com/h2database/h2database/issues/3483 batch sequence generation is broken on versions 2.x of H2.

There are two possible fixes:

We could special case the H2 dialect and use this query

```sql
SELECT NEXT VALUE FOR sequenceName
  FROM SYSTEM_RANGE(1, ?);
```

Or we could simplify / change the default query to

```sql
WITH RECURSIVE T(N) AS (
  SELECT 1
   UNION ALL
  SELECT N + 1
    FROM T
   WHERE N < ?
)
SELECT NEXT VALUE FOR sequenceName
  FROM T;
```

**Comment by vladmihalcea** [comment]
Thanks for spotting it. Let's change the default query. Would you like to send a Pull Request with the fix?

**Comment by marschall** [comment]
Yes, I can do a PR.

**Comment by vladmihalcea** [comment]
Looking forward to it

**Comment by vladmihalcea** [comment]
Thanks, I integrated it.
