### ISSUE TITLE
Hibernate 6, postgres and jsonb columns no longer need JsonBinaryType

### ISSUE THREAD

**Issue by Kurru** [vladmihalcea/hibernate-types#434]
Hibernate 6, postgres and jsonb columns.

In the process of updating to Hibernate 6, we discovered that we no longer seem to use `JsonBinaryType` for our `@Type` defs anymore. `JsonType` is sufficient.  

Perhaps this documentation for postgres should be updated if this special handling is no longer required?

> PostgreSQL
> You should use this JsonBinaryType to map both jsonb and json column types.
> 
> For more details, check out [this article](https://vladmihalcea.com/how-to-map-json-objects-using-generic-hibernate-types/).

**Comment by vladmihalcea** [comment]
Fixed by [this commit](https://github.com/vladmihalcea/hibernate-types/commit/36a17693fcb473198793857816324b7c3c351493).

**Comment by Kurru** [comment]
Thanks! We also found that `JsonType` worked as expected for H2 db (used in tests), but the `JsonBinaryType `had the unexpected behavior of wrapping the string in `"` and also escaping all inner `"`

i.e. json that should be 

```
{"name": "joe"}
```

Turned into
```
"{\"name\": \"joe\"}"
```

Not sure if this happened on the insertion side or the selecting side of the cycle though.
