### ISSUE TITLE
JSON Type

### ISSUE THREAD

**Issue by RealMarvn** [vladmihalcea/hibernate-types#437]
Hi,
I want to wrap a Pojo JSON in my MariaDB Database via your Hibernate Types framework.
I have huge issues regarding your @Type annotation.
```
package dev.marvn.interception.db.entitys

import com.vladmihalcea.hibernate.type.json.JsonType
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import org.hibernate.annotations.Type


@Entity
@Table(name = "support_data")
data class SupportDataEntity(

    @Id
    @Column(name = "server_id")
    var serverId: Long,

    @Type(JsonType.class)
    @Column( columnDefinition = "json", name = "support_data")
    var supportData: Long,
)


data class SupportData(
    var test: Long,
    var list: MutableList<Long>,
)```

This is how my POJO looks like. I ve got an error at @Type: "This annotation is not applicable to target 'value parameter'".
I don't know what to do next. How can I pass a Support Data Object as JSON into this column?
Thanks for your help in advance.

**Comment by vladmihalcea** [comment]
I've never tested it for MariaDB, so there's no guarantee that it will work.

And, I don't know what that exception is, but you can debug the MySQL integration tests in the GitHub repository and compare the execution to yours.

**Comment by RealMarvn** [comment]
I guess it should work of the Hibernate query which will be generated.
The problem is the @Type annotation. There is no @Type annotation by hibernate-types only by FasterXML and Hibernate itself. I used the Hibernate one and got this:
<img width="712" alt="Bildschirmfoto 2022-05-15 um 14 00 42" src="https://user-images.githubusercontent.com/67916561/168471663-9228005a-6b6b-4212-a3c3-a07f6afa7136.png">
:

**Comment by vladmihalcea** [comment]
Looks like you mixed the hibernate-types dependencies.

If you are using Hibernate 6, use the `hibernate-types-6` dependency. For Hibernate 5.5 or newer use the `hibernate-types-55` dependency. Check out the README file for more details.

**Comment by RealMarvn** [comment]
I am using the correct Hibernate Types dependency. I am using Hibernate 6 and Hibernate Types 6.

**Comment by vladmihalcea** [comment]
Then, it must be a Kotlin issue. The project is only tested with Java, and you can see how to use that annotation in the [integration tests folder](https://github.com/vladmihalcea/hibernate-types/tree/master/hibernate-types-60/src/test/java/com/vladmihalcea/hibernate/type/json).
