### ISSUE TITLE
Add support for the PostgreSQL hstore type

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#44]

**Comment by nstdio** [comment]
@vladmihalcea can I take this?

**Comment by vladmihalcea** [comment]
Sure thing. Thanks for taking care of it.

**Comment by vladmihalcea** [comment]
Fixed by [this commit](https://github.com/vladmihalcea/hibernate-types/commit/1eca8e0c3f5dec76cbe07c07d6313c1dd7629e2c).
