### ISSUE TITLE
Add the amazing HibernateRepository

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#444]
As explained in [this article](https://vladmihalcea.com/best-spring-data-jparepository/).

**Comment by ecopsdee** [comment]
This is the masters student that messaged you on linkedIn. Has this been assigned yet?

**Comment by vladmihalcea** [comment]
No, this issue hasn't been assigned.

**Comment by ecopsdee** [comment]
Should this be added only in version 6?

**Comment by vladmihalcea** [comment]
No. It should be added to all versions

**Comment by vladmihalcea** [comment]
Cool! Looking forward to it

**Comment by ecopsdee** [comment]
done

**Comment by vladmihalcea** [comment]
Fixed.
