### ISSUE TITLE
Add PostgreSQLCITextType to TypeContributor

### ISSUE THREAD

**Issue by efrench-novi** [vladmihalcea/hibernate-types#445]
I like the addition of the builtin TypeContributor, but I noticed the PostgreSQLCITextType type was not added. Not sure if it was for a specific reason or an oversight.

**Comment by vladmihalcea** [comment]
I remember some Types were triggering some errors when bootstrapping all of them. Try adding it and run the tests or run it locally on your project and see if it works.

**Comment by efrench-novi** [comment]
I had written my own TypeProvider before using `PostgreSQLCITextType.INSTANCE` and had no issues.  I just added it along with yours using the following code and it works without any issues. Using JDK 17 - have not tried with other JDK's.


```java
public class NoviTypeContributor implements TypeContributor {
    @Override
    public void contribute(TypeContributions typeContributions, ServiceRegistry serviceRegistry) {
        contributeType(typeContributions, PostgreSQLCITextType.INSTANCE);
    }

    //
    // copied from https://github.com/vladmihalcea/hibernate-types HibernateTypesContributor
    //
    private void contributeType(TypeContributions typeContributions, BasicType type) {
        typeContributions.contributeType(type);
    }

    private void contributeType(TypeContributions typeContributions, UserType type) {
        if (type instanceof ImmutableType immutableType) {
            typeContributions.contributeType(immutableType, immutableType.getName());
        } else {
            typeContributions.contributeType(type, type.getClass().getSimpleName());
        }
    }
}
```

**Comment by ecopsdee** [comment]
@efrench-novi i would like to email you. would you mind help me to resolve some configuration issues. your assistance would be helpful. we could connect via twitter or instagram.

**Comment by vladmihalcea** [comment]
Fixed for Hibernate 5 and 4 modules. The Hibernate 6 module fails if the `PostgreSQLCITextType` is auto-registered.
