### ISSUE TITLE
Update Readme to include information regarding building the project

### ISSUE THREAD

**Issue by pavelgordon** [vladmihalcea/hibernate-types#447]
That this project requires toolchains setup with JDK 6 and 8 pointing to the local JDK of a contributor:
1. create toolchains.xml file in .m2 directory(e.g. /Users/pavelgordon/.m2/toolchains.xml)
2. Content of file similar to https://gist.github.com/pavelgordon/23c74063c65570aca5366294c13cbfb4(e.g. JDK located in /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk)

**Comment by vladmihalcea** [comment]
I'll add a link to [this article](https://vladmihalcea.com/maven-and-java-multi-version-modules/), as it explains how to use Maven Toolchains.

**Comment by vladmihalcea** [comment]
Fixed.
