### ISSUE TITLE
Add support for JavaMoney (JSR 354) with the MonetaryAmountType

### ISSUE THREAD

**Issue by piotrooo** [vladmihalcea/hibernate-types#450]
In response to https://github.com/JavaMoney/jsr354-ri/issues/185#issuecomment-1146796277 maybe is a good idea to create issue here.

I think handling JavaMoney could be very useful.

This feature is in Jadira already (https://github.com/JadiraOrg/jadira/tree/master/usertype.core/src/main/java/org/jadira/usertype/moneyandcurrency/moneta) but seems it's looks like a little bit stale.

**Comment by vladmihalcea** [comment]
It's a good idea, indeed. Try creating a MonryType and some integration test to prove it and send me a Pull Request when it's done.

**Comment by piotrooo** [comment]
I think the very first implementation, should handle two concatenated columns. First one is for amount (sql decimal type), second for currency (sql varchar).

```
@Columns(columns = {@Column(name = "amount"), @Column(name = "currency")})
```

What do you think?

**Comment by vladmihalcea** [comment]
Thanks, I merged it.
