### ISSUE TITLE
@TypeDef removed from the hibernate-core:6.1.1.Final

### ISSUE THREAD

**Issue by kth13** [vladmihalcea/hibernate-types#452]
@vladmihalcea your library has been pretty useful. Thanks for that. I tried upgrading my application to hibernate-core:6:1:1.Final where they have totally removed the @typedef annotation.
I having an annotation like this @TypeDef(name = "list-array", typeClass = ListArrayType::class) and a reference like this @Type(type = "list-array") @Column(name = "disabilities", columnDefinition = "text[]"). what should be the alternative if this is not supported anymore

**Comment by vladmihalcea** [comment]
For Hibernate 6, use this instead:

```
@Type(ListArrayType.class)
@Column(
	name = "date_values",
	columnDefinition = "date[]"
)
private List<Date> dateValues;
```
