### ISSUE TITLE
ClassCastException?

### ISSUE THREAD

**Issue by TMSantos** [vladmihalcea/hibernate-types#46]
Hi there!
I'm trying to use your types but when I build it I get this exception:

`msc.service.StartException in service jboss.persistenceunit."server-api.war#dgo": javax.persistence.PersistenceException: [PersistenceUnit: db-test] Unable to build Hibernate SessionFactory
server-api_1        |   at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:179)
server-api_1        |   at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:121)
server-api_1        |   at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:667)
server-api_1        |   at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:193)
server-api_1        |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
server-api_1        |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
server-api_1        |   at java.lang.Thread.run(Thread.java:748)
server-api_1        |   at org.jboss.threads.JBossThread.run(JBossThread.java:320)
server-api_1        | Caused by: javax.persistence.PersistenceException: [PersistenceUnit: dgo] Unable to build Hibernate SessionFactory
server-api_1        |   at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:954)
server-api_1        |   at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:882)
server-api_1        |   at org.jboss.as.jpa.hibernate5.TwoPhaseBootstrapImpl.build(TwoPhaseBootstrapImpl.java:44)
server-api_1        |   at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:161)
server-api_1        |   ... 7 more
server-api_1        | Caused by: org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.json.JsonBinaryType
server-api_1        |   at org.hibernate.type.TypeFactory.type(TypeFactory.java:139)
server-api_1        |   at org.hibernate.type.TypeFactory.byClass(TypeFactory.java:109)
server-api_1        |   at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:112)
server-api_1        |   at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:416)
server-api_1        |   at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:398)
server-api_1        |   at org.hibernate.mapping.Property.isValid(Property.java:225)
server-api_1        |   at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:595)
server-api_1        |   at org.hibernate.mapping.RootClass.validate(RootClass.java:265)
server-api_1        |   at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:329)
server-api_1        |   at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:443)
server-api_1        |   at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:879)
server-api_1        |   ... 9 more
server-api_1        | Caused by: java.lang.ClassCastException: org.hibernate.annotations.common.reflection.java.JavaXProperty cannot be cast to org.hibernate.annotations.common.reflection.XProperty
server-api_1        |   at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.setParameterValues(JsonTypeDescriptor.java:58)
server-api_1        |   at com.vladmihalcea.hibernate.type.json.JsonBinaryType.setParameterValues(JsonBinaryType.java:66)
server-api_1        |   at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:152)
server-api_1        |   at org.hibernate.type.TypeFactory.type(TypeFactory.java:135)
server-api_1        |   ... 19 more
`

Not sure it's a bug on your lib or something I'm missing, any help?
Thanks

**Comment by vladmihalcea** [comment]
Try to debug it and see what the problem is. It could be that JBoss does not provide the right Hibernate dependencies, especially the Hibernate-common-annotations one. 

If you can replicate it with a test case, open a new issue and send the test case as a Pull Request.

**Comment by TMSantos** [comment]
That's something that came to my mind also, ok thank you for your help! I'll try to debug more deeply. Have a nice day

**Comment by vladmihalcea** [comment]
Sure thing. Have a nice day too.

**Comment by oisti** [comment]
Hi!

I'm getting the same ClassCastException on my Wildfly 14.0.1.Final regardless of types.
Dependencies provided by Wildfly 14.0.1.Final are:
hibernate-core 5.3.6.Final
hibernate-commons-annotations 5.0.4.Final

Thanks

**Comment by vladmihalcea** [comment]
Check out the previous comments.

**Comment by cec** [comment]
Hi @TMSantos  and @oisti  did you guys manage to solve this?

It's been haunting me for almost two whole days now...

**Comment by vpriscan** [comment]
This is haunting me too on Wildfly 17.0.1.Final.
Has anyone found a solution for this?

**Comment by vladmihalcea** [comment]
@vpriscan If you find a solution, you should post it here to help others in the future. I haven't used JBoos o Wildfly for a very long time, so I cannot help you with this.

**Comment by vpriscan** [comment]
@vladmihalcea @TMSantos @oisti @cec Okay I solved it.

1. For `hibernate-commons-annotations` dependency, use `provided` scope if you are using Maven, or `compileOnly` configuration if you are using Gradle. You can also just remove that dependency declaration altogether, because you probably don't need it for compilation.
Example for Maven:
```
        <dependency>
            <groupId>org.hibernate.common</groupId>
            <artifactId>hibernate-commons-annotations</artifactId>
            <version>5.0.5.Final</version>
            <scope>provided</scope>
        </dependency>
```

2. Add `org.hibernate.commons-annotations` module to Dependencies in  your **MANIFEST.MF**:
```
Dependencies: org.hibernate.commons-annotations
```
You can also make Maven add that for you, for example using the maven-ejb-plugin:
```
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ejb-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Dependencies>
                                org.hibernate.commons-annotations
                            </Dependencies>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by lennertdefeyter** [comment]
Fyi, this is the solution that I found to work:
https://stackoverflow.com/questions/52290683/hibernate-types-and-jboss-compatibility-issue

**Comment by vladmihalcea** [comment]
@Thanks @lennertdefeyter for pointing it out.

**Comment by mmonge** [comment]
Thank you @lennertdefeyter 😃️ !, in my case for Wildfly the Tomasz answer is the right one. I copied the direct link for other Wildfly pals to solve it quickly.

Direct link: https://stackoverflow.com/a/59786102
