### ISSUE TITLE
com.vladmihalcea.hibernate.type.json.JsonStringType cannot be cast to org.hibernate.type.CollectionType

### ISSUE THREAD

**Issue by zhaocx-py** [vladmihalcea/hibernate-types#460]
@TypeDef(name = "json", typeClass = JsonStringType.class)

@Type(type = "json")
@Column(columnDefinition = "json" )
private List<Long> trainIds = new ArrayList<>();

qTrainScheme.trainIds.size().gt(0): qTrainScheme.trainIds.size().lt(1)

**trainSchemeRepository.findAll(predicate, pageRequest);**

**Comment by vladmihalcea** [comment]
Check out [this test case](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-55/src/test/java/com/vladmihalcea/hibernate/type/json/PostgreSQLJsonListPojoTest.java). It works like a charm. Then, compare my test to yours, and see where they differ.

**Comment by zhaocx-py** [comment]
@vladmihalcea  
It works when I query the data directly, but when I use the QueryDSL framework with List<Long> trainIds as a conditional query, that is, queries based on whether there is data in IDS as a conditional query, like this
 jpaQueryFactory    *query.where(qTrainScheme.trainIds.size().gt(0));*

**Comment by vladmihalcea** [comment]
Sounds like a QueryDSL issue then
