### ISSUE TITLE
MonetaryAmountType throws NullPointerException when reading a null column value

### ISSUE THREAD

**Issue by ugrave** [vladmihalcea/hibernate-types#465]
The MonetaryAmountType  use the ResulSet.wasNull to check for null.
Problem is that at least one getter must called before.

From javadoc og `ResultSet.wasNull`:
`Note that you must first call one of the getter methods on a column to try to read its value`

I attached a demo with two use cases.
One read only the Money value there other one reads the hole entity.
When reading only the money value the npe is thrown. Only whan an additional column was read before it works without exception.

[demo.zip](https://github.com/vladmihalcea/hibernate-types/files/9242622/demo.zip)

**Comment by vladmihalcea** [comment]
I don't understand the issue. There is a integration test in repository you could use to add a new test that replicates your issue.

Not only that it's easier to isolate the problem that way, but, after the fix is done, there is already a test to prove the fix.

**Comment by ugrave** [comment]
Hi,

added a test case which reproduce the error. Found out that this always happend if the salery is null.

https://github.com/ugrave/hibernate-types/blob/96d985b2609c2fcec3436f4f666c03569c61e274/hibernate-types-55/src/test/java/com/vladmihalcea/hibernate/type/money/PostgreSQLMonetaryAmountTypeTest.java#L69

**Comment by ugrave** [comment]
A fix could be to check the amaout value if it is not null instead of the `rs.wasNull()`.
Or first read the amount column and the check with `rs.wasNull()`.

**Comment by vladmihalcea** [comment]
Thanks @ugrave for the tests and the investigation. I'll check it out when I have some time.

In the meanwhile, if you want, you could try to provide a Pull Request with a fix proposal.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by RoarBjur** [comment]
When will 2.17.2 be released with this fix? This is a major problem for my usage of the MonetaryAmountType class

**Comment by vladmihalcea** [comment]
@RoarBjur it depends on how much your company is willing to pay. For free, it's going to be ready when it's ready.

**Comment by RoarBjur** [comment]
@vladmihalcea Thank you for your reply. I am not in a hurry right now, but will contact you if necessary

**Comment by vladmihalcea** [comment]
There is another issue that I plan to add to 2.17.2, so it all depends on when I have the time to get that done.
