### ISSUE TITLE
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonSerializer

### ISSUE THREAD

**Issue by zenonwch** [vladmihalcea/hibernate-types#466]
I just updated from 2.17.0 to 2.17.1 and got 
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonSerializer

Got the issue on hibernate-types-52 and hibernate-types-55.

**Comment by vladmihalcea** [comment]
While previously, most dependencies were optional, starting with 2.17.1, they are all optional, as explained in the [docs](https://github.com/vladmihalcea/hibernate-types#optional-maven-dependencies).

So, you need to add the optional dependencies that you'd like to use, which will allow you to control their versions.
