### ISSUE TITLE
Add continuous Integer solution for YearMonthType

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#47]
As explained in [this article](https://blog.jooq.org/2016/10/05/why-you-should-design-your-database-to-optimise-for-statistics/), a continuous Integer solution could be both more compact and get a better chance of an index hit when doing range queries.

**Comment by lukaseder** [comment]
Cool, thanks!

> get a better chance of an index hit when doing range queries.

Note, without continuous integers (i.e. an encoding that reflects the uniform distribution of the "year month" data type), you might even get "index hits" when you shouldn't. It can go both ways.

**Comment by vladmihalcea** [comment]
Fixed
