### ISSUE TITLE
Add support for the JavaMoney (JSR 354) CurrencyUnit

### ISSUE THREAD

**Issue by piotrooo** [vladmihalcea/hibernate-types#473]
Hello @vladmihalcea!
I hope you're fine.

I come with another idea about extending types. We can add currency ISO-4217 codes.
It looks like:

```
@Column(name = "currency")
private CurrencyUnit currency;
```

What do you think? If you are interested in, I implemented almost everything what is needed.

Another question, I see you add Money handling for Hibernate versions >5, that is intentionally? Because I make implementation for all of Hibernate versions. If is, maybe pom's should be cleaned and removed Moneta dependency.

If it's ok, I can implement for all Hibernate versions >5.

**Comment by vladmihalcea** [comment]
Yes, please. The reason these Types are used on 5.2 or later is that it needs Java 8.

**Comment by piotrooo** [comment]
Sure. You can assign me to this issue.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks
