### ISSUE TITLE
Generify the Comparable type in the Range class

### ISSUE THREAD

**Issue by asdm90** [vladmihalcea/hibernate-types#478]
The generic type declaration for the Range class can be improved with wildcards like so:

Current declaraction:
`public final class Range<T extends Comparable> implements Serializable`

Possible enhancement:
`public final class Range<T extends Comparable<? super T>> implements Serializable`

This should remove a couple of IDE warnings about the use of generics in the class and should be backwards compatible.

**Comment by vladmihalcea** [comment]
Since you already investigate it, you could send a Pull Request with a change proposal. I'll investigate it afterward.

**Comment by vladmihalcea** [comment]
Fixed.
