### ISSUE TITLE
Question about the deleted "JSON type info missing for polymorphic collection" issue

### ISSUE THREAD

**Issue by klesun** [vladmihalcea/hibernate-types#480]
Hi. There was once an [#352](https://github.com/vladmihalcea/hibernate-types/issues/352) issue that asked about how to properly handle polymorphic jsonb collections. (I linked to it in a javadoc at my project back then)

The issue seems to be deleted, the [wayback machine](https://web.archive.org/web/20211028120806/https://github.com/vladmihalcea/hibernate-types/issues/352) says that the last comment was:

> Superseded by [#360](https://github.com/vladmihalcea/hibernate-types/issues/360)

The [#360](https://github.com/vladmihalcea/hibernate-types/issues/360) is sadly also deleted, guess it was superseded by some other issue as well.

What was the resolution of those issues? Where should we refer for the information on the matter?

___________________

I was using the approach I mentioned in [#352](https://github.com/vladmihalcea/hibernate-types/issues/352) of using `default` interface method `getType()`, but I have suspicion it interferes with [dirty check](https://github.com/vladmihalcea/hibernate-types/issues/138) mechanism.

**Comment by klesun** [comment]
Here is an MR related to the #352

https://github.com/vladmihalcea/hibernate-types/pull/353

**Comment by klesun** [comment]
And this seems to be related to the [#360](https://github.com/vladmihalcea/hibernate-types/issues/360)

[#361](https://github.com/vladmihalcea/hibernate-types/issues/361)

**Comment by vladmihalcea** [comment]
Last time I checked, [polymorphic JSON collections worked just fine](https://vladmihalcea.com/polymorphic-json-objects-hibernate/).

That issue was not needed.

**Comment by klesun** [comment]
ok, thanks

**Comment by vladmihalcea** [comment]
You're welcome.
