### ISSUE TITLE
The findAll method from the JpaRepository is an Anti-Pattern and the HibernateRepository should deprecate it

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#483]
The `findAll` method from the `JpaRepository` is a terrible anti-pattern as it allows you to fetch an entire database table with a single method call. Such methods have no purpose in a non-trivial application, so this method should be deprecated.

If you really want to fetch an entire database table, then you should do that explicitly with a JPQL call in the context where this is needed.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by ethanmills** [comment]
I don't think I agree that there are no valid usages of this in a non-trivial application. There are ~1.6M usages of this method on Github: https://github.com/search?l=Java&q=repository.findAll%28%29&type=Code

**Comment by vladmihalcea** [comment]
The article about this topic will be published tomorrow.
