### ISSUE TITLE
Timestamp vs ISO Date

### ISSUE THREAD

**Issue by vlad4800** [vladmihalcea/hibernate-types#489]
We have a property stored as Json in MariaDB 10.

The column definition is: 
```
    @Basic
    @Type(type = "json")
    @Column(columnDefinition = "json", name = "settings", nullable = true, insertable = true, updatable = true)
    public Settings getSettings() {
        return settings;
    }
```

The Settings class has a Date field:

```
private Date tokenExpiry;
```

When the Json is serialized in the DB, the `tokenExpiry` property is written as a unix timestamp instead of the ISO date format. All the other dates that do not use this library are stored correctly.

We also have a custom `hibernate.properties` file where we map our custom JsonProcessor class using the `hibernate.types.jackson.object.mapper` property.

Is this library using it's own rules when it comes to dates?

**Comment by vladmihalcea** [comment]
The `hibernate.types.jackson.object.mapper` property you are using should provide the library a custom `ObjectMapper` that serializes the timestamps differently, as explained by [this article](https://vladmihalcea.com/hibernate-types-customize-jackson-objectmapper/).

Try debugging the custom `ObjectMapper` to see why it's not working for you.

**Comment by vlad4800** [comment]
That's what we were doing. But due to a script error, the file was not included in the jar during the build so at runtime it was not used. I appologize for the distraction.
