### ISSUE TITLE
Migrate to java 9

### ISSUE THREAD

**Issue by alexeykip** [vladmihalcea/hibernate-types#49]
Good morning. I can't migrate my project to Java 9 because hibernate.types.52 is incorrect module name.
Do you plan to rename the packages?

**Comment by vladmihalcea** [comment]
Fixed by [this commit](https://github.com/vladmihalcea/hibernate-types/commit/ec22d7cd3f81b9e9bfcfbb39422edde54ec3f940).

**Comment by alexeykip** [comment]
It works. Thks

**Comment by vladmihalcea** [comment]
I released the version `2.3.2` with this fix. Soon, it should be available from Maven Central.
