### ISSUE TITLE
Add support for the PostgreSQL 'empty' range that's distinct from the (,) infinite range

### ISSUE THREAD

**Issue by nstdio** [vladmihalcea/hibernate-types#492]
When mapping PostgreSQL `empty` range we are creating `Range` objects which is actually unbounded from both sides. The created range has exact internal structure that `Range.integerRange("(infinity,infinity)")` would have.

Here is the quote from [documentation](https://www.postgresql.org/docs/current/rangetypes.html):

> ... 
Notice that the final pattern is empty, which represents an empty range (a range that contains no points).

So it'll be sensible to align with this semantics in Java as well.

Currently following test case test case fails:
```
    @Test
    public void emptyRangeWithEmptyKeyword() {
        Range<LocalDate> empty = Range.localDateRange("empty");

        assertFalse(empty.contains(LocalDate.MIN));
        assertFalse(empty.contains(LocalDate.now()));
        assertFalse(empty.contains(LocalDate.MAX));

        assertNull(empty.upper());
        assertNull(empty.lower());
    }
```

@vladmihalcea can you please assign this issue to me? I've already started working this.

**Comment by vladmihalcea** [comment]
Fixed.
