### ISSUE TITLE
Add support for querying by the embedded MonetaryAmount attributes

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hibernate-types#497]
This will allow us to run queries like the following one:

```
List<Salary> salaries = entityManager.createQuery("""
    select s 
    from Salary s 
    where s.salary.amount >= :amount
    """, Salary.class)
.setParameter("amount", amount)
.getResultList();
```

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by viktorvoltaire** [comment]
Hi @vladmihalcea 

I am running kotlin spring boot, with a simple JpaRepository, and since this fix im getting this error
```
org.springframework.orm.jpa.JpaSystemException: Calling setPropertyValues is illegal on on javax.money.MonetaryAmount because it's an immutable object!; nested exception is org.hibernate.HibernateException: Calling setPropertyValues is illegal on on javax.money.MonetaryAmount because it's an immutable object!
```
when running `save` on our repository. Like below 👇  I removed some stuff and renamed a few things. I can provide some more details if needed

```
@TypeDef(name = "monetary-amount-currency", typeClass = MonetaryAmountType::class, defaultForType = MonetaryAmount::class)
class AnEntity(
    id: UUID,
    @Columns(columns = [Column(name = "amount"), Column(name = "currency")])
    @Type(type = "monetary-amount-currency")
    var netPrice: MonetaryAmount,
....
```

```
    @Autowired
    private lateinit var repo: ARepo

    @Test
    fun `validate money is stored correctly in DB`() {
        val journeyId1 = randomUUID()
        repo.save(
            AnEntity(
                id = randomUUID(),
                netPrice = Money.of(5555, "SEK"),
            )
        )
.........
```

**Comment by vladmihalcea** [comment]
@viktorvoltaire Try to debug the problem and see why that Exception is thrown. 

Most likely, it's thrown from [this method](https://github.com/vladmihalcea/hibernate-types/blob/018a60a58a7565a709d0789e81586312e8a5f5db/hibernate-types-55/src/main/java/com/vladmihalcea/hibernate/type/ImmutableCompositeType.java#L364), but you will have to debug and see why that one got called in your case while the existing test cases in this repository work just fine.

Doing a comparative debug between your code and the integration tests in this repository will surely help you find the problem.

Looking forward to seeing what you found during your investigation.

**Comment by viktorvoltaire** [comment]
Tbh im not sure, prior to bumping to version `2.20.0` i end up here while debugging https://github.com/hibernate/hibernate-orm/blob/5.6.12/hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java#L265

Once bumping to version `2.20.0` i end up here while debugging https://github.com/hibernate/hibernate-orm/blob/5.6.12/hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java#L260 

Hence the `Calling setPropertyValues is illegal on on javax.money.MonetaryAmount because it's an immutable object!` exception. Not really sure how to proceed 🤔

**Comment by vladmihalcea** [comment]
Try to debug the [`PostgreSQLMonetaryAmountTypeTest`](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-55/src/test/java/com/vladmihalcea/hibernate/type/money/PostgreSQLMonetaryAmountTypeTest.java) and see why it works fine there.

**Comment by viktorvoltaire** [comment]
I guess its because `isComponentType()` was changed from false to true

**Comment by vladmihalcea** [comment]
According to the [Hibernate API spec](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/type/Type.html#isComponentType--), it should return `true`:

> boolean isComponentType()
> Return true if the implementation is castable to [CompositeType](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/type/CompositeType.html). 
> Essentially a polymorphic version of (type instanceof CompositeType.class). 
> A component type may own collections or associations and hence must provide certain extra functionality.
```

**Comment by viktorvoltaire** [comment]
> According to the [Hibernate API spec](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/type/Type.html#isComponentType--):
> 
> > boolean isComponentType()
> > Return true if the implementation is castable to [CompositeType](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/type/CompositeType.html).
> > Essentially a polymorphic version of (type instanceof CompositeType.class).
> > A component type may own collections or associations and hence must provide certain extra functionality.
> 
> Now, it could be a wrong assumption, but it's curious why it works in the official tests?
> 
> And, without it, you won't be able to query by its internal attributes.

Interesting, we are not working with EntityManager the same way you are, basically we are just calling an Interface that implements a JpaRepository, and then we run save on that. The types we use for MonetaryAmount is 

```
    add column amount numeric,
    add column currency text;
```

Other than that we have followed your guide https://vladmihalcea.com/monetaryamount-jpa-hibernate/ on how to implement it

**Comment by viktorvoltaire** [comment]
Could it be because hibernate is invoking merge, based on how we create the entity

**Comment by vladmihalcea** [comment]
It's not Hibernate, it's Spring then. Check out [this article](https://vladmihalcea.com/best-spring-data-jparepository/) about the Spring save anti-pattern.

**Comment by viktorvoltaire** [comment]
I will have a look when I have time, here is a bit more from the stacktrace. As you pointed out its `org.springframework.orm.jpa.SharedEntityManagerCreator` thats invoking it

```
Caused by: org.hibernate.HibernateException: Calling setPropertyValues is illegal on on javax.money.MonetaryAmount because it's an immutable object!
	at com.vladmihalcea.hibernate.type.ImmutableCompositeType.setPropertyValues(ImmutableCompositeType.java:365)
	at org.hibernate.type.TypeHelper.replaceAssociations(TypeHelper.java:260)
	at org.hibernate.event.internal.DefaultMergeEventListener.copyValues(DefaultMergeEventListener.java:476)
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:248)
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:318)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:172)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:70)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:829)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:816)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:311)
	at jdk.proxy2/jdk.proxy2.$Proxy187.merge(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:669)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
```

**Comment by viktorvoltaire** [comment]
I did some more testing, and by adding a version to the entity
```
    @Version
    val version: Long? = null,
```
makes the isNew true, causing the entityManager to run persist rather than merge
```
    if (this.entityInformation.isNew(entity)) {
      this.em.persist(entity);
      return entity;
    } else {
      return this.em.merge(entity);
    }
```

**Comment by vladmihalcea** [comment]
@viktorvoltaire I [changed the test cases](https://github.com/vladmihalcea/hibernate-types/commit/977e2d0add4f7e3f2ccba470fc80ffe132030073) to include `merge`, which also work fine when `merge` is called for detached entities.

The problem is, most likely, called by the Spring `save` anti-pattern, which calls `merge` for new/transient entities.

**Comment by viktorvoltaire** [comment]
Yeah you are right @vladmihalcea thanks for all the assist!

**Comment by vladmihalcea** [comment]
@viktorvoltaire You're welcome.
