### ISSUE TITLE
Add support for cast to proper JSON object which is part of some JPA hierarchy entities

### ISSUE THREAD

**Issue by roxana-bandac** [vladmihalcea/hibernate-types#503]
**Given a set of JPA entities which are included on a hierarchy using @DiscriminatorValue. Each JPA entity has it's own JSON Java Object.
When a JPQL query is written to get the List of some type of JSON Java Object with proper filter based on the TYPE of JPA Entity, it should return properly (cast) with the correct JSON Java Object. The filter of query is with TYPE IN (X, Y). The return type is List of an interface implemented by each JSON object.
One of the workarounds was to split the query for each type, where the output specifies clearly type of JSON object. 

Currently, the following error occurs for a such case:**

_

> Caused by: java.lang.IllegalArgumentException: The given string value: { " THE JSON
> 	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.fromString(ObjectMapperWrapper.java:52)
> 	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.fromString(JsonTypeDescriptor.java:106)
> 	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.wrap(JsonTypeDescriptor.java:164)
> 	at com.vladmihalcea.hibernate.type.json.internal.AbstractJsonSqlTypeDescriptor$1.doExtract(AbstractJsonSqlTypeDescriptor.java:34)
> 	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
> 	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
> 	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253)
> 	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243)
> 	at org.hibernate.loader.hql.QueryLoader.getResultRow(QueryLoader.java:457)
> 	at org.hibernate.loader.hql.QueryLoader.getResultColumnOrRow(QueryLoader.java:440)
> 	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:773)
> 	at org.hibernate.loader.Loader.getRowsFromResultSet(Loader.java:1042)
> 	at org.hibernate.loader.Loader.processResultSet(Loader.java:993)
> 	at org.hibernate.loader.Loader.doQuery(Loader.java:962)
> 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:352)
> 	at org.hibernate.loader.Loader.doList(Loader.java:2857)
> 	at org.hibernate.loader.Loader.doList(Loader.java:2839)
> 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2671)
> 	at org.hibernate.loader.Loader.list(Loader.java:2666)
> 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
> 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
> 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
> 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1412)
> 	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1565)
> 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533)
> 	at org.hibernate.query.Query.getResultList(Query.java:165)
> 	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:126)
> 	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
> 	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
> 	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
> 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:618)
> 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
> 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
> 	... 143 common frames omitted
> Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field 
> at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
> 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:843)
> 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1597)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1547)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:504)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1292)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
> 	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.fromString(ObjectMapperWrapper.java:50)
> 	... 181 common frames omitted

_

**Comment by vladmihalcea** [comment]
Frankly, I don't understand the context in which this issue can replicate.

So, the first step would be to add an integration test that replicates the issue.

The second step is to investigate it, find the problem, and the provides the fix that makes the test pass while not affecting the other tests.

Looking forward to seeing your Pull Request that fixes this issue.

**Comment by roxana-bandac** [comment]
We have more solutions, but maybe someday in the future the library could identify the proper class type of the json object. It’s a more complex case. I edited the description, was not clear enough. Sorry for unclarity.

**Comment by vladmihalcea** [comment]
It's still not clear. I'll close the issue and reopen only if a test case is provided.
