### ISSUE TITLE
Excluding null fields while saving a json

### ISSUE THREAD

**Issue by anmol1vw13** [vladmihalcea/hibernate-types#506]
Hi Vlad,
I'm using `hibernate-types-55` version `2.14.0`. 
To support persisting json data I've done the following 
- Defined a typedef  

```
@TypeDefs({
    @TypeDef(name = "json", typeClass = JsonType.class)
})
```
- Add a column definition to the field
```
@Column(name = "metadata", columnDefinition = "jsonb")
@Type(type = "json")
private Field field;
```
My concern here is that the field object has a lot of properties which are null by default and when the save happens, the key is persisted with null value. How can I exclude the keys with null values?

**Comment by vladmihalcea** [comment]
You can customize the JSON objet serialization, [like this](https://vladmihalcea.com/hibernate-types-customize-jackson-objectmapper/).

This allows you to save the JSON object with a custom ObjectMapper.

**Comment by anmol1vw13** [comment]
Thank you Vlad. It worked. I'm closing the issue.
