### ISSUE TITLE
Add byId methods to Hibernate repository

### ISSUE THREAD

**Issue by hinrik** [vladmihalcea/hibernate-types#511]
In [your article](https://vladmihalcea.com/best-spring-data-jparepository/), you say `HibernateRepository` is _The best Spring Data JpaRepository alternative_. However, it is not a drop-in replacement for `JpaRepository` because it misses all the useful by-id methods such as `findById()`. Why not include those?

**Comment by vladmihalcea** [comment]
The article explains that the `HibernateRepository` is not a drop-in replacement for `JpaRepository`, but an extension.

For instance, this is the `PostRepository` from the article:

```
@Repository
public interface PostRepository
    extends HibernateRepository<Post>, JpaRepository<Post, Long> {
 
}
```

As you can see, it extends both the `HibernateRepository` and the `JpaRepository`, so you are still having all the findById utilities.

However, in the next release, a new utility will be added which will be a drop-in replacement for the `JpaRepository`. Check out [this article](https://vladmihalcea.com/spring-data-base-repository/) for more details.
