### ISSUE TITLE
hibernate-types-55 converting to camel case

### ISSUE THREAD

**Issue by nivruth-naka** [vladmihalcea/hibernate-types#512]
We are using Microsoft SQL Server 2016 with hibernate-types-55 2.20.0 

When we have a Java object without a camel case convention and call save on the entity, it is automatically getting converted to camel case. For example: `{
  "Amount": 100
}` is being saved as `{
  "amount": 100
}` We validated that while serializing it is preserving the original format.

**Comment by vladmihalcea** [comment]
It's probably due to Jackson. However, you can provide a custom `ObjectMapper`, as explained in [this article](https://vladmihalcea.com/hibernate-types-customize-jackson-objectmapper/).

That way, you may customize the way the JSON Object is serialized to a String value.

**Comment by vladmihalcea** [comment]
Have you tried it, and it didn't work?

1. Why would the column type matter when the String serialization is done in the app?
2. Why would it matter if you use Gson in Spring Boot when the library uses Jackson internally?

But you don't have to follow my advice. Luckily, the project is open-source, so you are free to explore any other alternative you can come up with. That's the beauty of free software.
