### ISSUE TITLE
Mapping an array of PostgreSQL type?

### ISSUE THREAD

**Issue by mvh77** [vladmihalcea/hibernate-types#515]
Hi! Is it possible to map an array of a PostgreSQL type to a java List? I have something like this in mind:

```sql
CREATE TYPE localized_description AS (
    language varchar(2),
    description varchar(5000)
);
ALTER TABLE foobar ADD COLUMN descriptions localized_description[] NOT NULL DEFAULT '{}';
```

Thanks!

**Comment by vladmihalcea** [comment]
Anything is possible. That's the beauty of OSS. It's just Java code.

**Comment by mvh77** [comment]
:laughing: ok, so nothing out of the box that I would have missed. I'll see if I get a chance to dive deeper into this, thanks!

**Comment by vladmihalcea** [comment]
It supports ENUM arrays, which are also defined using TYPE. But I'm not sure what would be the Object type on the Java side.

If it worked, what would be the Java type that maps the `localized_description`?

**Comment by vladmihalcea** [comment]
> There would probably need to be a mechanism for defining it on a case by case, but I'm no Hibernate guru so I don't. Maybe it's easier to map it as a json collection

Yes, you can map it to a JSON column, and it will work fine.

> You must be a Transylvanian vampire

Well, yeah 🧛
