### ISSUE TITLE
Not passed a ParameterType - generally this indicates a hbm.xml binding case

### ISSUE THREAD

**Issue by lienide** [vladmihalcea/hibernate-types#521]
Hi!

I'm very like this article [how-to-map-json-objects-using-generic-hibernate-types](https://vladmihalcea.com/how-to-map-json-objects-using-generic-hibernate-types/)!

I use `*.hbm.xml` mapping files to mapping JPA `Entity` in my ddd project, and i get a `NPE` error when use JsonType as Entity's `ValueObject`, like this:

![image](https://user-images.githubusercontent.com/29501807/205503136-2021b20d-506b-4541-9621-ef1afe3842de.png)

I want use `.hbm.xml` mapping-file to keep clean my domain object, is there has a method that not passed a ParameterType - only generally this indicates a hbm.xml binding case?

Thanks!

**Comment by vladmihalcea** [comment]
Most likely that it doesn't work with HBM files. Hibernate has dropped support for HBM since 2006, so they probably didn't implement this dynamic parameter feature.

**Comment by lienide** [comment]
> Most likely that it doesn't work with HBM files. Hibernate has dropped support for HBM since 2006, so they probably didn't implement this dynamic parameter feature.
> 
> You're only option is to use annotations or use your own custom Type that removes that seParametrValues method.

I see `hibernate-mapping-x.dtd` in hibernate core 5.6.x as below, could you tell me official link about `Hibernate has dropped support for HBM since 2006`, i think i need switch to annotation-driven if necessary!

![image](https://user-images.githubusercontent.com/29501807/205529719-ffa4cbaa-8b1e-4ef0-a77a-770be870cbc4.png)

**Comment by vladmihalcea** [comment]
> I see hibernate-mapping-x.dtd in hibernate core 5.6.x as below, could you tell me official link about Hibernate has dropped support for HBM since 2006, i think i need switch to annotation-driven if necessary!

Sure thing. Open the [Hibernate User Guide](https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html), go to authors, check the first name, and then check my GitHub profile as well. I worked for Hibernate. It's me who rewrote the manual. When Hibernate added support for JPA in 2006, HBM lost its relevancy. And, when a feature was developed, it was first developed for annotations, not HBM.

Now, the reason HBM mappings work is for backward compatibility, but there are lots of new features that haven't been merged from annotations to HBM. 

That's why you won't find any HBM examples in any of my [300 articles about Hibernate](https://vladmihalcea.com/tutorials/hibernate/).

And, with the release of Hibernate 6, [HHH-15335](https://hibernate.atlassian.net/browse/HHH-15335) made this statement official.

**Comment by lienide** [comment]
> > I see hibernate-mapping-x.dtd in hibernate core 5.6.x as below, could you tell me official link about Hibernate has dropped support for HBM since 2006, i think i need switch to annotation-driven if necessary!
> 
> Sure thing. Open the [Hibernate User Guide](https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html), and right under the title, check the first name and see who's the main author of the current Hibernate User Guide, and you'll see that it's me.
> 
> Now, when I rewrote the manual, why do you think I created all the examples with annotations and not with HBM, as was the case in the Hibernate 3 manual?
> 
> When Hibernate added support for JPA in 2006, HBM lost its relevancy. And, when a feature was developed, it was first developed for annotations, not HBM.
> 
> Now, the reason HBM mappings work is for backward compatibility, but there are lots of new features that haven't been merged from annotations to HBM.
> 
> That's also why you won't find any HBM examples in any of my [300 articles about Hibernate](https://vladmihalcea.com/tutorials/hibernate/).
> 
> And, with the release of Hibernate 6, [HHH-15335](https://hibernate.atlassian.net/browse/HHH-15335) made this statement official.

Wowww!!

I really ignore that i'm sorry.

I think i see.

I will follow that like [300 articles about Hibernate](https://vladmihalcea.com/tutorials/hibernate/) as soon as possible.

Thank you very much!

**Comment by vladmihalcea** [comment]
You're welcome.
