### ISSUE TITLE
Feature Request: Typed IDs with generation type of IDENTITY and SEQUENCE

### ISSUE THREAD

**Issue by SimonHarmonicMinor** [vladmihalcea/hibernate-types#522]
Recently I have discovered the beauty of typed IDs in Hibernate. Suppose I have the `User` entity with `UUID` id that is set on the client side.

```java
@Entity
@Table(name = "users")
@Getter
public class User {
    @Id
    private UUID id;

    // other attributes don't matter for the use case
    
    public static User newUser(...) {
        var user = new User();
        user.setAttributes(...);
        user.setId(UUID.randomUUID());
        return user;
    }
}
```

The `@EmbeddedId` annotation can make this piece of code much more type safe.

 ```java
@Entity
@Table(name = "users")
@Getter
public class User {
    @EmbeddedId
    private User.ID id;

    // other attributes don't matter for the use case
    
    public static User newUser(...) {
        var user = new User();
        user.setAttributes(...);
        user.setId(UUID.randomUUID());
        return user;
    }

    @Data
    @Setter(PRIVATE)
    @Embeddable
    public static class ID {
        @Column(updatable = false)
        @NotNull
        private UUID id;
    }
}
```

And I can nicely fit it in my Spring Data JPA repository.

```java
public interface UserRepository extends JpaRepository<User, User.ID> { ... }
```

So, if I want to retrieve the `User` by ID or even perform a custom JPQL statement I don't have to deal with raw `UUID` types anymore that many entities can share. The compiler checks the type of the id.

Unfortunately, Hibernate does not provide user-friendly API to define typed IDs with `IDENTITY` and `SEQUENCE` strategies.

@vladmihalcea what it's your opinion about typed IDs usage? Do you think that some custom types like the `LongIdentity` or the `IntegerIdentity` would be a valuable addition to the wonderful Hibernate Types library?

**Comment by vladmihalcea** [comment]
Using UUIDs for entity identifiers is a terrible idea. Don't do that. Use something like a [TSID](https://github.com/f4b6a3/tsid-creator) instead.

And I don't see the value of over-complicating your mappings using that `EmbeddedId`.

**Comment by SimonHarmonicMinor** [comment]
@vladmihalcea 

> Using UUIDs for entity identifiers is a terrible idea. Don't do that. Use something like a [TSID](https://github.com/f4b6a3/tsid-creator) instead.

Thanks, I didn't know about the library. I'll check it out.

> But I don't see how that's more type-safe. Java is type-safe, and the entity identifier already has a type of its own.

Let me introduce a particular example. Suppose I have two entities: `User` and `UserGroup`. Both have `Long` IDs and the `SEQUENCE` strategy. Assume I want to assign `User` to some `UserGroup`. Here is the possible method declaration:

```java
void assignUserToGroup(Long userId, Long userGroupId)
```

Compiler won't complain about any errors, if make this mistake.

```java
assignUserGroup(userGroupId, userId)
```

Both IDs have `Long` type. So, no compile errors here. If I got a foreign key constraint violation, I'd be lucky. But if there are no foreign keys (or the passed parameters don't break the constraint), then I'm in a big trouble. What's even more frustrating, such bugs are hard to track because compiler won't help you anyhow.

On the contrary, look at the refactored option below.

```java
void assignUserToGroup(User.ID userId, UserGroup.ID userGroupId)
```

Now such bugs are impossible because the code won't compile. Besides, it also allows me to overload methods with the same names:

```java
class RoleAccess {
    // doesn't compile
    boolean hasAnyRole(Long userId, Role.. role) { ... }
    boolean hasAnyRole(Long userGroupId, Role... role) { ... }
}

class RoleAccess {
    // compiles successfully
    boolean hasAnyRole(User.ID userId, Role.. role) { ... }
    boolean hasAnyRole(UserGroup.ID userGroupId, Role... role) { ... }
}
```

The TSID approach is valid if I don't use sequences. Unfortunately, I cannot easily combine embeddable classes with sequences usage:

```java
@Entity
@Table(name = "users")
@Getter
public class User {
   @EmbeddedId
   private User.ID id;

   // other attributes don't matter for the use case
   
   public static User newUser(...) {
       var user = new User();
       user.setAttributes(...);
       user.setId(new User.ID());
       return user;
   }

   @Data
   @Setter(PRIVATE)
   @Embeddable
   public static class ID {
       // doesn't put the new ID value on entity persist action
       @GenerationType(strategy = SEQUENCE)
       private Long id;
   }
}
```

If I could integrate the `SEQUENCE` and the `IDENTITY` strategies with user-defined ID classes, it would be amazing. I'm thinking about something like this:

```java
@Entity
@Table(name = "users")
@Getter
public class User {
   @EmbeddedId
   @LongSequenceId
   private User.ID id;

   // other attributes don't matter for the use case
   
   public static User newUser(...) {
       var user = new User();
       user.setAttributes(...);
       user.setId(new User.ID());
       return user;
   }

   @Data
   @Setter(PRIVATE)
   @Embeddable
   public static class ID {
       private Long id;
   }
}
```

**Comment by vladmihalcea** [comment]
> If I got a foreign key constraint violation, I'd be lucky.

No need for luck. If you add a FK constraint, the DB will enforce it.

> But if there are no foreign keys

But if you don't have FKs, your transactions are not ACID, as they break the Consistency property.

Again, I don't see any benefit in introducing the `EmbeddedId`. It breaks the `Keep It Simple` strategy I use for everything that I design. More, it creates unnecessary Objects that have to be collected by the GC.

And, just like you can pass a `userId` by mistake to a `userGroupId`, you can mistakenly create a `User.ID` using the numeric value that was passed as a `userGroupId`.

**Comment by SimonHarmonicMinor** [comment]
@vladmihalcea 

> No need for luck. If you add a FK constraint, the DB will enforce it.

Suppose I have these IDs:

| UserId | UserGroupId |
|--------|-------------|
| 1      | 1           |
| 2      | 2           |

I want to assign `user=1` to `userGroup=2`. If one accidentally swaps the IDs arguments order, the foreign key wouldn't help me anyway. The assignment will proceed successfully but the final result will be unexpected.

> Again, I don't see any benefit in introducing the EmbeddedId. It breaks the Keep It Simple strategy I use for everything that I design.

Why do you think it breaks the KISS principle? Value objects usage is a common design pattern. For example, if I need to store phone numbers, then it's absolutely normal to create the `PhoneNumber` class to encapsulate all validations. I don't see much difference in comparison to IDs. Each value identifies a specific entity. I don't want somebody to query `Comment` with the `Post.ID`.

> More, it creates unnecessary Objects that have to be collected by the GC.

Point. But I think that we should state all performance caveats in comparison to something else. Even the fastest database query is measured in milliseconds (+ network delay). Whilst creating a new object spends nanoseconds or microseconds.

I agree that there are cases when CPU usage is crucial and one cannot afford to declare a wrapper for convenience. Anyway, I doubt those kinds of services work with relational databases and the Hibernate. If you're building a regular enterprise application that manipulates rows in the database and has complex domain logic, then you probably aim for security, design, and the particular queries performance.

**Comment by vladmihalcea** [comment]
> I want to assign user=1 to userGroup=2. If one accidentally swaps the IDs arguments order, the foreign key wouldn't help me anyway.

And, your solution will fail as well if you accidentally instantiate the wrong ID object.

FK ids are not assigned manually. They are usually assigned using Proxy references, as explained in [this article](https://vladmihalcea.com/spring-data-jpa-findbyid/).

Fetching the wrong Proxy references is covered by integration tests anyway.

**Comment by SimonHarmonicMinor** [comment]
> And, your solution will fail as well if you accidentally instantiate the wrong ID object.

I don't instantiate them directly. If I use Spring, I can tune Jackson and map them directly to the controller. Besides, if I retrieve an entity from the database, I can safely pass this ID everywhere (e.g. publish custom events and capture them in `@TransactionalEventListener` methods).

> Fetching the wrong Proxy references is covered by integration tests anyway.

Sure, I can write integration tests to validate the scenario. Anyway, it doesn't mean that specific domain objects are useless. Java is a statically typed language. Python is not. But if write many tests in Python, I can validate all the possible inputs and outputs. But compiler makes this job easier: I don't have to validate the case when somebody passed the `String` but expected `int`.

However, I got your point. I can't say I agree with that but I understand your arguments.

**Comment by vladmihalcea** [comment]
> I don't instantiate them directly.

Exactly.

> If I use Spring, I can tune Jackson and map them directly to the controller.

The way you automate that based on the entity type, it's the same for entity Proxies.

> But if write many tests in Python, I can validate all the possible inputs and outputs. But compiler makes this job easier: I don't have to validate the case when somebody passed the String but expected int.

Yes, and that's why the compiler will validate the entity identifier type when instantiating the Proxy from the the `EntityManager.getReference` call.

> However, I got your point. I can't say I agree with that but I understand your arguments.

You don't have to agree with me. Just because I'd never use that `EmbeddedId` indirection, it doesn't mean you can't use it. I prefer the KISS principle, as I explained in [this article](https://vladmihalcea.com/how-to-create-tech-startup/).

If you think this solution provides value to your team, then you don't need a stranger over the Internet to agree with your software design decisions.
