### ISSUE TITLE
JSON deserialization does not correctly return polymorphic lists with structured objects after merge

### ISSUE THREAD

**Issue by tobias-bahls** [vladmihalcea/hibernate-types#523]
When having a polymorphic list with entries that have a nested JSON object such as:

```json
[
  { 
   "type": "discount.coupon.percentage",
   "percentage": 0.02, 
   "banner": { "text": "On Sale", "color": "#000" }
  } 
]
```

The entity returned by `entityManager.merge` assigns a `List<LinkedHashMap<>>` to the field containing the polymorphic list instead of a `List<MyType>` which results in this exception:

```
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class MyClass (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; MyClass is in unnamed module of loader 'app')
```

When I retrieve the same entity from `entityManager`, the list is deserialized correctly.

A test case that reproduces the issue can be found [here](https://github.com/tobias-bahls/hibernate-types/blob/structured-polymorphic-test/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/json/polymorphic/PostgreSQLJsonPolymorphicListWithComplexStructureJacksonTypeTest.java). I'm happy to contribute a fix, but I'd need some pointers on where to start looking 

This is using hibernate-types-52:2.20 on JDK 17.

**Comment by tobias-bahls** [comment]
Unfortunately consulting is not an option. Would you have time to review a PR if I would post one?

**Comment by vladmihalcea** [comment]
If you have a PR, please sned it. But, as you can see in the [PR](https://github.com/vladmihalcea/hibernate-types/pulls) list, I didn't have time to review the ones sent 6 weeks ago. 

However, you can fork the project and build your own local copy that fixes the issue. You are not tied to this branch. That's the beauty of OSS.

**Comment by tobias-bahls** [comment]
After some investigation it turns out that the root cause of the issue is that the nested entity did not implement `Serializable`, making it serializable fixes the issue.

I think this is just an user error on my side, hence closing.
