### ISSUE TITLE
Spring 3.0.0 Hibernate 6.1 failing mapping JsonNode 

### ISSUE THREAD

**Issue by xuanpan** [vladmihalcea/hibernate-types#524]
I have recently upgrade to hibernate-types-60 under a Spring 3.0.0 upgrade and stuck on how to map my previous JsonNode column. The only way I figured is to map like this

 ```
@Type(JsonType.class)
@Column(name = "json_content", nullable = false)
private JsonNode jsonContent;
```

But the compiler fails on generating the hibernate code by giving me this error: `Attempt to recreate a file for type ... ` for all my entities

**Comment by vladmihalcea** [comment]
You can download this GitHub repository and run the Hibernate 6 integration tests, which map the `JsonNode` as well.

Then, you can compare why the examples in this repository work while yours don't.
