### ISSUE TITLE
Breaking strings with accents

### ISSUE THREAD

**Issue by charcoast** [vladmihalcea/hibernate-types#527]
I'm using Hibernate Types JsonType with MySQL, and I'm having trouble fetching Strings with accents used in Portuguese, such as "á", "ó", "ú", "ç" and "ã. These letters are replaced by a diamond � when I search from the database. Interestingly, when writing to the database in the JSON structure, the accent is correct.

Below is a print of the debugger
![image](https://user-images.githubusercontent.com/11007668/207315629-1881dbdb-08e2-4a80-9102-b6397555604a.png)

When the accented String is in a common MySQL String field , this problem does not occur, so I come here to ask for help.

I also ran the test present in the Hibernate Types project with the accent, and in this case it was correct, which left me even more confused.

**Comment by vladmihalcea** [comment]
That's a common encoding issue, most likely caused because your JVM and the DB use different encodings. If you set everything to use UTF-8 (browser, JVM, DB), it will work like a charm.

**Comment by charcoast** [comment]
I found this bug report which led to fix the problem in the MySQL JDBC driver.

https://bugs.mysql.com/bug.php?id=80631

**Comment by vladmihalcea** [comment]
I'm glad you found the solution.
