### ISSUE TITLE
Add support for PostgreSQL Interval column type

### ISSUE THREAD

**Issue by JWGmeligMeyling** [vladmihalcea/hibernate-types#53]
Hi Vlad,

I have a custom type for PGIntervals that I map to a Java duration. This is for example useful to map result sets of native queries that subtract one timestamp for another. Let me know if there's interest in adding it to the custom type library:

```java
public class PGIntervalType implements UserType {

    public static final PGIntervalType INSTANCE = new PGIntervalType();

    public Class<?> returnedClass() {
        return Duration.class;
    }


    public int[] sqlTypes() {
        return new int[] {Types.OTHER};
    }


    @Override
    public Object nullSafeGet(ResultSet rs, String[] names, SharedSessionContractImplementor session, Object owner) throws HibernateException {
        try {
            final PGInterval pgi = (PGInterval) rs.getObject(names[0]);
            final int days = pgi.getDays();
            final int hours = pgi.getHours();
            final int mins = pgi.getMinutes();
            final double secs = pgi.getSeconds();

            return Duration.ofDays(days)
                .plus(hours, ChronoUnit.HOURS)
                .plus(mins, ChronoUnit.MINUTES)
                .plus(Math.round(secs), ChronoUnit.SECONDS);

        }
        catch (Exception e) {
            return null;
        }
    }


    @Override
    public void nullSafeSet(PreparedStatement st, Object value, int index, SharedSessionContractImplementor session) throws HibernateException, SQLException {
        if (value == null) {
            st.setNull(index, Types.OTHER);
        }
        else {
            final Duration period = ((Duration)value);
            final int days = (int) period.toDays();
            final int hours = (int) (period.toHours() - days * 24);
            final int mins = (int) (period.toMinutes() - period.toHours() * 60);
            final int secs = (int) (period.getSeconds() - mins * 60);

            final PGInterval pgi = new PGInterval(0, 0, days, hours, mins, secs);
            st.setObject(index, pgi);
        }
    }


    public boolean equals(Object x, Object y)
        throws HibernateException {

        return x == y;
    }


    public int hashCode(Object x)
        throws HibernateException {
        return x.hashCode();
    }


    public Object deepCopy(Object value)
        throws HibernateException {
        return value;
    }


    public boolean isMutable() {
        return false;
    }


    public Serializable disassemble(Object value)
        throws HibernateException {
        return (Serializable) value;
    }


    public Object assemble(Serializable cached, Object owner)
        throws HibernateException {
        return cached;
    }


    public Object replace(Object original, Object target, Object owner)
        throws HibernateException {
        return original;
    }

}
```

**Comment by vladmihalcea** [comment]
Yes, sure. But you should extend the ImmutableType from this project which makes it easier to implement custom Types.

**Comment by JWGmeligMeyling** [comment]
Yes this is the little snippet that I'm currently using, but I'll provide a PR that adheres to the project's conventions 😄

**Comment by vladmihalcea** [comment]
Cool. Looking forward to it.

**Comment by vladmihalcea** [comment]
Integrated, thanks.

**Comment by JWGmeligMeyling** [comment]
Thanks! :+1:

**Comment by vladmihalcea** [comment]
I have no idea since I've never used Kotlin. Does your company want to pay for this feature?

**Comment by jilvin** [comment]
We could make it a feature if more people need it. I will be happy to help towards the same if some guidance could be provided from you. Our company is not looking forward for a paid development for this feature at the moment.

**Comment by vladmihalcea** [comment]
The code base is very straightforward, so you can surely implement this feature after you study the existing Types.

Looking forward to your Pull Request that implements this feature.

**Comment by jilvin** [comment]
Thanks a lot for your reply. I am currently occupied with work. But surely if this generates more interest, I would be glad to contribute towards supporting Kotlin Duration too. I am currently using the available converters between the Duration types in Kotlin. We could possibly use the same strategy for the library to support Kotlin Duration in the future.

Thanks again for your wonderful work on the library and for making it free and open source at the same time.

Towards a better future. Cheers.

**Comment by vladmihalcea** [comment]
You're welcome. Luckily, Kotlin is compatible with Java, so you can also use the Java Duration in the meantime.
