### ISSUE TITLE
Avoid creating too many Jackson ObjectMapper instances

### ISSUE THREAD

**Issue by Sam-Kruglov** [vladmihalcea/hibernate-types#530]
Jackson ObjectMapper is supposed to be shared but I see that the code created a whole bunch of these objects for no apparent reason. This is not a light object as well.

https://github.com/vladmihalcea/hibernate-types/blob/0cef559854363b0c4362aaac3d27b7d910ef4173/hibernate-types-55/src/main/java/com/vladmihalcea/hibernate/type/util/Configuration.java#L157

The code above also creates this object unconditionally even if I provide a supplier, so it will create this object and then immediately drop it because it'll find a supplier. 

Why don't we just use one instance everywhere like Spring MVC uses one? I see we have an instance here:

https://github.com/vladmihalcea/hibernate-types/blob/0cef559854363b0c4362aaac3d27b7d910ef4173/hibernate-types-55/src/main/java/com/vladmihalcea/hibernate/type/util/ObjectMapperWrapper.java#L28

The user-provided supplier could be called once instead of a bunch of times too. I currently build my supplier as a singleton.

**Comment by vladmihalcea** [comment]
The `ObjectMapper` is meant to be shared by all instances of the same Type. You could use different JSON Types that have unique configuration settings.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by Sam-Kruglov** [comment]
One suggestion would be to make `ObjectMapperSupplier` a singleton supplier or if the user doesn't build it this way, the mapper will be created multiple times
