### ISSUE TITLE
ObjectMapperWrapper throws NullPointerException when referencing the ObjectMapper

### ISSUE THREAD

**Issue by wimdeblauwe** [vladmihalcea/hibernate-types#533]
I upgraded `hibernate-types` from 2.14.1 to 2.21.0. When running our test suite on the build server (Azure DevOps), many of our tests fail with this NullPointerException:

```
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(Object)" because "this.objectMapper" is null
	at com.vladmihalcea.hibernate.type.util.ObjectMapperWrapper.toString(ObjectMapperWrapper.java:101)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.toString(JsonTypeDescriptor.java:100)
	at com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.unwrap(JsonTypeDescriptor.java:126)
	at com.vladmihalcea.hibernate.type.json.internal.JsonBinarySqlTypeDescriptor$1.doBind(JsonBinarySqlTypeDescriptor.java:24)
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:73)
```

After looking through the changelog, I noticed that #530 was part of the 2.21.0 release. I reverted to 2.20.0 and the problem went away.

Unfortunately, I don't have a test case to reproduce the problem. Even with our test suite, I don't have the problem locally, but I have it consistently on the build server. But I wanted to already create this issue in case other also run into this, then they can comment here if they might have more information.

In our application, we are using a `Supplier<ObjectMapper>` so `hibernate-types` can use our Spring Boot configured ObjectMapper, like this:

```
@Component("hibernateObjectMapper")
public class HibernateObjectMapper implements Supplier<ObjectMapper> {

    private static ObjectMapper objectMapper;

    @Autowired
    public void setObjectMapper(ObjectMapper objectMapper) {
        HibernateObjectMapper.objectMapper = objectMapper;
    }

    @Override
    public ObjectMapper get() {
        return objectMapper;
    }
}
``` 

We also have this in our `application.properties`:

```
hibernate.types.jackson.object.mapper=my.company.myproject.HibernateObjectMapper
```

We also have this:

```
@Component
public class HibernateBeanDependencyProcessor implements BeanFactoryPostProcessor {
    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory factory) {
        BeanDefinition beanDefinition = factory.getBeanDefinition("entityManagerFactory");
        String[] dependsOn = beanDefinition.getDependsOn();
        dependsOn = dependsOn == null ? new String[]{} : dependsOn;
        String[] newDependsOn = new String[dependsOn.length + 1];
        System.arraycopy(dependsOn, 0, newDependsOn, 1, dependsOn.length);
        newDependsOn[0] = "hibernateObjectMapper";
        beanDefinition.setDependsOn(newDependsOn);
    }
}
```

This is a post processor that ensures the `HibernateObjectMapper` is created first in the Spring context so hibernate-types will be able to correctly use it.

**Comment by vladmihalcea** [comment]
Looking at your code, it could be that the ObjectMapper reference is fetched before Spring resolves it.

You can add a breakpoint in the getObjectMapper method of your `HibernateObjectMapper` to confirm that.

**Comment by wimdeblauwe** [comment]
I agree, but the very strange thing is that I don't have the issue locally. So if I debug, the order of things is correct and Spring will inject its `ObjectMapper` before the `get()` is called on the supplier by `hibernate-types`. 
It is the only way that I know that can make `hibernate-types` use the application-wide Spring Boot `ObjectMapper`. I'd love to hear if there is another (better) way.

**Comment by vladmihalcea** [comment]
Then the problem is caused by Spring not firing the `HibernateBeanDependencyProcessor` on the build server.

I could make a change that would call the `ObjectMapper` lazily the first time it needs it, and theoretically, the `HibernateBeanDependencyProcessor` would have been called by then.

**Comment by wimdeblauwe** [comment]
That would be nice. Maybe the constructor of `ObjectMapperWrapper` should also check that the `ObjectMapper` it receives should be non-null to fail fast?

**Comment by vladmihalcea** [comment]
Fixed.
