### ISSUE TITLE
Support for Matrix persistence

### ISSUE THREAD

**Issue by jlarroque** [vladmihalcea/hibernate-types#54]
Hi there!

Great project!

Would be great if there is support to add a String matrix, like String[][] and not just String[].

**Comment by vladmihalcea** [comment]
Based on the existing Type, send me a Pull Request with a new PostgreSQL Type to support multi-dimensional arrays.

**Comment by vladmihalcea** [comment]
Better try to create a new Type for it and register on the entity property.

**Comment by vladmihalcea** [comment]
Matrix arrays are supported. Check out the [`MatrixArrayTypeTest`](https://github.com/vladmihalcea/hibernate-types/blob/b3d77a4fc1c69d0880156a4426ae66294902428a/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/array/MatrixArrayTypeTest.java) for an example.
