### ISSUE TITLE
Using JsonBinaryType to handle java.util.ArrayList 

### ISSUE THREAD

**Issue by alecharp** [vladmihalcea/hibernate-types#57]
Hello,

I'm trying to store a list of `String` in a PostgreSQL `Array`. Do to that, I found your library which seems to be solving this problem but I cannot figure out how to use it properly. 

I have this

```
@Type(type = "jsonb")
@Column(columnDefinition = "jsonb")
private List<String> owners = new ArrayList<>();
```

and the database value is 

```
{foobar}
```

and I get 

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token
```

which make sense, as an array would start with `[` and not `{`. But it seems that `ARRAY` in PostgreSQL are in `{}` and not `[]`.

Can you help me understand what I'm missing? Seems pretty obvious, but I cannot see it.

**Comment by vladmihalcea** [comment]
That value is not a proper JSON object. That's why it does not work.
