### ISSUE TITLE
Add EnumArrayType to support mapping database Enums as Java arrays

### ISSUE THREAD

**Issue by NazirLKC** [vladmihalcea/hibernate-types#58]
Hi,

Can you include the EnumArrayType you created [here](https://github.com/vladmihalcea/high-performance-java-persistence/blob/5.2/core/src/main/java/com/vladmihalcea/book/hpjp/hibernate/type/array/EnumArrayType.java) in this repo? That would be very helpful.

**Comment by NazirLKC** [comment]
After looking more into the code I referenced above, I noticed that it didn't quite meet my requirements. The EnumArrayType was translating Java enum arrays into integer arrays in PostgreSQL instead of enum type arrays. I've made some changes to the above code to be able to support PostgreSQL's enum type arrays in a generic way. I will create a pull request shortly for your review. Any feedback would be appreciated.

**Comment by NazirLKC** [comment]
The pull request is here #59

**Comment by vladmihalcea** [comment]
Cool. I'll check it out when I have some time.

**Comment by vladmihalcea** [comment]
This is available from version 2.3.5.

**Comment by NazirLKC** [comment]
Awesome, thanks!
