### ISSUE TITLE
Error with Type erasure and clone method

### ISSUE THREAD

**Issue by pedroxs** [vladmihalcea/hibernate-types#6]
[This method](https://github.com/vladmihalcea/hibernate-types/blob/26e93b805bea9eff30a62cab12d3b3676f0c1d40/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/json/internal/JacksonUtil.java#L40) breaks when trying to clone `java.util.List` and `java.util.Map` top level attributes. Maybe use serialization to create a deep copy, ex:
```
    public static <T> T clone(T value) {
        try {
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            ObjectOutputStream oos = new ObjectOutputStream(bos);
            oos.writeObject(value);
            oos.flush();
            oos.close();
            bos.close();

            ByteArrayInputStream bais = new ByteArrayInputStream(bos.toByteArray());
            return (T) new ObjectInputStream(bais).readObject();
        } catch (ClassNotFoundException | IOException ex) {
            throw new HibernateException(ex);
        }
    }
```

My current work around is to encapsulate such attributes on wrapper classes. Maybe there are other ways to go like `MixIns` or `Type` annotations, but I have not tried / don't know how to do those.

Suggestions?

**Comment by pedroxs** [comment]
I just found that Hibernate has this helper method: `org.hibernate.internal.util.SerializationHelper#clone`, maybe use this instead of Jackson for cloning purposes? WDYT

**Comment by vladmihalcea** [comment]
@pedroxs Please send me a Pull Request with a test case (you can copy/paste an existing one as a template) to replicate the issue. Then. I'll investigate it. Thanks.

**Comment by pedroxs** [comment]
@vladmihalcea my branch only had a test case reproducing the error and not a solution to the problem. As I mentioned on previous messages, I am still not sure how to solve this issue.

**Comment by vladmihalcea** [comment]
@pedroxs Based on your test, I changed the way `clone` is implemented so that we now use the `SerializationHelper` if the object is `Serializable` and use the previous clone otherwise. Check the 1.1.2 and it should fixe your issue.

**Comment by pedroxs** [comment]
Somehow I missed your commit... Will give it a try and post some feedback. Thanks

**Comment by pedroxs** [comment]
Worked like a charm. Thanks!
