### ISSUE TITLE
@JsonIgnoreProperties(ignoreUnknown = true) seems to be ignored

### ISSUE THREAD

**Issue by jelmew** [vladmihalcea/hibernate-types#60]
Hi

We are using this library in our system and we ran into the following issue. It seems that fasterXML annotations such as` @JsonIgnoreProperties(ignoreUnknown = true)` seem to be ignored, making deserialization fail. Is this behaviour as intended (I do not know with my limited jackson/fasterXML knowledge).

Kind regards,
Jelmer

**Comment by vladmihalcea** [comment]
It's unclear what the problem is. You need to provide a replicating test case. Fork the repository and create a new test case that demonstrates this issue. Send a Pull Request when you are done.

**Comment by jelmew** [comment]
HI. I'll try to do so tomorrow.

**Comment by vladmihalcea** [comment]
Great. I'll check it out once you have an example I can debug.

**Comment by jelmew** [comment]
Hi. I'm just being corrected by a colleague. We didn't look into the log and it was functioning correctly. Closing this issue.
