### ISSUE TITLE
Pass array types in PostgreSQL functions as parameters in JPA query

### ISSUE THREAD

**Issue by StanislavGubanov** [vladmihalcea/hibernate-types#61]
Hello, Vlad.

How use array types in PostgreSQL database functions with array params in JPA

https://www.postgresql.org/docs/current/functions-array.html

function for example:
```sql
CREATE OR REPLACE FUNCTION fn_helper_array_contains(a integer[],b integer[])
RETURNS boolean AS
$$
BEGIN
  return a @> b;
END;
$$ LANGUAGE 'plpgsql';

-- select fn_helper_array_contains (array[1,2,3]::integer[],array[1,2]::integer[]);
```
###

**Comment by vladmihalcea** [comment]
The ARRAY support in hibernate-types is for entity properties only. This is not supported with stored procedures as they don't take a Hibernate Type.

The only way to use ARRAY with stored procedures is via JDBC or using jOOQ.

**Comment by vladmihalcea** [comment]
[This commit](https://github.com/vladmihalcea/hibernate-types/commit/e87179d65021024ec06c624535df3c67f39ba69e) shows how you can do it:

CriteriaBuilder cb = entityManager.getCriteriaBuilder();
CriteriaQuery<Event> cq = cb.createQuery(Event.class);
Root<Event> root = cq.from(Event.class);
cq.select(root);

```
ParameterExpression containValues = cb.parameter(int[].class, "arrayValues");
cq.where(cb.equal(cb.function("fn_helper_array_contains", Boolean.class, root.get("values"), containValues), Boolean.TRUE));
TypedQuery<Event> query = entityManager.createQuery(cq);
int[] arrayValues = {12, 16};
query.unwrap(Query.class).setParameter("arrayValues", arrayValues, IntArrayType.INSTANCE);
List<Event> events = query.getResultList();
assertArrayEquals(new int[]{12, 14, 16}, events.get(0).getValues());
```

Notice the `unwrap` to `org.hibernate.query.Query.class` and passing the `IntArrayType.INSTANCE` to bind the parameter:

    query.unwrap(Query.class).setParameter("arrayValues", arrayValues, IntArrayType.INSTANCE);
