### ISSUE TITLE
Polymorphic List

### ISSUE THREAD

**Issue by mguilherme** [vladmihalcea/hibernate-types#65]
I'm trying to create a List with polymorphic to a jsonb without success!
- I have no objectMapper custom configuration
- Normal List and String List works.
- Polymorphic without List works just fine

The action column retains de @class property in json, the actions columns does not! 

Source:

```Java
@Data
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "orders")
@EntityListeners(AuditingEntityListener.class)
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
public class Order implements Identifiable<Long> {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    private Action action; // Works fine

    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    private List<Action> actions; // Doens't work

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class OrderDetail implements Serializable {
        private String content;
        private Integer amount;
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS)
    public interface Action extends Serializable {
        String getOperation();
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Add implements Action {
        private String operation;
    }


    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Remove implements Action {
        private String operation;
        private String other;
    }
}
```

**Comment by mguilherme** [comment]
> Polymorphic collections cannot be supported. Either you use a `List<JsonNode>` and do the conversion yourself, or just map the actual subclasses.

Thanks for the clarification @vladmihalcea

**Comment by ctytgat** [comment]
@vladmihalcea I just ran into this myself, and wonder what the reason could be that this isn't supported? 
Jackson can perfectly serialize and deserialize polymorphic lists, as long as the objects contain the correct type info.
But for some reason, hibernate serialization won't include the type info and so deserialization fails...

**Comment by ctytgat** [comment]
For completeness, my case looks like this:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = A.class, name = "a"),
        @JsonSubTypes.Type(value = B.class, name = "b")})
@Data
public class Base implements Serializable {
}

@Data
public class A extends Base {
}

@Data
public class B extends Base {
}

Entity field:

    @Type(type = "jsonb")
    @Column(columnDefinition = "json")
    @Getter
    private List<A> foo = new ArrayList<>(); --> won't deserialize

```

**Comment by joshiste** [comment]
Not tested but could work...

```
public class ActionList extends List<Action> {}
```

```
...
    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    private ActionList actions;
...
```

**Comment by andrewhall-premier** [comment]
I've created a library [polymorphic-json-support](https://github.com/stansonhealth/polymorphic-json-support) which adds polymorphic support for the json type.  It can perform serialzation/deserialization of collections of interfaces or base classes.  All you have to do is include it in the classpath - there is no configuration/customization required.
