### ISSUE TITLE
Jackson serialization exception for range

### ISSUE THREAD

**Issue by AbdulR3hman** [vladmihalcea/hibernate-types#67]
There is a problem when using the new ranges that was just recently merged with master #64  and the problem was due to no public getters/setters in the Range class.

I'm happy to fix it if allowed. I've fixed it locally by adding getters and setters for the upper and lower limits.

**Comment by vladmihalcea** [comment]
@AbdulR3hman Thanks for the ifx. Looking forward to it. Make sure you add a test case too.

**Comment by vladmihalcea** [comment]
Could be fixed by [this commit](https://github.com/vladmihalcea/hibernate-types/commit/9162090147a9e3014837e0041f4a6189216719da). If it's not, please reopen the issue.
