### ISSUE TITLE
Exception: Unable to load class [jsonb]

### ISSUE THREAD

**Issue by saurabhprakash** [vladmihalcea/hibernate-types#69]
I'm following this doc for setup: 

https://vladmihalcea.com/how-to-map-json-collections-using-jpa-and-hibernate/

Other related versions are: springboot(2.1)+postgres(10.5)+hibernate(5.3.7).

Following are changes in file:

In pom.xml

    ....
    <dependency>
        <groupId>com.vladmihalcea</groupId>
        <artifactId>hibernate-types-52</artifactId>
        <version>2.3.5</version>
    </dependency>
    ....

Entity definition:
```

@Entity(name = "Event")
@Table(name = "event")
@TypeDefs({
    @TypeDef(name = "string-array", typeClass = StringArrayType.class),
    @TypeDef(name = "int-array", typeClass = IntArrayType.class),
    @TypeDef(name = "json", typeClass = JsonStringType.class),
    @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class),
    @TypeDef(name = "jsonb-node", typeClass = JsonNodeBinaryType.class),
    @TypeDef(name = "json-node", typeClass = JsonNodeStringType.class),
})
public class Event {

    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    private List<Location> alternativeLocations = new ArrayList<Location>();

    //Getters and setters omitted for brevity
}
```

On running springboot application it given below error: 
 nested exception is org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [jsonb]

All other settings are standard sprintboot settings working with postgres. Post creation of this above error was coming.

Please let me know possible reason for same, Thanks in advance :)

**Comment by vladmihalcea** [comment]
Fork the project and run the JSON test cases in debug to see why mine work and your application does not.

I'll leave the issue open for a while so that you can add the solution to this problem. Most likely, it's a configuration issue.

**Comment by saurabhprakash** [comment]
This worked post doing a  force maven clean install ("mvn -f pom.xml clean install")

Thanks for reply 👍
