### ISSUE TITLE
Support for Java enums with explicit database ID value

### ISSUE THREAD

**Issue by nemecec** [vladmihalcea/hibernate-types#72]
After reading https://vladmihalcea.com/the-best-way-to-map-an-enum-type-with-jpa-and-hibernate/ I came up with an alternative solution that could be added to hibernate-types:

Have a `byte`/`int` field in each Java enum class with the DB persistent ID value. Have all such enums implement an interface with getter for that field (e.g. `getDatabaseValue()`). And implement a custom converter to convert such enum values into numeric values for storage to database.

This has the following benefits:
* as compact as the `int` ordinal approach without the downsides
* no problem when enum values are rearranged in Java code
* database ID is made explicit in Java code (otherwise you would need to count the enum values to figure out the ID that is used in the database)
* you can use `int` or `byte` (different interfaces) if you know in advance the number of enum values you expect to have

Sample:
```java
public enum Gender implements WithByteDatabaseValue {

  MALE(1),
  FEMALE(2);

  private final byte databaseId;

  Gender(int databaseId) {
    this.databaseId = (byte) databaseId;
  }

  @Override
  public byte getDatabaseValue() {
    return databaseId;
  }

}
```

```java
public interface WithByteDatabaseValue {

  byte getDatabaseValue();

}
```

```java
public interface WithIntDatabaseValue {

  int getDatabaseValue();

}
```

And then in Hibernate converter, you would do something like:
```java
if (obj instanceof WithByteDatabaseValue) {
  return ((WithByteDatabaseValue) obj).getDatabaseValue();
}
else if (obj instanceof WithIntDatabaseValue) {
  return ((WithIntDatabaseValue) obj).getDatabaseValue();
}
```

**Comment by vladmihalcea** [comment]
I don't see the advantage over using ordinal. The databaseId sounds like the Enum will be stored in a separate table, I'm which case ordinal works just fine combined with a shared identifier.

This solution looks overly complicated for a generic Type. It's better to be implemented as a project-specific Type.
