### ISSUE TITLE
RFI on differences between JsonStringType JsonNodeStringType

### ISSUE THREAD

**Issue by Stexxen** [vladmihalcea/hibernate-types#77]
I can see that `JsonNodeStringType` is extending `AbstractSingleColumnStandardBasicType<JsonNode>` as opposed to `<Object>` for the `JsonStringType` class. 

But the biggest difference appears to be the use of the interface `DynamicParameterizedType`

Could you possible explain it's use, and hopefully that will help me understand why a specific JsonNode version was created?

**Comment by vladmihalcea** [comment]
Just read [the first two articles](https://github.com/vladmihalcea/hibernate-types) provided in the README document and run the aforementioned unit tests in this repository you will understand the difference.

**Comment by Stexxen** [comment]
Perhaps my question wasn't worded in the best way.

I have read both articles and in them you state

> Because Hibernate does not support JSON types natively, we need a JsonNodeBinaryType to handle the Jackson-specific JsonNode object type.

Now that statement applies to PostgreSQL, as it uses the Binary type, I assume the same statement applies to MySQL with the String type.

Now I've experimented with JsonNodeStringType and JsonStringType to persist a JsonNode object and both work great. Hence my confusion.

Now it could be that a combination of MySQL 5.7 and Hibernate 5.4 means that whatever distinction made this separation required is no longer necessary?

**Comment by vladmihalcea** [comment]
> Now that statement applies to PostgreSQL, as it uses the Binary type, I assume the same statement applies to MySQL with the String type.

That statement is about Hibernate support for a Java object type, so it applies to any RDBMS that can store JSON.

> Now it could be that a combination of MySQL 5.7 and Hibernate 5.4 means that whatever distinction made this separation required is no longer necessary?

`JsonNodeStringType` is for `JsonNode` while `JsonStringType` is for POJOs.

**Comment by vladmihalcea** [comment]
In the beginning, the `JsonStringType` did not get the type from the annotated property. Nowadays, you can use the `JsonStringType` even for `JsonNode`, so you can use either one.

**Comment by Stexxen** [comment]
That's what I was wondering, so thanks for clarifying.

You've created an Excellent library.
Thanks.

**Comment by vladmihalcea** [comment]
Thanks. If you like this library, you are going to love my [High-Performance Java Persistence book](https://vladmihalcea.com/books/high-performance-java-persistence/) even more.
