### ISSUE TITLE
Issue with ZonedDateTimeRanges and DST

### ISSUE THREAD

**Issue by Simbosan** [vladmihalcea/hibernate-types#78]
I have a Range field in my @Entity

@TypeDef(name = "range", typeClass = PostgreSQLRangeType.class, defaultForType = Range.class)
public class BiomaterialTimeWindowed extends Biomaterial
{
    Range<ZonedDateTime> activeRange;

This maps to a tstzrange column in the table

When you store a value it modifies the offset if the date falls within DST so therefore:

activeRange = Range.zonedDateTimeRange("[2014-05-28T16:00:01+12, 2018-12-28T16:00:05+12]")

Leads to the following in the database:
[2014-05-28T16:00:01+12, 2018-12-28T16:00:05+13]

But then we you query the field an error gets thrown 
399: IllegalArgumentException("The upper and lower bounds must be in same time zone!");

For example if I use a Spring Data Rest endpoint to list those entities I get this error.

First, a workaround would be good. But does it makes sense to make this restriction?

**Comment by vladmihalcea** [comment]
Send me a Pull Request with a test case that replicates the issue. I'll check it out afterwards.

**Comment by Simbosan** [comment]
Need a Postgres instance so I've created a simple Spring Boot application that demos the problem

The class CreateEntitiesWithTestRanges contains comments on how to reproduce

https://github.com/Simbosan/tztzrange-bug

Cheers

Simon

**Comment by Simbosan** [comment]
Pull request created. Fingers crossed I did it right

**Comment by vladmihalcea** [comment]
Thanks. I'll check it out when I have some time.

**Comment by vladmihalcea** [comment]
Thanks. I fixed it with [this commit](https://github.com/vladmihalcea/hibernate-types/commit/eea1e37eab0f0bcfa154db22065f0fbae1e03557).

**Comment by Simbosan** [comment]
Nice, thanks very much.  I had tried with OffsetDateTime but didn't have time to work it all the way through.

Will this appear on Maven or should I clone and use that?

**Comment by vladmihalcea** [comment]
I will release a new version soon.

**Comment by vladmihalcea** [comment]
I released the 2.4.1 version which contains the fix for this issue.

**Comment by Simbosan** [comment]
Brilliant, thanks very much.
