### ISSUE TITLE
Support insertion of String values into JSON columns

### ISSUE THREAD

**Issue by gunnarmorling** [vladmihalcea/hibernate-types#80]
I have a `String` property which contains a JSON representation. Inserting this into a PG "json" column fails:

    postgres_1       | ERROR:  column "payload" is of type json but expression is of type character varying at character 89
    postgres_1       | HINT:  You will need to rewrite or cast the expression

It would be nice to have support for this without having to parse the value into a `JsonNode` again.

**Comment by vladmihalcea** [comment]
The [`PostgreSQLJsonStringPropertyTest`](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/test/java/com/vladmihalcea/hibernate/type/json/PostgreSQLJsonStringPropertyTest.java) demonstrates that this feature is already supported.

This is mapping that you need to set:

    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    private String properties;

And this is the `jsonb` definition:

    @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
