### ISSUE TITLE
EnumArrayType issue when have multiple fields with different enums arrays

### ISSUE THREAD

**Issue by jltnf54** [vladmihalcea/hibernate-types#84]
I am having an issue using multiple enum type arrays in the same entity. See below

`
@Entity
@TypeDefs({
  @TypeDef(name = "pgsql_enum_array", typeClass = EnumArrayType.class),
`
and fields:
`
  @Column(columnDefinition = "my_type[]")
  @Type(
      type = "pgsql_enum_array",
      parameters = {@Parameter(name = EnumArrayType.SQL_ARRAY_TYPE, value = "my_type")})
  private MyType[] mytype;

  @Column(columnDefinition = "your_type[]")
  @Type(
      type = "pgsql_enum_array",
      parameters = {@Parameter(name = EnumArrayType.SQL_ARRAY_TYPE, value = "your_type")})
  private YourType[] yourtype;
`
The EnumArrayType create a single instance of EnumArrayTypeDescriptor so the object so the final arrayObjectClass will be the last item register by the @Type.  

  arrayObjectClass = ((ParameterType) parameters.get(PARAMETER_TYPE)).getReturnedClass();

**Comment by vladmihalcea** [comment]
This needs to be handled like JSON types. So, you need to create a replicating test case and provide a fix in a similar way as `JsonNodeBinaryType`.

I'll take a look after you submit the Pull Request.

**Comment by jltnf54** [comment]
so i can contribute in a pull request?

**Comment by jltnf54** [comment]
i will submit one shortly

**Comment by vladmihalcea** [comment]
That's the spirit of open source software development.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by vladmihalcea** [comment]
Released in 2.4.3.
