### ISSUE TITLE
java.lang.IllegalArgumentException: The given string value: {"uuid": ".........l} cannot be transformed to Json object

### ISSUE THREAD

**Issue by Hemalrajapaksha** [vladmihalcea/hibernate-types#88]
@vladmihalcea , I'm using com.vladmihalcea version 4.3 for saving several JSONs objects in my PostgreSQL database
data saving part is working as expected but there is an issue when deserializing particular rows.

```
//1st object

@TypeDefs({
		@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
})
@AutoScaleFactor
@Entity
@Table(name = "TESTEXECUTIONPLAN")
public class TestExecutionPlanBO extends BusinessObjectImpl {	
	private static final long serialVersionUID = -6454L;
	@Id
	private String testPlanID;
	private String testPlanName;
	private int testCasesCount;
    ......
       @Type(type = "jsonb")
       @Column(columnDefinition = "json")
	private JobVO jobVoJson;
```

```

//2nd object
@TypeDefs({
		@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
})

@TrustedBO
@Entity
@Table(name = "EXECUTIONREQUESTS")
public class ExecutionRequest extends BusinessObjectImpl{

	private static final long serialVersionUID = -517242L;
	@Id
	private String uuId;
	private String orderId;
	........

	@Type(type = "jsonb")
	@Column(columnDefinition = "json")
	private ExecutionRequestVO executionRequest;
}
```

When listing both tables 1st table is working fine. When retrieving the second it gives the above error.
The issue is inside JsonTypeDescriptor.java 
`
```
  private static Class<?> jsonObjectClass;

    @Override
    public void setParameterValues(Properties parameters) {
        jsonObjectClass = ( (ParameterType) parameters.get( PARAMETER_TYPE ) )
                .getReturnedClass();

    }
````

jsonObjectClass variable is not changing when it comes to the second table. both times it trying to deserialize by using same object class(JobVO). the second time it should be ExecutionRequestVO

What am I suppose to do to fix the issue 
Hibernate version - 4.3.0.Final
PostgresSQL version - 42.1.3.jre7
com.vladmihalcea - 2.4.0

**Comment by vladmihalcea** [comment]
Try to replicate the issue with a test case. Once you could replicated it, send me a Pull Request so I could take a look on it.

**Comment by vladmihalcea** [comment]
Closed because no replicating test case was sent.
