### ISSUE TITLE
Cannot use @OneToMany relations to entities having jsonb columns when using TABLE_PER_CLASS inheritance

### ISSUE THREAD

**Issue by mdiotude** [vladmihalcea/hibernate-types#92]
I have a project where I have two related entities, let's say A and B, using the `TABLE_PER_CLASS` inheritance strategy. In this case B extends A. Another entity C has a `@OneToMany` relation to the base class A. When trying to retrieve the items for the collection of A in C Hibernate performs a query with a `UNION ALL` clause between A and B.
In the above situation when should B contain a jsonb type column, the union query fails with the following error:
`org.postgresql.util.PSQLException: ERROR: UNION could not convert type jsonb to uuid`.
In the union Hibernate selects `null` constants for the columns that are not present in either table, each cast to its type. But for the jsonb column it selects `null:uuid`.
Probably something needs to be done with the PostgresDialect so that Hibernate recognizes the correct type and does the cast correctly?

I created a test class to reliably reproduce the issue, please see the attachment.
[PostgreSQLJsonInheritanceTest.java.zip](https://github.com/vladmihalcea/hibernate-types/files/3059909/PostgreSQLJsonInheritanceTest.java.zip)

**Comment by vladmihalcea** [comment]
As I explained in my [High-Performance Java Persistence book](https://vladmihalcea.com/books/high-performance-java-persistence/), the TABLE_PER_CLASS inheritance strategy is a terrible idea. You should never use it.

Therefore, I don't think it's worth fixing a use case you should never use.

What you describe is probably a Hibernate issue than a issue in this framework. Therefore, you should investigate it and open a Jira issue for Hibernate if that's the case.

**Comment by vladmihalcea** [comment]
[This article](https://vladmihalcea.com/hibernate-no-dialect-mapping-for-jdbc-type/) can help you as well.

**Comment by mdiotude** [comment]
Thanks! I'll definitely try overriding the Dialect, hopefully it helps with my case. I'd rather avoid changing the inheritance at this time.

I understand your position regarding this particular issue, but I still have concerns that there might be some mapping missing in your framework.
The root cause is that Hibernate somehow "thinks" that the native type for jsonb columns is "uuid", which sort of makes sense since that is the only thing registered in the dialect to handle Types.Other. In my example the column field is a String, that could be why it made that match.

Please correct me if I'm wrong, but I don't see anywhere in the framework were we map the Json hibernate types to native "jsonb" data type. The closest thing I see is the `columnDefinition` , but that should only be used to create the table. I don't know if there is some other process in Hibernate that requires using the data type directly; from the article you linked it looks like native queries might be another one.

Perhaps the custom dialect in the article should be part of this framework? At least one advantage could be to avoid having to use `columnDefinition`, which makes the code less portable in my view.

**Comment by vladmihalcea** [comment]
The problem is not in this framework. It's due to how Hibernate maps Types.OTHER for PostgreSQL. I had one proposal to the Hibernate IRM project, but if was postponed for 6.0. So, either it will be fixed in Hibernate ORM or you will have to take care if it in your application.

**Comment by mdiotude** [comment]
Yes, I get your point. Customizing the dialect does feel like a workaround to me, so I can understand why you don't want such a thing in your framework.
I've also been having trouble with Hibernate's mappings for Oracle. Then too I had to create a custom dialect. There is definitely some room for improvement in how Hibernate does its mappings.

I do use FlywayDB actually :) I was following your article [https://vladmihalcea.com/how-to-map-json-objects-using-generic-hibernate-types/] and there you do mention specifically to use different values for the `columnDefinition`, which led me to believe that was somehow important to use. Good to know that's not the case.

Anyway, thanks again very much for your help! I'm actually curious about your book, you might have a new customer soon ;)

**Comment by vladmihalcea** [comment]
You're welcome and enjoy reading it. You're going to love it.
