### ISSUE TITLE
Add support for DDL in PostgreSQL arrays

### ISSUE THREAD

**Issue by agolovenko** [vladmihalcea/hibernate-types#95]
While using this lib PostgreSQL arrays works fine, the testing is limited. During DB initialisation phase hibernate fails to generate a proper DDL for tables that have array types mapped with exception: 

`Caused by: org.hibernate.MappingException: No Dialect mapping for JDBC type: 2003`

Would be really nice to have DDL support for array types as well.
Otherwise great lib, many thanks!

**Comment by vladmihalcea** [comment]
Everything works just fine already. If this was not supported, then no test could run as the DDL is generated automatically prior to every run.
