### ISSUE TITLE
Add support for mapping ARRAY to a java.util.List

### ISSUE THREAD

**Issue by bendem** [vladmihalcea/hibernate-types#97]
You can already map a postgresql ARRAY to a java array, but using raw arrays is not exactly idiomatic in java. Would'nt it make sense to allow mapping it to a `Collection` instead?

**Comment by vladmihalcea** [comment]
Yes, it can be done. Send me a Pull Request with the implementation. Looking forward to it.

**Comment by nstdio** [comment]
@vladmihalcea I can take it, can you assign this issue to me?

**Comment by vladmihalcea** [comment]
Done. Thanks for adding your contribution.

**Comment by bendem** [comment]
Awesome, thank indeed @nstdio

**Comment by vladmihalcea** [comment]
Fixed by [this commit](https://github.com/vladmihalcea/hibernate-types/commit/a53a39b5217a44f74095f0b3c24f6be7966c30a9).
