### ISSUE TITLE
Postgres inserting to json column type using JsonNode

### ISSUE THREAD

**Issue by sivaalli** [vladmihalcea/hibernate-types#98]
Hi Vlad Mihalcea,

Thanks for your great work on creating json types for JPA/hibernate.

My use case is to have a JsonNode property type in Entity and wanted to map it to json column type in Postgres. When I implement this using TypeDef with typeClass as JsonNodeStringType, I'm seeing an error 
`org.postgresql.util.PSQLException: ERROR: column "node" is of type json but expression is of type character varying` 
But when I modify database table to use jsonb and use TypeDef with typeClass as JsonNodeBinaryType, I was able to successfully insert to DB. I could have used jsonb but jsonb in postgres has a little overhead and consumes more memory.

Please find my git project example here: 
https://github.com/sivaalli/spring-jpa-postgres-json

You can directly run main class. This will start embedded postgres and inserts sql scripts necessary and then runs java process.

**Comment by vladmihalcea** [comment]
That's by design. Use `JsonNodeBinaryType` with PostgreSQL. `JsonNodeStringType` is for MySQL, as explained in the provided examples.

**Comment by sivaalli** [comment]
Ok. I think java doc is misleading. It just says "Maps a Jackson {@link JsonNode} on a String JSON column type" but does not specifically call out for MySQL database.

**Comment by vladmihalcea** [comment]
You should send me a PullRequest with the fix.

**Comment by vladmihalcea** [comment]
Fixed in 2.4.4.
